In [2]:
import pandas as pd

s1 = pd.read_csv("dataset/train/train_source1.tsv", sep="\t")
s2 = pd.read_csv("dataset/train/train_source2.tsv", sep="\t")
s3 = pd.read_csv("dataset/train/train_source3.tsv", sep="\t")
gt = pd.read_csv("dataset/train/train_ground_truth.tsv", sep="\t")

for name, df in [("source1", s1), ("source2", s2), ("source3", s3), ("ground_truth", gt)]:
    print(name, df.shape)
    print(df.head(), "\n")

source1 (2206821, 4)
      entity_id            business_name  \
0  S1-925783039      Orelee's Barbershop
1  S1-773889195              Prime Money
2  S1-377745466            B+ Retail Inc
3  S1-133037285            Christ Chapel
4  S1-755362802  Prabhav Business Center

                                    business_address country
0             1795 Westchester Drive, High Point, NC      US
1                    17560 Ellis Road, Tahlequah, OK      US
2                1712 Montebello Avenue, Phoenix, AZ      US
3  2100 Cameron Drive, Unit APARTMENT G, Dundalk, MD      US
4  797, Lake Town Block A, Kolkata, Howrah, West ...   India

source2 (5034616, 4)
      entity_id                    business_name  \
0  S2-166376419  राम मार्केटिंग प्राइवेट लिमिटेड
1  S2-764573417     -- Holloway Peak Inc Seafood
2  S2-639257739         आदित्य प्रॉपर्टीज एलएलपी
3  S2-163963287                       Summit Inc
4   S2-49942811     Delta Tetlecommunication Inc

                                   business_address country
0      KH NO. -570/13, NEW DELHI, WEST DELHI, Delhi   India
1                         105 ELM ST, MORGANTON, NC      US
2  G-3/571, GULMOHAR COLONY, BHOPAL, Madhya Pradesh   India
3             GREENSBORO, NC, 19 1/2 STARDUST TRAIL      US
4                   914 PIERPONT AVE, CLEVELAND, OH      US

source3 (5285603, 4)
      entity_id                                business_name  \
0  S3-202863386                           wilfordhancock.com
1  S3-859268022  International South Consultants Private Ltd
2   S3-22467283                  LLC Moncada Léarning Center
3  S3-671162755                               Moyna's Coffee
4  S3-960981775                 Pvt. EFS Print Ventures Ltd.

                                    business_address country
0                        Mack Rd, Haltom City, Texas      US
1                                                NaN   India
2                    5780 Fawn Ct, Fort Worth, Texas      US
3       1 Ivanhoe Ave, PO Box 6009, Cincinnati, Ohio      US
4  Door No 183, 41St Cross, 22Nd Main 9Th Block J...   India

ground_truth (2206821, 2)
  source1_entity_id                                 matched_entity_ids
0         S1-965667  S2-681193310,S2-743505751,S3-775321672,S3-1129...
1       S1-55344266  S2-249013014,S2-197070651,S3-478195123,S3-3843...
2      S1-343815751             S2-790675320,S2-479876582,S3-878454467
3      S1-656753428              S2-153058913,S2-24659151,S3-679606215
4      S1-102811957  S2-478959098,S2-553508714,S2-625774905,S3-7280...

In [8]:
def blocking_key(name, country):
    if pd.isna(name):
        return f"{country}_MISSING"
    clean = name.lower().strip()
    clean = ''.join(c for c in clean if c.isalnum())
    return f"{country}_{clean[:4]}"

In [9]:
print(s1['country'].value_counts())
print(s2['country'].value_counts())
print(s3['country'].value_counts())

country
US       1323633
India     883188
Name: count, dtype: int64
country
US       3016817
India    2017799
Name: count, dtype: int64
country
US       3170056
India    2115547
Name: count, dtype: int64

In [10]:
# apply blocking key to every row
s1['block_key'] = s1.apply(lambda r: blocking_key(r['business_name'], r['country']), axis=1)
s2['block_key'] = s2.apply(lambda r: blocking_key(r['business_name'], r['country']), axis=1)
s3['block_key'] = s3.apply(lambda r: blocking_key(r['business_name'], r['country']), axis=1)

# how many records land in each bucket, for s2 and s3?
print(s2['block_key'].value_counts().describe())
print(s3['block_key'].value_counts().describe())

count    226543.000000
mean         22.223666
std         273.103238
min           1.000000
25%           1.000000
50%           2.000000
75%           4.000000
max       39818.000000
Name: count, dtype: float64
count    229562.000000
mean         23.024730
std         293.836371
min           1.000000
25%           1.000000
50%           2.000000
75%           4.000000
max       46761.000000
Name: count, dtype: float64

In [11]:
print(s1['business_name'].isna().sum(), s1.shape[0])
print(s2['business_name'].isna().sum(), s2.shape[0])
print(s3['business_name'].isna().sum(), s3.shape[0])

0 2206821
2 5034616
13 5285603

In [12]:
print("SOURCE 2 - TOP 20 LARGEST BUCKETS")
print(
    s2["block_key"]
    .value_counts()
    .head(20)
)

print("\nSOURCE 3 - TOP 20 LARGEST BUCKETS")
print(
    s3["block_key"]
    .value_counts()
    .head(20)
)

SOURCE 2 - TOP 20 LARGEST BUCKETS
block_key
India_priv    39818
US_pedi       30732
US_inte       27623
India_shri    26765
US_prim       15516
US_metr       15271
India_limi    15079
India_indi    14030
US_fami       13736
US_card       12399
US_brig       12287
US_dent       11115
US_west       10930
India_tech    10884
US_phys       10824
US_stra       10666
US_blue       10581
US_corn       10578
US_derm       10505
US_foot       10408
Name: count, dtype: int64

SOURCE 3 - TOP 20 LARGEST BUCKETS
block_key
India_priv    46761
US_pedi       31261
India_shri    30313
US_inte       28251
India_limi    19190
US_prim       15866
India_indi    15821
US_metr       15206
India_shiv    14151
US_fami       13720
India_tech    12809
US_card       12416
US_brig       12391
India_shre    11952
US_dent       11472
US_west       11148
US_delt       11139
US_phys       10860
US_corn       10768
US_stra       10746
Name: count, dtype: int64

In [13]:
top_s2_keys = s2["block_key"].value_counts().head(10).index

for key in top_s2_keys:
    print("\n" + "=" * 80)
    print("BLOCK KEY:", key)
    print("COUNT:", (s2["block_key"] == key).sum())

    display(
        s2.loc[
            s2["block_key"] == key,
            ["entity_id", "business_name", "business_address", "country"]
        ].head(20)
    )

================================================================================
BLOCK KEY: India_priv
COUNT: 39818

,entity_id,business_name,business_address,country
41,S2-978126813,Private Ambernath Sólar Limited,"PLOT NO B-78/1, ADDITIONAL MIDC ANAND NAGAR, A...",India
114,S2-435778329,PRIVATE AHMEDABAD INFRATECH (LTD),"A-29 KARAMACHARINAGAR IGHATLODAIA, AHMEDABAD, ...",India
178,S2-308505251,Private Dronagiri College Overseas Limited,"NO.501/C, NULL, BENGALURU, BANGALORE, ಕರ್ನಾಟಕ",India
433,S2-590774517,Private RVA Addibivse Limited,"HINDI SAHIYA PARISHADBUILDING BULANDSAHAR, UTT...",India
458,S2-811707035,Private Sonali Mbamkftisng [Limited],"127, GROUND FLOOR SAHARA SHOPPING CENTRE, INDI...",India
629,S2-369458829,Private New Investments Ltd,"Kerala, KOZHIKODE, 17/581 V",India
641,S2-838493982,Private Seven Global Ltd,"7-10, West Bengal, NADIA, CINEMA HOUSE LANE, K...",India
642,S2-12796093,Private Bombay Klrihnna Systems Limited,"POOVALAMBEDU DIST TIRUVALLUR, 15 OLD NO 8 MADH...",India
643,S2-955730734,Private Shaikpet Capital Ltd,"G-2ND FLOOR, PLOT NO755, ROAD NO36, HYDERABAD,...",India
649,S2-570191750,privateparksquare.com,"3RD FLOOR, RATNANJALI SQUARE, NEAR GLORIYA RES...",India
669,S2-189892225,Private Landmark Interiors Límited,"#433 GODOWN-4, GURGAON, Haryana",India
752,S2-699404448,private js trading limited,"H-NO. 5-22/4, PALAMANER, ఆంధ్రప్రదేశ్",India
833,S2-164651728,Private Shiv Food Limited,"NEW DELHI, NEW FRIENDS COLONY, A - 211, Delhi",India
941,S2-744794854,PRIVATE GAGANDEEP MARBLES LIMITED,"#108 H-BLOCK F NEW ALIPORE, CALCUTTA, KOLKATA...",India
1063,S2-158902765,Private Streamline Products Límited,H.NO 991 C/O SAKHARAM DEORAO TEKALE AT SAUTADA...,India
1352,S2-693296247,Private Indo Maa Solutions [Limited],C/O PENNAPUREDDY VENKAT H NO 4-95/1/7 BAVANI N...,India
1481,S2-498046006,Private Exports Eric Series Ltd,"Maharashtra, PALM SPRING LK RD, NEAR D MART, M...",India
1492,S2-640420911,PRIVATE LAKSHMI INVESTMENTS LIMITED,"V-##17, NEHRU ENCLAVE, LUCKNOW, Uttar Pradesh",India
1519,S2-223117200,Private White Infra Motors Limited,"NO 39 NEW EXTENSION COLONY, FARIDABAD, PALWAL,...",India
1803,S2-198938800,Private Laxmi Foundation [Limited],"H.NO C-114, THIRUNEERMALAI MAIN ROAD NAGALKENI...",India

================================================================================
BLOCK KEY: US_pedi
COUNT: 30732

,entity_id,business_name,business_address,country
61,S2-457500956,Pediatric Dentistry Crystal Care Incorporated,"##6806 ROBIN DR, WY, GILLETTE CITY",US
277,S2-516249560,Pediatric Medicine Partners,"#821 CARRIAGE HOUSE CIRCLE, EVNSVILLE, IN",US
280,S2-716687956,Pediatric Dental Group Inc. Center,"3327 BEDFORD LANE, MONTGOMERY, AL",US
499,S2-716961117,Pediatric Dental Coastal Health Incorporated,"#7528 BOONVILLE HWY, EVANSVILLE, IN",US
510,S2-734993182,Pediatric Dental Partners of Taylorville Inc.,"929 1250 RD N, TAYLORVILLE, IL",US
730,S2-199669656,pediatricdentalspecialists.com,"8636 DEN BALK DRIVE, CHESTERFIELD COUNTY, VA",US
763,S2-176968531,Pediatric Dental Group Inc,"SEEKONK, #23 JUNIPER RD, MA",US
950,S2-310613953,Pediatric Northside Better Physicians [Dental],"3037 IMPRESSIONS DR, LAKE IN THE HILLS, IL",US
1341,S2-92868774,Pediatric Dentistry Associates,"NC, 881 SHORE DR, SOUTHPORT",US
1388,S2-866650875,Pediatric Dentistry Group Group Partners,"12017 OBEE RD, HAVEN, KS",US
1449,S2-39079223,Pediatric-Care,"66 MURRAY ST, PO BOX 5644, BINGHAMTON, NY",US
1747,S2-38917398,Pediatric Clinic Star,"13203 MESA VERDE DR, SUN CITY WEST, AZ",US
2028,S2-399449669,"Pediatric Déntistry Associates of Salisbury, L...","4175 MT HOPE CHURCH RD, <NULL>, SALISBURY, NC",US
2029,S2-574914445,Pediatric Dentistry Rocky Specialists Inc,"4102 NAVARRO, GALVESTON, TX",US
2921,S2-145521404,Pediatric Dentistry Cáre Ass0ciates,"GRANGER, 100 ARKOSE PASS, TX",US
2936,S2-671212976,pediatricdentalassociates.com,"TUCSON, COUNTRY CLUB RD, AZ",US
3373,S2-39401964,Pediatric Denta1 Associates [Partners],"BOONE, NC, 0122 SHILOH LN",US
3483,S2-27986137,Pediatric Dentistry Medicine Partners Corporation,"12939 1/2 MANSFIELD AVENUE, SPOKANE VALLEY, WA",US
3608,S2-619859806,Pediatric Health,"34A STRAWBERRY LANE, CITY OF APPLETON, WI",US
3715,S2-158363027,PEDIATRIC DETLGTFAY COASTAL PARTNERS GROUP,"CHURCH HILL, 699A OKOLONA RD, TN",US

================================================================================
BLOCK KEY: US_inte
COUNT: 27623

,entity_id,business_name,business_address,country
501,S2-474346550,Internal Medicine Cdcnic of Brooklyn Inc,"2652 22 ST, PO BOX 6831, BROOKLYN, NY",US
548,S2-146516261,Interfaith Ministries,"Juniper St, BATH, NY",US
1172,S2-699391872,INTERNAL MEDICINE PHYSICIANS LLC,"400 L COLEMAN DRIVE, MILLSBORO, DE",US
1246,S2-382377359,Interstate Ridge Tsak0s L.L.C.,"09 FIR LN, INCORPORATED, IL",US
1317,S2-845577049,Interfaith Charities,"5537 Denton Dr, RUSSELLVILLE, TN",US
1666,S2-886131666,"INTEGRATED LLC-BLUEROCK, DIRECT","2403 VAN DYKE AVE, RALEIGH, NC",US
1958,S2-772269040,internal medicine clinic group,"765 OLD LICK CREEK ROAD, LOUISA, KY",US
2042,S2-426439815,Internal LLC Associates Medicine,"1123 LEWIS JONES BOULEVARD, TN, GALLATIN",US
2076,S2-372202978,@interstatecoalition,"#N3983 BADEN STREET, COLUMBUS, WI",US
2552,S2-209093728,Interstate League Corporation,"04710 SURREY AVE, ROANOKE, VA",US
2689,S2-894693263,Internal Medicine Frontier Physicians Holdings,"SPRINGVILLE, AL, 511 174",US
3055,S2-46777321,Interstate Federal Hotels LLC,"WINSTON-SALEM, 5700- SHATTALON DRIVE, NC",US
3598,S2-31971701,Integrated Intelligence Works Co,"19549. Cambridge Rd, MUNDELEIN, IL",US
3770,S2-741940589,Integrated Mortgage Midtown LLC Service,"26 CEDAR LN, BEAVER COVE, ME",US
4109,S2-299640307,integratedkongsberg.com,"1232-1234 VISTA DEL CIMA, CAAMRILLO, CA",US
4244,S2-497025062,Interstate Rrhdt Ltd,"15 ST, BROOKLYN, NY",US
4376,S2-829337272,Interfaith Gui1d Corp,"WAKEFIELD, 23 CATALPA ST, MA",US
4908,S2-308390109,Interstate LLC Babcock Empire,"31D PINE HILL RD, THOMASTON, CT",US
5122,S2-872738270,Integrated Beacon Columbia (LP),"254B SAUNDERS AVE, LINCOLN, NE",US
5319,S2-933085923,Internal Médicine Center Ltd,"13 13TH AVE, BROOKHAVEN, NY",US

================================================================================
BLOCK KEY: India_shri
COUNT: 26765

,entity_id,business_name,business_address,country
126,S2-948280510,Shri Upasana Hospitalities [(Clinic)],"HN 996 A-201/202, DELPHI, HIRANANDANI BUSINESS...",India
173,S2-892923793,Shri Gold Infotech Motors Pdriet Limited,"SHOP NO. #53 PLOT NO 5/6 SECTOR, 03 MANOSH COM...",India
186,S2-688657051,Shri Tranz & Sons Private,"DOOR NO 568 63, DOMLUR, II STAGE 1ST CROSS, 4T...",India
460,S2-60818919,Shri Om Constructions Corp,"H.NO . B-0019, G/F JOHRI FARD, OKHLA, NEWDELHI...",India
560,S2-161476122,Shri Yashvardhan Educational Society,NaN,India
660,S2-330756776,Shri Satyaraj Media Limited Center,NaN,India
979,S2-739448663,Shri @maalogistics,"Karnataka, NO.2307, (OLD NO.44/6), GROUND FLOO...",India
1081,S2-940106616,Shri HITECH IMPEX,"FL N 1102, D, SWARNA CHSL, UNIQUE GARDEN BEVER...",India
1095,S2-656892137,SHRIRAM TECH (INDIA) PVT,"H.NO 507 KAMALALAYA CENTRE156A LENIN SARANI, K...",India
1163,S2-371915761,SHRINATHJI SOLUTIONS (PRIVATE),"NO 0374 179, 1ST FLOOR, KHAN RESIDENCY 12TH A ...",India
1321,S2-814528835,Shri Panache F0undation,"301, MAYURESH COSMOS, 3RD FLOOR, PLOT NO. 37 S...",India
1536,S2-648755299,Shri Stone Oil Private Ltd,"PL 16, H NO. 7236, NEAR R. K. MEMORIAL, OZAR O...",India
1988,S2-554378599,Shri City Estate Llp,"NO 202 , 2ND FLOOR, SLV COMPLEX, ABOVE GRAND, ...",India
2017,S2-777367118,Shri *** Thinking Brothers (India),"NO 7 WARD NO SEVEN PR, ROBERTSGANJ, SONBHADRA,...",India
2114,S2-137876921,Shri kbjindiafinance.com,"H.NO 81/76 , PERUNDURAI ROAD, SARAVANA COMPLEX...",India
2120,S2-681634213,Shri Satakshi Development Private,"2-7-136/7 BUS STAND ROAD, JANGAON, Telangana",India
2183,S2-279477360,Shri Mg Oil,"DOOR NO 400 L MODEL TOWN, REWARI, Haryana",India
2323,S2-519557968,Shri Deep Propmart Psrilvage (Limited),"VILLA NO. 09, NORTHSTAR HILLSIDE, SURVEY NO. 1...",India
2329,S2-148466906,Shri Jai Ltd Pvt Cyber,NaN,India
2444,S2-835063716,Shri SKYLAND SOFTWARE PRIVATE LIMITED,NaN,India

================================================================================
BLOCK KEY: US_prim
COUNT: 15516

,entity_id,business_name,business_address,country
515,S2-662221399,Primary Care Associates Associates Center,NaN,US
768,S2-145204119,Primary Care Cornerstone Physicians Ltd,"308 WASHINGTON AVE, LANCASTER, OH",US
1225,S2-294062437,Primary Care Golden Clinic Llc,"HALL AVENUE, MN, RICHMOND",US
1441,S2-960129567,>> PRIME CONSTRUCTION CONSULTANTS P.C.,"11776 WILLOW VIW CT, VIOLET TWP, OH",US
2143,S2-273999815,Prime Anchor Bittaibse Inc,"##19 MORGAN AVENUE, ONEONT ATOWNSHIP, NY",US
2363,S2-515386320,Prime-Prudential,"1375 145TH AVENUE, GOODYER, AZ",US
2834,S2-218203548,Primary Care Délta Délta Group,"3406 VESTAVIA ST, PRICHARD, AL",US
3024,S2-564433190,PRIMARY-CARE CLINIC PARTNERS,"8756 1/2 CARROUSEL PARK CIR, CINCINNATI, OH",US
3091,S2-483436853,PRIMARYLEBANONCARE.COM #6463,"##725 CEDAR GROVE ROAD, LEBANON, TN",US
3102,S2-684921133,Prime Pmv Ltd Northside,"2638 45TH AVE, MARYVALE, AZ",US
3154,S2-585698283,Primary Care Group Partners Foundation,"15667 100ST WAY, REDMOND, WA",US
3679,S2-150634918,Prime Creative Associates L.L.C.,"38 WHISPERING WIND DR, WISLOW, AZ",US
4025,S2-715418044,Prime Summit Atlinace,"SEAVER ST, DORCESTER, MA",US
4637,S2-87980826,Prime Nippon,"057 HIGHLAND AVENUE, BINGHAMTON, NY",US
4759,S2-754789254,Primary Care Gulf Partners Group,"2623. JAMES ST, BELLINGHAM, WA",US
4995,S2-646593051,Primary Care First Ass0ciates LLC,"224D WINDGATE DR, NC, CLAYTON",US
5648,S2-57257373,Prime Robotics Brands Ltd,"7723 PIT ROAD, REDDING, CA",US
5816,S2-81661580,Prime Logistics Partners,"5472 WILD ROSE LN, WEST DES MOINES, IA",US
6296,S2-221732138,"Prime Technical Products, Ltd.","TX, 2907 POPLAR ISLE, MISSOURI CITY",US
6326,S2-596878321,PRIMARY CARE CLINIC LLC,"102 9RD AVE, CAPITOL, AZ",US

================================================================================
BLOCK KEY: US_metr
COUNT: 15271

,entity_id,business_name,business_address,country
787,S2-414011287,METROPROGRAM.COM,"117 IRWIN ST, INDIANAPOLIS, IN",US
1283,S2-992673515,Metropolitan Council Inc,"6810 16 AVENUE, BROOKLYN, NY",US
1664,S2-895531443,Metropolitan Estate [LP],"17171 RED SHALE HILL RD, PEKIN, IL",US
1696,S2-484427273,metroholdingsgroup.com,"Cason Ln, MURFREESBORO, TN",US
1852,S2-784849034,Metro Frontier Machine,"SUGARLOAF DR, NASHVILLE, TN",US
2214,S2-988430985,Metro Canada LLC,NaN,US
2361,S2-845362212,Metropolitan Mótors L.L.C.,"1145 TOSCANA DR, RIO RANCHO, NM",US
2539,S2-822377517,Metro Súnstone LLC,"4902 17RD ST, DES MOINES, IA",US
3290,S2-345917206,Metropolitan Managers Llc,"ROCHESTER, 3 MANILA ST, NY",US
3421,S2-156443143,Metro Lhengedng Inc.,"1640 ARUNDEL STREET, PO BOX 5386, SAINT PAUL, MN",US
3473,S2-598788762,metropolitan graphics,"IL, 10574 WOODLAND AVE, BEACH PARK",US
3494,S2-358578952,Metropolitan Property LLC Services,"767 STAHLMAN DR, BULLHEAD CITY, AZ",US
3725,S2-137658355,Metropolitan-Wealth [Networks],"CHARLOTTE CITY, 14 PARK FAIRFAX DRIVE, NC, <NULL>",US
4306,S2-693383953,METROPOLITAN LODGING LTD CENTER,"616 AVENUE B-5, COUNTY, WY",US
4452,S2-211389639,Metropolitan Silver Oil LLC,NaN,US
4544,S2-766743346,Metro Vsat LLC,"53 SUMMER SHADE RD, ALLONS, TN",US
5141,S2-803074201,Metropolitan Commodities-Inc,"2941 SPRINGSWEET LN, RALEIGH, NC",US
5781,S2-828388778,METROPOLITAN CAFE LLC,"2243 JOEY LN, ARLINGTON, TX",US
5902,S2-439072420,"Metropolitan-Chain Midtown, Inc.","116 PUMPING JACK ROAD, SHERMAN, TX",US
6537,S2-631104870,Metro Green Graf,"195389 4420 RD, RINGODL, OK",US

================================================================================
BLOCK KEY: India_limi
COUNT: 15079

,entity_id,business_name,business_address,country
153,S2-891756213,Limited Ratnagiri Narang Partners,"H NO 1/B/2 HALIYAL LAYOUT, DHARWAR, DHARWAD, K...",India
155,S2-696635067,Limited Golconda Riddhi Private,"MATHURA, Uttar Pradesh, #58YAMUNA NAGAR AZAMPU...",India
785,S2-147418558,Limited Good Supreme Private Service,"HN 629 O NO.807/N NO 7, VELLORE, Tamil Nadu",India
1023,S2-294753168,Limited AIDL Ir Services,"ROOM NO 208, B WING, AHILYA DUTT BUILDING, PAN...",India
1153,S2-542224090,Limited Ventures Kv Servicesprivate,"#528, MARAMS RP HOMES, INFORMATION COLONY, RAN...",India
2765,S2-906898057,LIMITED ROHA PRIVATE SERVICE,"RC 59/2 RAGHUNATHPUR NORTH P.O. RAGHUNATHPUR, ...",India
3380,S2-532389987,Limited Sky Impex Center,"25, STRAND ROAD MARSHALL HOUSE, 6TH FLOOR, ROO...",India
3785,S2-164761174,LIMITED PZ AUTO,"1-98/5/4/G/5, PLOT NO 65, LEVEL 2, KARAN ARCAD...",India
4093,S2-504054294,Limited Meena Trabldedrs,"FLAT NO 0-5A, B WING, KULSUM COMP, KAUSA MUMBR...",India
4583,S2-674315309,Limited Chennai & Partners,"S/O SHOJI LAL MEENA, BISALPUR COLONY KE PICHE,...",India
4633,S2-913038433,LIMITED INDUSTRIES AAKAR CHIT CENTER,"MUMBAI CITY, Maharashtra, RADHA BHAVAN1ST FLOO...",India
5300,S2-738771320,[[[Limited]]] Neo Brothers,"C-8/52, YAMUNA VIHAR, DELHI, EAST DELHI, Delhi",India
5329,S2-505328569,Limited SA Private Services,"NEW DELHI, 4-B, Delhi",India
6721,S2-693942357,Limitless Jewel,"18 H SARABHA NAGAR, LUDHIANA, Punjab",India
6916,S2-835202415,LIMITED SAMTA POLYTECHNIC INFRATECH CENTER,"HN 254 BUILDING NO. 15, MUMBAI, Maharashtra",India
7002,S2-611602843,Limited HE Internationa1,"3768/1, null, LUDHIANA, Punjab",India
7126,S2-174298792,LIMITED SOLUTIONS PERFECT PRIVATE CENTER,"H 187, SECTOR 63 NOIDA, UTTAR PRADESH, NOIDA, ...",India
7418,S2-296457382,LIMITED SHIV CONSULTING PRIVATE,"71, SHRI GOPAL NAGAR GOPALPURA BYEPASS, JAIPUR...",India
8251,S2-858876941,Limited Panchkula Kchenwtlare Ventures,"SCF-36, PANCHKULA, Haryana",India
8359,S2-219201040,[LIMITED] NEW DELHI CHIT,"PROP. NO.- 577, NEW DELHI, SOUTH DELHI, Delhi",India

================================================================================
BLOCK KEY: India_indi
COUNT: 14030

,entity_id,business_name,business_address,country
356,S2-187514897,INDIA CASTINGS COLOUR PRIVATE LTD,"NO 14TH FLOOR, FLAT NO. 1403, A WING DEVCHAYA,...",India
575,S2-781210535,(india) Nanjil Small Pvt,"10, SIKKA COMPLEX, COMMUNITY CENTER, PREET VIH...",India
870,S2-743482966,(india) Hps Hr Co.,"HOUSE NO. 307/1/48, 2ND FLOOR, SHAHZADA BAGH, ...",India
1466,S2-416568090,indigomarketing.com,"Delhi, 2 , 1ST FLOOR, DLF INDUSTRIAL, AREA, NA...",India
2703,S2-678818787,India Classic Services LLP,"HOUSE NO. 589, SECTOR-9 HUDA, AMBALA CITY, Har...",India
3335,S2-489103612,(INDIA) BHAGYASHREE NATURE PRIVATE LIMITED,"Uttar Pradesh, S-05, SECOND FLOOR, OXY HOMEZ, ...",India
3710,S2-981453578,INDIA SUDARSHAN METALS PVT,"SSB 0084, SECTOR 13P, HSAR, हरियाणा",India
4017,S2-335124172,(india) Sarswati India Private Limited,"NO 204 , 2ND FLOOR, GLN GOWDA COMPLEX, BANGLOR...",India
4618,S2-878639783,India India Ss Inpsectin Company,"FLAT - G1702, APARNA SAROVAR ZENITH, NALLAGAND...",India
4651,S2-89956614,Indivar Communications L.L.P.,"#49, PARDA BAGH DARYA GANN, NEW DELHI, Delhi",India
4881,S2-386575117,indiabehalagases.com,"FLAT NO. F503, TOWER F, PALM DRIVE SECTOR 66, ...",India
5987,S2-235155410,(india) Alkapuri Step Group,"HN 00404 HOUSE NO. 308(A), NEAR PARJAPAT CHOPA...",India
6464,S2-542402013,India Options Bright Private [(Limited)],SHRI MURKUTE PREM BANSILAL FL.NO C/18 NANDLAL ...,India
6475,S2-496024117,(india) Roman Fusions Private,"H.NO 162 , BBMP KHATHA NO925/162, 9TH MAIN, 14...",India
6737,S2-618275000,INDIA VBM RES0RT-PRIVATE LIMITED,"#1207/343 & 1207/1/343/1, 9TH MAIN, 7TH SECTOR...",India
7166,S2-62697433,India Varalaxmi Solutions Private Límited,"PLOT 876. PARGATI NAGAR LATUR, LATUR, Maharashtra",India
7476,S2-856318585,Indian Logistics Private Limited,"D/732, SOMANI CHOKDI, GIDC ANKLESHWAR, ANKLESH...",India
7721,S2-337546861,India Bishnu Integrated LLP,254 RNO 2 FLAT 701 6ND FLR RADHIKA APARTMENT P...,India
7725,S2-40008757,INDIA WILLINGDON PRIVATE LIMITED SERVICE,"H.NO - 7-4-1-464, OPPOSITE TO PETROL BUNK LANE...",India
7858,S2-867204681,India Manikaran Creations LLP,"PLOT 898 346, IIND FLOOR, TRIPLICANE HIGH ROAD...",India

================================================================================
BLOCK KEY: US_fami
COUNT: 13736

,entity_id,business_name,business_address,country
128,S2-857681318,Family Specialists,"4733 LIBERTY RODA, SALEM, OR",US
366,S2-589492301,family care of fairfax county,"4535 WHITTEMORE PLABE, FAIRFAX COUNTY, VA",US
1014,S2-749642407,Family Ridge Chiropractic,"CEDARBROOK ROAD, N/A, NAPERVILLE CITY, IL",US
1300,S2-598991538,Family Medicine (L.L.C.),"04775 WILLIAMS DR, GEORGETOWN, TX",US
1314,S2-626832027,Family Ministries III,"81 MADERA CT, LOS BAONS, CA",US
1389,S2-284585076,FAMILY BLUE CLINIC,"FESTUS, 35 SPRING VALLEY, MO",US
1870,S2-980246492,Family Specialists of Town Of Matteson,"TOWN OF MATTESON, N10958D PEARL FLATS LN, WI",US
2400,S2-980457024,Family Precision Health Corporation,"122, ROUND ROCK, TX",US
2432,S2-520441214,Family Choice Medicine Partners,"IRVINGTON, 40 ECKAR STREET, NY",US
2499,S2-58825780,FAMILY ÍNSTITUTE LLC,"583 NINTH ST, HOUSTON, TX",US
2777,S2-334284265,Family (Tdfrt),"729 HOFT ROAD, WEBSTER, NY",US
2986,S2-98331541,Family Empire Partner LLC,"37 CLARK STREET, EVERETT, MA",US
3108,S2-698383825,Family Center,"194 4TH STREET, TROY, NY",US
3822,S2-438397589,Family-Interstate,"TX, 4800 Bayer Hollow Drive, KILLEEN CIITY",US
4345,S2-570512018,Family Clinic Inc Inc,"3879-3883 HOG BEND, GRAORD, TX",US
4525,S2-862571135,Family Health Inc Trust,"212, CLACKAMAS, OR",US
4672,S2-505244705,familycharities.com,"OR, WESTON, COUSE CREEK ROAD",US
4728,S2-784105752,Fami1y Patriot Health,"13320 MISSRON AVENUE, SPOKANE VALLEY, WA",US
5345,S2-555983033,Family Cr Associates Ltd,"1257 UNIVERSITY ST, REDDLANDS TOWNSHIP, CA",US
5366,S2-890476046,"Family Clinic, (Group)","365 HIEH STREET, HUNTINGTON, IN",US

================================================================================
BLOCK KEY: US_card
COUNT: 12399

,entity_id,business_name,business_address,country
202,S2-736654053,Cardiology Clinic Metro Inc.,"256 ROSELAND PLACE, ABERDEEN, NC",US
1258,S2-400132919,CARDIOLOGY CLAOE GROUP,"4950 FULTON DR, FAIRFIELD, CA",US
1354,S2-988228866,Cardiology Bright Care Co,"341 ALLUVIUM DR, LAUREL, MD",US
1369,S2-595414933,CARDIOLOGY CARE ASSOCIATES OF SOMERSET,"4028 Hopewell Twp Rd 40, OH, SOMERSET",US
1993,S2-681384833,cardiologypartners.com,"628 SUN VALLEY DR, ANDERSON, IN",US
2227,S2-97346546,CARDIOLOGY PARTNERS,"550 FLEETWOOD DRIVE, HOT SPRINGS NATIONAL PARK...",US
2976,S2-692356310,Cardiology Care of Des Moines Greater,"##1409 OSCEOLA AVE, DES MOINES, IA",US
3127,S2-49461175,cardiology health inc (ID: 7253),"204 PARKSIDE DRIVE, OH, POWELL",US
3202,S2-846535978,Cardiology Center Pllc,"7837 1700 ROAD NORTH, PONTIAC, IL",US
3447,S2-121549347,Cardiology Associates of Whitman,"66 POND STREET, WHITMAN CITY, MA",US
3722,S2-381785440,Cardiology Ace,"3709- SECOND STREET, GREAT BEND, KS",US
4915,S2-440765604,Cardinal Córp,"10814 TAHOE WAY, SOUTH JORDAN, UT",US
5562,S2-632080323,CARDOSO'S CONSULTING,"8336 DUPONT AVE, BLOOMINGTON, MN",US
5745,S2-237459247,Cardiology Health of Cincinnati Corp,"WOODHURST CT, CINCINNATI, OH",US
5846,S2-878574120,CARDIOLOGY ELITE CGBEE HARBOR,"1319-1323 PRIVADO LN, SEDRO-WOOLLEY, WA",US
5955,S2-322836083,"cardinal, llc","169 CSURT ST, MADISONT OWNSHIP, WV",US
6047,S2-29692158,"Cardiology Inc Partners,","5615 55ST CIR, PO BOX 5301, VANCOUVER TOWNSHIP...",US
6413,S2-97306857,Cardinal,"173- SHELDON HILL ROAD, OLIVEBRIDGE, NY",US
6466,S2-450858686,Cardiology Specialists of Mrgcer Island Inc,"##7019 82TH AVE, MERCER ISSLAND, WA",US
6743,S2-9255512,CARDIOLOGY ÍNNOVATIVE,"##1060 WOODLAND LANE, OPELIKA, AL",US

In [14]:
top_s3_keys = s3["block_key"].value_counts().head(10).index

for key in top_s3_keys:
    print("\n" + "=" * 80)
    print("BLOCK KEY:", key)
    print("COUNT:", (s3["block_key"] == key).sum())

    display(
        s3.loc[
            s3["block_key"] == key,
            ["entity_id", "business_name", "business_address", "country"]
        ].head(20)
    )

================================================================================
BLOCK KEY: India_priv
COUNT: 46761

,entity_id,business_name,business_address,country
68,S3-891901989,Private Shivam Projects [Limited],"B-3 Kailash Colony, New Delhi, South Delhi, DL",India
78,S3-263247365,Private Unique Enterprises Limited,"302, Andheri (West), Mumbai, महाराष्ट्र",India
338,S3-968476116,Private Amika Infotech Límited,B-1/a24- Mohan Co-operativeindustrial Estate M...,India
341,S3-787353706,Private Hitech Infrastructure Ltd,"G-2 Parth 14, Panchnath Plot, Rajkot, ગુજરાત",India
367,S3-126982322,Private Chennai Solutions Limited,"Kanchipuram, TN, No 147, Ground Floor, Nanbarg...",India
388,S3-610402578,PRIVATE PRANAV TECHNOFAB LIMITED,"No.3c, Saravanampatti, Coimbatore, TN",India
461,S3-523695838,Private Sun P0wer Ltd,"Door No 113/1 F-1001, Jewel Of India, Opp. Jai...",India
630,S3-711373924,Private Blue Care Limited,"RJ, 30, Jaipur",India
856,S3-81118620,PRIVATE SELEX CHEMICALS LIMITED,"408, Ahmedabad, GJ",India
860,S3-269732947,Private Lakshmi Global Foods Limited,"Door No 0710 S No 56/5B, Haveli, Pune, MH",India
1026,S3-485472794,PRIVATE INTERNATIONAL CLASSIC INDUSTRIES LIMITED,"5Thflr Amstor Annexe Bldg, Technopark Phase 1,...",India
1061,S3-488501613,Private C1assic Tech Ltd,"Ce-4012, Mumbai, महाराष्ट्र, Mumbai City, Ce-4...",India
1077,S3-927026135,Private Vigor Institute [Limited],"C/o Mauli Oil Mill, Plot No 43, Besides Malpan...",India
1084,S3-740193994,Private Bangalore South Educational Group Limited,"23-7, Bangalore South, Bangalore, KA",India
1245,S3-4185616,Private Aditin Tours Ltd,"Door No 158 Hig 65/55 Pratap Nagar, Sanganer, ...",India
1414,S3-712564318,Private Sundha Blanc Ltd,"Plot No-16, Sector A-9, Pocket-1 Narela, Delhi...",India
1454,S3-343009930,Private Shree Fóundation Limited,"239, 2Nd Floor Exult Shoppers, Near Vesu Ss, S...",India
1548,S3-485162371,Private Hyderabad Pdins Limited,"H.no 19 Baghameeri, Kukatpally, Rangareddy, Hy...",India
1657,S3-353857348,Private Bharat Research Limited (India),"Vasai, Sativali, MH, Thane, Sno46 Hno1 Damupad...",India
1725,S3-409544576,Private Solar Brothers Ltd,"H.no 124, Vka Complex Upstairs, Srinivasapuram...",India

================================================================================
BLOCK KEY: US_pedi
COUNT: 31261

,entity_id,business_name,business_address,country
138,S3-161412777,pediatric dental care associates inc,"492 Fairborn Ln, Round Lake, Illinois",US
210,S3-903416633,Pediatric Express Care Llc,"6795 Landriano Place, Rancho Cucamonga, Califo...",US
646,S3-538882911,Pediatric Dental Physicians Inc.,NaN,US
1415,S3-697956436,Pediatric Mdeicien of Elkhart West LLC,"0414 Cleveland Ave, Elkhart, Indiana",US
1434,S3-406432606,Pediatric Dental Pcans Inc.,"2623 39th Ave, Washington, Seattle",US
1493,S3-741719955,Pediatric Dental Medicine East Ltd,"18231 34st Avenue, Shaw Butte, Arizona",US
1575,S3-328775191,Pediatric Partners Partners Co,"112 Green St, Boston, Massachusetts",US
1675,S3-39511634,Pediatric Health Partners,"7928 Summerfern Ct, Cypress, Texas",US
1935,S3-775613160,Pediatric Dental Frontier Health Southside [LLC],"9116 Pineville-Matthews Road, # A, Pineville, ...",US
2137,S3-270062152,Pediatric Dentistry Associates Of,"261 River St, Warrensburg, New York",US
2278,S3-805197347,Pediatric LLC Center,"12 Veteran Street, Lockhart, Texas",US
2548,S3-781754949,Pediatric Dentistry Care Associates,"12910 Fort Washington Road, Fort Washington, M...",US
2643,S3-453848329,Pediatric Clinic of North Strabane Township Me...,"1093 Woodlawn Dr, North Strabane Township, Pen...",US
2800,S3-308343706,Pediatric Specialists,"5381 Brambleton Ave, Raleigh, North Carolina",US
2878,S3-755016411,Pediatric Déntal Secure LLC,"15-C Prag Blvd, PO Box 7980, Monroe, New York",US
3128,S3-929472406,Pediatric Dentistry Specialists Central Corp,"8117 Long Mesa Dr, Prescott Valley, Arizona",US
3161,S3-958000113,Pediatric Dentistry Group Association,"5255 Bunker Hill Court, Loves Park, Illinois",US
3164,S3-697931116,@pediatricdentistry,"932 Casper Rd, RIO Ranch Ocity, New Mexico",US
3245,S3-656204670,Pediatric Dentistry Select Specialists Inc,"City Of Madison, Wisconsin, 1619 Stoughton Road",US
3594,S3-116292285,Pediatric,"5124 Princess Anne Road, Norfolk City, VA",US

================================================================================
BLOCK KEY: India_shri
COUNT: 30313

,entity_id,business_name,business_address,country
200,S3-954711163,Shri Sunrise Infrastructure Automobiles Private,"23, Bonfields Lane, 2Nd Floor, Kolkata, Howrah...",India
222,S3-465433588,Shri VIJAY SOLUTIONS GARMENTS PRIVATE LIMITED,"Word No.28, 9, Psd-a, Gharsana, राजस्थान",India
465,S3-587791501,Shri Specia1ist (India) India Limited,"Vill- Asma Po- Bhoudgali, Nawada, BR",India
515,S3-151326341,Shri Bb Industries Co,"Fl18 Nikhil Co.hos.soc., Pune City, Pune, MH",India
521,S3-904865577,Shri Srm Software Ventures [Pvt.],"Lotus Land Mark;66, Mutyalampadu Vja, Vijayawa...",India
1042,S3-461819126,Shri Umang Ventures,"Ka-46, Kavi Nagar, Ghaziabad, UP",India
1049,S3-67687930,Shri Success College Corporation,"Office No- 02, Pune, MH, N/A, Pune City",India
1157,S3-664049432,Shri Dynamic Enterprises Pvt,"Sirsa, R/scf-3-11 Anaj Mandi, N/A, HR",India
1496,S3-565866487,Shri Eagle Builders of Shaikpet,"Unit No 203, Hyderabad, Shaikpet, 2Nd Floor, S...",India
1702,S3-632816662,Shri >> Baba Travels Llp,"Office No. 7, 3Rd Floor, Sumriddhi Business, S...",India
1790,S3-584170524,Shrinathji International School Co,"##182, Zone - I, Bhopal, M. P. Nagar, MP",India
2013,S3-905358091,Shri Tech Educational of Akola Pvt Ltd,"15 Amg Cyber Cafe Kelkar, Akola, महाराष्ट्र, A...",India
2207,S3-957950100,Shri Kshitija Consultants Private Limited,"House No. 160/2, Delhi, DL",India
2248,S3-45721923,Shri @mavalindia,"N-2/104, Irc Village Nayapalli, OD, Bhubaneswa...",India
2435,S3-852310629,Shri Blueridge Medical Centre Corp,#A-23 Swastik Palazajuhu Scheme Jvpd Road Next...,India
2601,S3-792824791,Shri Gale Safety Overseas Private [Limited],"No 14 C/o Gyanbarao Tukaram, Ingle, Yehlegaon ...",India
2972,S3-899348640,Shri Sahajanand Education Overseas Private Lim...,"8Th Floor, Kalpataru Habitat Dr S S Rao Road, ...",India
3100,S3-870725109,Shri Himalaya Marketing LLP,"26 L.s.c. Market Second Floor, Shivaji Enclave...",India
3132,S3-989531349,Shri Systematic Clinic Electronics,"6-2-686/B/6/A/306, Hyderabad, Andhra Pradesh",India
3450,S3-389191171,Shri Bhakti Investments (sInh) Private (Limited),"Plot 646 H Num 6 147/2, Khammam, Kothagudem, TG",India

================================================================================
BLOCK KEY: US_inte
COUNT: 28251

,entity_id,business_name,business_address,country
23,S3-326049086,Integrated Business Systems,"#111 Frontage Road 2121, Ilfeld, New Mexico",US
422,S3-145119058,Interstate Aftomcotiev (Holdings),"711 Lataste Dr, Oxford, Alabama",US
659,S3-585464626,Integrated Semiconductor-Union Inc.,"Scottsburg, 7740 Delaney Park Road, Indiana",US
747,S3-439688939,Internal Group Services Enterprises,NaN,US
1211,S3-436133819,Interfaith Ptlsfojnt,"4733 36th St, Tacoma, Washington",US
1343,S3-268816588,internal medicine vanguard clinic,"#59 Mary Street, Quincy, Massachusetts",US
1579,S3-761561267,Interstate Pediatrics Partners,"1930 College Ave, City Of Appleton, Wisconsin",US
1635,S3-662186191,Integrated Genhc Associates P.C.,"95 Hager Ln, Boxborough, Massachusetts",US
2183,S3-382027490,Interstate Wr0awide,"2423 15th Place, Washington, District of Columbia",US
2188,S3-753489692,Integrated Consumer Worldwide Summit LLC,"<NULL>, Silver Spring, Maryland, 15039 Westhol...",US
2468,S3-957396127,Interstate Ministries Partners,"4308 X, Mosinee, Wisconsin",US
3231,S3-222783425,Internal Medicine,"2005 Farmview Drive, # UNIT 4, Florence, Kentucky",US
3269,S3-243926790,Integrated Payroll,"2906 Speedway Ave, Wichita Falls, Texas",US
3280,S3-431565370,Integrated Hospitality Union (LP),"50 Ledgeview Way, # 2410, Wrentham, Massachusetts",US
3466,S3-500236934,Interfaith N1etwrk P.C.,"302-B Mountain Creek Ln, Mansfield CITY, Texas",US
3488,S3-995288766,Internal Medicine,"5809 9 Mile Ridge Rd, Hardy, Arkansas",US
3500,S3-580594311,Interna1 Medicine Physicians of Írving LLC - 7...,"8249 Ranchview Dr, Unit 1088, Irving, Texas",US
3514,S3-702393009,Interstate Insibbute,"Jelly Park Stone Dr, Cypress, Texas",US
3606,S3-788554325,Interstate Summit Institute,"417 Shep Street, Austin, Texas",US
3695,S3-798234760,Internal Medicine Associates of Wendell,"754-758 Ambrose Hill Ln, Wendell, North Carolina",US

================================================================================
BLOCK KEY: India_limi
COUNT: 19190

,entity_id,business_name,business_address,country
436,S3-960875960,limited aditya it,"1081/1, Calicut, Kozhikode, കേരളം",India
470,S3-444730740,Limited Harmony Sons Private Center,"Shop 4, Mumbai, Mumbai City, महाराष्ट्र",India
1380,S3-841046679,Limited Laxmi Industries Medicals,"No C-32 Villa-c, Sultanpur, New Delhi, DL",India
1889,S3-627028990,Limited Jain Private [Services],"No 75 Past, Secunderabad, Hyderabad, తెలంగాణ",India
2499,S3-834848830,Limited Silver Protpetise,"#29/199-B1 Gcc Building, NULL, Ernakulam, High...",India
2772,S3-276376723,Limited CHQ Consultants Private,"80-A Ground Floor, New Delhi, West Delhi, दिल्ली",India
2830,S3-933265713,Limited Seven Private Services,"Country Club Kool, Hyderabad, TG",India
3316,S3-644136141,Limited Radhapuram Travels Infratech Services,"No.119 B, Radhapuram Road, Valliyur, Vadakkuva...",India
3523,S3-595577021,Limited Laxmi Marketing Service,"#884/7 Meenal Arcade Nal, Stop Eradwane, Pune ...",India
3969,S3-135441609,Limited Mumbai Engineers Services,"No.d900c9, 711 21Rd, Chitrakar Dhurandhar Marg...",India
4143,S3-122398992,Limited Balaji Índustries Automobiles,"Door No 161, 1St Stage, 3Rd Phase, Woc Road, S...",India
4368,S3-284290045,Limited Madan Foundation Center,"Suite 217, Mumbai, MH",India
4685,S3-529889082,Limited Vijay Private Center,"Hyderabad, TG, Navya Arcade, Opp-anutex Malkaj...",India
5179,S3-126629336,limited united healthcare,"GJ, House No. #9 A, Diwalipura, Shreeji Housin...",India
5319,S3-583532509,Limited Apex Foundation Partners,"997. 10/47, Lucknow, Sahara Estate Bahar, Jank...",India
5391,S3-145167978,Limited Royal Private Center,"027/16, Gali No 10, 60 Phota Road Vishwas Naga...",India
5500,S3-311779914,Limited Shivam Ace Búilders,"Flat No-0026, New Delhi, DL",India
5659,S3-834933559,Limited Chambal Computers Private,"Sklad One Building A-129a, Feroke, Kozhikode, KL",India
5796,S3-312341122,Limited Dheeraj Inlda,"Thane, Sh1 Bldg G 1 Wing A Jesal, Thane, महारा...",India
6585,S3-28063048,Limited Vs Infratech Private,"#1, Allur Village, Nandikotkur Mandal, Nandyal...",India

================================================================================
BLOCK KEY: US_prim
COUNT: 15866

,entity_id,business_name,business_address,country
456,S3-738431506,Primary Care Classic,"57908 Somerton Highway, Barnesville, Ohio",US
1076,S3-982441302,Primary Care Cgminttal Group,"2029 1/2 Woodlawn Boulevard, Wichita, Kansas",US
1650,S3-954979111,Primary Crae Group,"Goldsboro, PMB 232, 20 Ash St, North Carolina",US
1708,S3-196626644,Prime Forefront Ltd,"51 Foothill Ln, Huntington, New York",US
1927,S3-743366290,Prime Engineering LLC Services,"282 Jackson Blvd, Chicao, Illinois",US
2653,S3-768137581,Primary Care National Center Group,"212 Clay Street, Unit Apartment 2, Anoka, Minn...",US
2787,S3-739323357,Prime Transition,"3643 Icard Rhodhiss Rd, Connelly Springs, Nort...",US
2858,S3-395749895,Primary Care Mountain,"Graham, Washington, 9309 210th Street Court",US
3684,S3-215179046,Primary Care Asoicates LLC,"821 Fairway St, PO Box 8284, Bethalto, Illinois",US
3745,S3-614161266,Primary Care Horizon,"#6848 Trovita Way, Citrus Heights, California",US
3786,S3-702403754,Primary Care Care Premier Physicians L.L.C.,"7303 17th Avenue, Hyattsville, Maryland",US
3796,S3-726357182,Prime Diagnostic East LLC Partners,"5911 Greene Street, Charlotte, North Carolina",US
4274,S3-531535716,Prime Kongsberg,"2117 Huffine Mill Road, Mcleansville, North Ca...",US
4443,S3-582628933,Primary Care Preferred Center Inc,"127-C Altamont Ave, Glen Cove, New York",US
4804,S3-443516445,Prime Automation Studios LLC,"709 Copley Street, Elmira, New York",US
4826,S3-3788020,PRIMARY CARE SPECIALISTS,"Oregon, 5040 1/2 Ainsworth St, Portland",US
4847,S3-128939732,Primary Care LLC Service,"11775 Patience Way, Prescott Valley, Arizona",US
4862,S3-382215493,Prime Bay Twó Corp,"3629 Wood Ave, Kansas City, Kansas",US
4917,S3-937680294,Prime Materials,"1008-1010 Bunker Dr, Unit 301, Akron, Ohio",US
5385,S3-389939797,"Prime-Lifceo, LLC","30 Milliken Street, Old Orchard Beach, Maine",US

================================================================================
BLOCK KEY: India_indi
COUNT: 15821

,entity_id,business_name,business_address,country
11,S3-53737228,Indian Care Public Limited,"Raebareli, Rae Bareli, Raibareilly, UP, No #51...",India
379,S3-753125827,India Amkay Hotels Group Holdings,"Sakar Iv Opp Town Hall, Nr Sanyas Ashram Ellis...",India
757,S3-560301253,India Shankheshwar Developers Pvt.,"Flat-106, Andheri (East), Mumbai, MH",India
802,S3-983937391,India Amkay Hotels Group Pvt Ltd.,"Godown 1 Basement Ka-395, Ghaziabad, Greater N...",India
1756,S3-931705895,Indian Índustries Electronics LLP,"A-18 6St Floor New Multan Nagar, New Delhi, No...",India
1778,S3-212534587,India WKM India (Private),"Block A-351 3-100/135/403, Tirumalagiri, Hyder...",India
2513,S3-213712532,India Funds,"Hn 464 6/432, Sree Vamsaviruthi, Nagar, Pulian...",India
2848,S3-550217951,India Solutions Clinic LLP,"390 5Th Cross 2Nd Main, Vrushabavathi Nagar Ka...",India
3614,S3-932336301,India Ananth Private Limited Center,"Udrej Bhawan, Asansol, Paschim Bardhaman, WB",India
3768,S3-656689436,India Cinnamon Infrastructure Limited,"7-100/44/Srkr/301, Nizampet, Hyderabad, Tiruma...",India
4006,S3-850241907,India Bharaj Heights Pvt Ltd,"No.83., 2Nd Cross, 5Th Main Road, Keb Layout, ...",India
4011,S3-87907581,Indian Foods,"Flat No.-t 102, 3Rd Floor, House No. 2A/416, A...",India
4235,S3-800155502,Indian Systems Private,"MP, Sidhi, Ward No.003, null, Sidhi",India
4477,S3-744260812,Indian Red International Private,"H.no 669 W1/b1.177 Mariamman Kovil Street, The...",India
4846,S3-520867148,indiapeninsulaagri.com,"No.6/489 Triveni Pilathara, Kannur, കേരളം",India
5429,S3-255471794,(India) Dynamics Triveni,"Delhi, DL, #210-211., North West, First Floor,...",India
5655,S3-83727805,Indian Law Chambers,"C-5 Transport Nagar, Mainpuri, UP",India
5834,S3-53506436,India Super Pictures,"No 15 Lml Colony Ammankulam, P N Palayam, Coim...",India
5886,S3-954922372,India,"1283, Bara Bazar Opp. Church, Kashmere Gate, N...",India
6066,S3-497678036,India Laxmi Ltd Pvt Chaudhari,"Plot No. 445, Sector - 1/A, Ground Floor, Oslo...",India

================================================================================
BLOCK KEY: US_metr
COUNT: 15206

,entity_id,business_name,business_address,country
218,S3-6605683,Metropolitan Holdings Inc,"00524 Marlowe Road, Raleigh, North Carolina",US
394,S3-421946310,Metropolitan Genesis,"20600 Kearney Path, Lakeville, Minnesota",US
560,S3-213092687,Metro Sunstone,"1361 1/2 Firethorne Drive, Mason Ciity, Ohio",US
854,S3-144720166,Metropolitanclassicatlanticus.Com,"620 Washington St, Winchester, Massachusetts",US
1340,S3-76997783,"Metropolitan Hgrózson Steel, LLC","229 Winding Way, <NULL>, Shelbyville, Kentucky",US
1421,S3-303012024,Metropolitan Institute,"03300 Woodlark Dr, Fort Worth, Texas",US
2323,S3-834951367,Metropolitan Horizon Co,"1824 Equine Retre Way, Crandall ICTY, Texas",US
2417,S3-164116745,"Metro Fe1lowship, Group","12232 Schreoder Rd, Dallas, Texas",US
3382,S3-931218676,Metropolitan Federation,"325-327 136th Street, Ocean City, Maryland",US
3521,S3-69542509,"Metro Fróntier United, Inc","1319 Arapahoe Avenue, Salt Lake City, Utah",US
3782,S3-770141930,Metro Elite Group,"Virginia Beach CITY, Virginia, ##137 -108 Runa...",US
4376,S3-753663048,Metro A1liance,NaN,US
4398,S3-615367524,Metropolitan Pacific Services,"#408 Utah Avenue, Pittsurg, Kansas",US
5132,S3-260724733,metrostrategichouse.com,"106 Johnson Dr, Spicewood, Texas",US
5182,S3-621528582,"Metro Blue Boston, Inc","244 Walnut Ridge Rd, Salem, Indiana",US
5375,S3-872701289,Metropolitan Royal Precious (LLC),"##20 Millers Ln, Warwick, New York",US
5691,S3-930620189,Metropolitan Préparatory Ácademy,"22 House Rock Road, Weymouth, Massachusetts",US
6099,S3-386771828,Metropolitan Allegro L.L.C.,"1 Broadway, Long Beach, New York",US
6187,S3-911530348,Metro Initiative Corporation,"2500 Boddie Ln, # Unit 6101, Gulf Shores, Alabama",US
6758,S3-774464697,Metropolitan Optimal,"42823 Pamplin Terrace, Chantily, Virginia",US

================================================================================
BLOCK KEY: India_shiv
COUNT: 14151

,entity_id,business_name,business_address,country
244,S3-619115665,Shivkripa-Development Private Limited,"&12-7-4/1&2, Hyderabad, TG",India
308,S3-439655728,Shiv Leasing Industries Private,"Birbhum, No 28 C/o, পশ্চিমবঙ্গ",India
592,S3-747355483,shiv business private limited,"Near City Thana Kath Mandi, Divreportingcircle...",India
639,S3-551778816,Shiv Services प्राइवेट लिमिटेड,"Block No. 21, Room No 123, 3Rd Floor, Near Nan...",India
693,S3-895371174,shiva industries private limited,"Sp-g-43, Maurya Enclave Pitampura, New Delhi, DL",India
1908,S3-526379348,SHIVSHAKTI AGENCY PRIVATE LIMITED,"No 120, <NULL>, New Delhi, दिल्ली",India
1973,S3-300764673,Shiv Energy [Limited],"C-20, Ahmedabad, GJ",India
2079,S3-987704104,Shiva Investment Investment L.L.P.,"247, Industrial Area Nangla, Faridabad, HR",India
3226,S3-612463547,Shivam Constructions Pvt Limited,"H.no 68 Ac 45, Palit Villa Prafullkanan, Kesto...",India
4003,S3-93402322,Shiv Consulting,"H.no.3-6-767, Flat.no.302, Anitha Towers Stree...",India
4017,S3-949391033,Shiv Internatonal Limited,"Plot No- B3/426/3245, N 426/3423 At- Lingipur,...",India
4485,S3-828182798,Shivam It Public Limited,"22, Mann Sandwal, Gurdaspur, Gurdaspur, PB",India
5287,S3-222464878,Shivam புராப்பர்ட்டீஸ் LLP,"Y 96, 8Th Street Anna Nagar, Chennai, TN",India
5861,S3-309841773,SHIV UNIVERSAL INFRASTRUCTURE PRIVATE LIMITED,"First Floor, Azeez Centre No.623, Anna Salai, ...",India
6249,S3-494114230,Shiv Developers Foods [Limited],"No ##51 C/o. Ramlal Panwar, B-248, Panchsheel ...",India
6503,S3-677851804,Shiv Software Private,"H No. 1-19-80/57, Hyderabad, తెలంగాణ",India
6834,S3-102683694,Shivan Limited Private Mercantile,"Plot No. 52-B, Sainik Enclave, Sec-3, Gali No....",India
6902,S3-184375154,Shivam Media Pvt Ltd,"818-A, Ahmedabad Hq Region, GJ",India
6930,S3-545214696,Shivam Agro Prltiae Limited,"No 01-17-3/7, Vizag, Vishakhapatnam, AP",India
7017,S3-563043948,SHIVA FINANCE LLP,NaN,India

================================================================================
BLOCK KEY: US_fami
COUNT: 13720

,entity_id,business_name,business_address,country
289,S3-400079254,Familycareassociates.Com,"904 Main St, Blackwell, Oklahoma",US
332,S3-971943018,Family East Foundation,"1893 Main St, Newinton, Connecticut",US
981,S3-673495166,Family-Health,"74 Jeter Road, Plao, Illinois",US
2345,S3-87582110,Family LLC Services,"226, Bakersville, North Carolina",US
2452,S3-976237098,Family Bright Care Associates Associates LLC,NaN,US
3020,S3-863259103,#familymountain,"Walgren Dr, Silvedale, Washington",US
3022,S3-853118311,Family-Specialists,"Maryland, Crofton, 1733 Peartree Ln, Fl 0",US
3319,S3-252752998,Family Associates LP,"3415 Coventry Ln, Lafayette, Indiana",US
3886,S3-553176058,Family Medicine East (LLC),"98 Saint Andrews Pl, Unit Apartment 2E, Yonker...",US
4661,S3-513589353,Family Specialists Co,"414- 4nd Street, Gillette, Wyoming",US
4686,S3-995246766,Family Health P.L.L.C.,"2709 Market Center Dr, Morrisville, North Caro...",US
5046,S3-454169329,Family Clinic,"17300 88nd Avenue, Unit 135, Peoria, Arizona",US
6214,S3-521981880,Family Rapid Church,"2365 Oriole Dr, Sierra Vista, Arizona",US
6797,S3-665272367,Family Delta Specialists PC,"125 Connect St, De Queen, Arkansas",US
6933,S3-668808075,Family-Care Associates North Inc,"159-C Forest Rd, Tolland, Massachusetts",US
7374,S3-96459860,Family Center Ltd,"3283c Cleo St, Orange, Texas",US
7925,S3-923137437,Family Bright Partners,"Salem, Virginia, 95 Point Pleasant Ave",US
7944,S3-245771513,Family Committee Westgate,"Mckiinney, 5919 Broadacre Drive, Texas",US
8813,S3-910577277,Family Partnesrs,"105 Windsong Bay Ln, Tega Cay, South Carolina",US
8890,S3-496061507,Fami1y Partners Inc.,"423 Appalachian Way, Montreat, North Carolina",US

In [15]:
print("Ground truth columns:")
print(gt.columns.tolist())

print("\nGround truth shape:")
print(gt.shape)

print("\nGround truth sample:")
display(gt.head())

Ground truth columns:
['source1_entity_id', 'matched_entity_ids']

Ground truth shape:
(2206821, 2)

Ground truth sample:

  source1_entity_id                                 matched_entity_ids
0         S1-965667  S2-681193310,S2-743505751,S3-775321672,S3-1129...
1       S1-55344266  S2-249013014,S2-197070651,S3-478195123,S3-3843...
2      S1-343815751             S2-790675320,S2-479876582,S3-878454467
3      S1-656753428              S2-153058913,S2-24659151,S3-679606215
4      S1-102811957  S2-478959098,S2-553508714,S2-625774905,S3-7280...

In [16]:
# Create individual S1 -> matched entity pairs
gt_pairs = gt[
    ["source1_entity_id", "matched_entity_ids"]
].copy()

# Convert comma-separated matches into lists
gt_pairs["matched_entity_ids"] = gt_pairs["matched_entity_ids"].fillna("")

gt_pairs["matched_entity_ids"] = gt_pairs["matched_entity_ids"].apply(
    lambda x: [v for v in x.split(",") if v]
)

# One row per true match
gt_pairs = gt_pairs.explode("matched_entity_ids")

# Remove empty matches (singleton/no-match S1 entities)
gt_pairs = gt_pairs[
    gt_pairs["matched_entity_ids"].notna()
    & (gt_pairs["matched_entity_ids"] != "")
].copy()

print("Total ground-truth matched pairs:", len(gt_pairs))
print("\nSample:")
display(gt_pairs.head(10))

Total ground-truth matched pairs: 7638365

Sample:

  source1_entity_id matched_entity_ids
0         S1-965667       S2-681193310
0         S1-965667       S2-743505751
0         S1-965667       S3-775321672
0         S1-965667        S3-11291185
0         S1-965667       S3-860443364
1       S1-55344266       S2-249013014
1       S1-55344266       S2-197070651
1       S1-55344266       S3-478195123
1       S1-55344266       S3-384364074
2      S1-343815751       S2-790675320

In [17]:
s1_blocks = s1[
    ["entity_id", "block_key"]
].rename(
    columns={
        "entity_id": "source1_entity_id",
        "block_key": "s1_block_key"
    }
)

gt_pairs = gt_pairs.merge(
    s1_blocks,
    on="source1_entity_id",
    how="left"
)

print(gt_pairs.head())

  source1_entity_id matched_entity_ids s1_block_key
0         S1-965667       S2-681193310      US_maur
1         S1-965667       S2-743505751      US_maur
2         S1-965667       S3-775321672      US_maur
3         S1-965667        S3-11291185      US_maur
4         S1-965667       S3-860443364      US_maur

In [19]:
# S2 block-key lookup
s2_blocks = s2[
    ["entity_id", "block_key"]
].rename(
    columns={
        "entity_id": "matched_entity_ids",
        "block_key": "matched_block_key"
    }
)

# S3 block-key lookup
s3_blocks = s3[
    ["entity_id", "block_key"]
].rename(
    columns={
        "entity_id": "matched_entity_ids",
        "block_key": "matched_block_key"
    }
)

print("S2 lookup rows:", len(s2_blocks))
print("S3 lookup rows:", len(s3_blocks))

display(s2_blocks.head())
display(s3_blocks.head())

S2 lookup rows: 5034616
S3 lookup rows: 5285603

  matched_entity_ids matched_block_key
0       S2-166376419        India_रममर
1       S2-764573417           US_holl
2       S2-639257739        India_आदतय
3       S2-163963287           US_summ
4        S2-49942811           US_delt

  matched_entity_ids matched_block_key
0       S3-202863386           US_wilf
1       S3-859268022        India_inte
2        S3-22467283           US_llcm
3       S3-671162755           US_moyn
4       S3-960981775        India_pvte

In [20]:
gt_s2 = gt_pairs[
    gt_pairs["matched_entity_ids"].str.startswith("S2-")
].copy()

gt_s3 = gt_pairs[
    gt_pairs["matched_entity_ids"].str.startswith("S3-")
].copy()

print("S2 true pairs:", len(gt_s2))
print("S3 true pairs:", len(gt_s3))
print("Total:", len(gt_s2) + len(gt_s3))

S2 true pairs: 3693619
S3 true pairs: 3944746
Total: 7638365

In [21]:
gt_s2 = gt_s2.merge(
    s2_blocks,
    on="matched_entity_ids",
    how="left"
)

print(gt_s2.shape)
display(gt_s2.head(10))

(3693619, 4)

  source1_entity_id matched_entity_ids s1_block_key matched_block_key
0         S1-965667       S2-681193310      US_maur           US_maur
1         S1-965667       S2-743505751      US_maur           US_maur
2       S1-55344266       S2-249013014   India_raji        India_ரஜஇன
3       S1-55344266       S2-197070651   India_raji        India_raji
4      S1-343815751       S2-790675320      US_dahl           US_dahl
5      S1-343815751       S2-479876582      US_dahl           US_dahl
6      S1-656753428       S2-153058913   India_ssfo        India_एसएस
7      S1-656753428        S2-24659151   India_ssfo        India_एसएस
8      S1-102811957       S2-478959098      US_payn           US_payn
9      S1-102811957       S2-553508714      US_payn           US_payn

In [22]:
gt_s2["captured"] = (
    gt_s2["s1_block_key"]
    == gt_s2["matched_block_key"]
)

print("S2 captured pairs:", gt_s2["captured"].sum())
print("S2 missed pairs:", (~gt_s2["captured"]).sum())

print(
    "S2 blocking recall:",
    f"{gt_s2['captured'].mean():.6%}"
)

S2 captured pairs: 2836235
S2 missed pairs: 857384
S2 blocking recall: 76.787427%

In [23]:
gt_s3 = gt_s3.merge(
    s3_blocks,
    on="matched_entity_ids",
    how="left"
)

gt_s3["captured"] = (
    gt_s3["s1_block_key"]
    == gt_s3["matched_block_key"]
)

print("S3 captured pairs:", gt_s3["captured"].sum())
print("S3 missed pairs:", (~gt_s3["captured"]).sum())

print(
    "S3 blocking recall:",
    f"{gt_s3['captured'].mean():.6%}"
)

S3 captured pairs: 2975792
S3 missed pairs: 968954
S3 blocking recall: 75.436847%

In [24]:
total_pairs = len(gt_s2) + len(gt_s3)

captured_pairs = (
    gt_s2["captured"].sum()
    + gt_s3["captured"].sum()
)

missed_pairs = total_pairs - captured_pairs

overall_recall = captured_pairs / total_pairs

print("=" * 50)
print("V1 BLOCKING RECALL")
print("=" * 50)

print(f"Total true pairs : {total_pairs:,}")
print(f"Captured pairs   : {captured_pairs:,}")
print(f"Missed pairs     : {missed_pairs:,}")
print(f"Recall           : {overall_recall:.6%}")

==================================================
V1 BLOCKING RECALL
==================================================
Total true pairs : 7,638,365
Captured pairs   : 5,812,027
Missed pairs     : 1,826,338
Recall           : 76.089935%

In [25]:
missed_s2 = gt_s2[
    ~gt_s2["captured"]
].copy()

missed_s3 = gt_s3[
    ~gt_s3["captured"]
].copy()

print("Missed S2:", len(missed_s2))
print("Missed S3:", len(missed_s3))

Missed S2: 857384
Missed S3: 968954

In [26]:
display(
    missed_s2[
        [
            "source1_entity_id",
            "matched_entity_ids",
            "s1_block_key",
            "matched_block_key"
        ]
    ].head(30)
)

    source1_entity_id matched_entity_ids s1_block_key matched_block_key
2         S1-55344266       S2-249013014   India_raji        India_ரஜஇன
6        S1-656753428       S2-153058913   India_ssfo        India_एसएस
7        S1-656753428        S2-24659151   India_ssfo        India_एसएस
12       S1-318373630       S2-660036492   India_redv        India_रडवच
14       S1-789009573       S2-383871912   India_hote        India_हटलए
21       S1-546142636       S2-392804085      US_crys           US_llcc
27       S1-503957000       S2-994658326      US_apho           US_apin
29       S1-503957000       S2-353308450      US_apho           US_apin
30       S1-503957000       S2-173295926      US_apho           US_apín
32       S1-561341312       S2-483615364   India_bala        India_బలజఇ
35       S1-727602285       S2-976870196   India_swas        India_सवसत
36       S1-727602285       S2-947230367   India_swas        India_सवसत
38       S1-727602285       S2-138660620   India_swas        India_llps
43       S1-264156494       S2-184087846   India_diks        India_drdi
44       S1-567308588       S2-191200521      US_zand           US_zblu
47       S1-292935703       S2-195749344      US_cozy           US_gcoz
56        S1-72310418       S2-516305116   India_burg        India_srib
69       S1-491795528       S2-977672203   India_anus        India_msan
71        S1-72444401       S2-973800896   India_news        India_नयसल
74        S1-72444401       S2-503949813   India_news        India_नयसल
93       S1-693111833       S2-540189532   India_vira        India_shri
98       S1-561619160       S2-453284266      US_hutc           US_novi
100      S1-553375105        S2-81940621      US_kozl           US_cira
106      S1-152222475       S2-449137844   India_ramm        India_रममल
107      S1-152222475       S2-981487936   India_ramm        India_raml
134      S1-243930232       S2-950290299      US_qsta           US_qstá
135      S1-243930232       S2-337942322      US_qsta           US_qstá
138      S1-652339606       S2-731383297   India_libr        India_sril
139      S1-816256578        S2-58277947   India_suns        India_सनसफ
141      S1-816256578        S2-20898154   India_suns        India_5uns

In [27]:
display(
    missed_s3[
        [
            "source1_entity_id",
            "matched_entity_ids",
            "s1_block_key",
            "matched_block_key"
        ]
    ].head(30)
)

    source1_entity_id matched_entity_ids s1_block_key matched_block_key
0           S1-965667       S3-775321672      US_maur           US_dréx
4         S1-55344266       S3-384364074   India_raji        India_ரஜஇன
6        S1-656753428       S3-679606215   India_ssfo        India_एसएस
19       S1-730934468       S3-352439310      US_orel           US_llco
20         S1-7293388       S3-523120965   India_chor        India_smtc
21       S1-546142636       S3-200008747      US_crys           US_llcc
22       S1-546142636       S3-729771680      US_crys           US_llcc
26       S1-274126313       S3-850112871      US_obsi           US_korb
27       S1-145361722        S3-96572514      US_dick           US_corp
28       S1-503957000       S3-858763214      US_apho           US_inca
30       S1-503957000       S3-555791452      US_apho           US_apap
33       S1-777597828       S3-413669121      US_upto           US_solk
47       S1-567308588       S3-764465670      US_zand             US_zb
50       S1-292935703       S3-533626303      US_cozy           US_belo
51       S1-439810025       S3-975833735      US_tien           US_ddsl
53       S1-314714647       S3-837108914   India_seab        India_mrse
54       S1-314714647       S3-192802051   India_seab        India_xylo
55       S1-616588883       S3-200505774      US_caoa           US_caoá
61       S1-463669205       S3-242940401      US_beac           US_llc8
62       S1-116043204        S3-85523430   India_redc        India_redp
63       S1-818149988       S3-965578558      US_vady           US_vagd
71       S1-473377609       S3-433876173   India_wave        India_belo
72        S1-72444401       S3-505153321   India_news        India_नयसल
73        S1-67172650       S3-251407198   India_apar        India_msap
78       S1-131928575       S3-849706696      US_jean           US_llcj
88       S1-731397769       S3-794611761      US_faso           US_faye
98       S1-553375105       S3-150800481      US_kozl           US_lope
102      S1-152222475       S3-784413899   India_ramm        India_priv
107      S1-161556164        S3-91054277   India_zabu          India_zb
120      S1-790589419       S3-242226202   India_chri        India_msch

In [28]:
# Number of candidates generated by V1
s1_block_counts = s1["block_key"].value_counts()

v1_candidate_pairs = (
    s1_block_counts
    .to_frame("s1_count")
    .join(
        s2["block_key"].value_counts().rename("s2_count"),
        how="left"
    )
    .join(
        s3["block_key"].value_counts().rename("s3_count"),
        how="left"
    )
    .fillna(0)
)

v1_candidate_pairs["candidate_count"] = (
    v1_candidate_pairs["s1_count"]
    * (
        v1_candidate_pairs["s2_count"]
        + v1_candidate_pairs["s3_count"]
    )
)

print(
    "Total V1 candidate pairs:",
    f"{v1_candidate_pairs['candidate_count'].sum():,}"
)

print(
    "Average candidates per S1:",
    f"{v1_candidate_pairs['candidate_count'].sum() / len(s1):,.2f}"
)

print(
    "Reduction ratio:",
    f"{1 - v1_candidate_pairs['candidate_count'].sum() / (len(s1) * (len(s2)+len(s3))):.4%}"
)

Total V1 candidate pairs: 15,216,021,816.0
Average candidates per S1: 6,895.00
Reduction ratio: 99.9332%

In [29]:
missed = pd.concat(
    [
        missed_s2.assign(target_source="S2"),
        missed_s3.assign(target_source="S3")
    ],
    ignore_index=True
)

print("Total missed:", len(missed))

display(
    missed[
        [
            "source1_entity_id",
            "matched_entity_ids",
            "s1_block_key",
            "matched_block_key",
            "target_source"
        ]
    ].head(50)
)

Total missed: 1826338

,source1_entity_id,matched_entity_ids,s1_block_key,matched_block_key,target_source
0,S1-55344266,S2-249013014,India_raji,India_ரஜஇன,S2
1,S1-656753428,S2-153058913,India_ssfo,India_एसएस,S2
2,S1-656753428,S2-24659151,India_ssfo,India_एसएस,S2
3,S1-318373630,S2-660036492,India_redv,India_रडवच,S2
4,S1-789009573,S2-383871912,India_hote,India_हटलए,S2
5,S1-546142636,S2-392804085,US_crys,US_llcc,S2
6,S1-503957000,S2-994658326,US_apho,US_apin,S2
7,S1-503957000,S2-353308450,US_apho,US_apin,S2
8,S1-503957000,S2-173295926,US_apho,US_apín,S2
9,S1-561341312,S2-483615364,India_bala,India_బలజఇ,S2
10,S1-727602285,S2-976870196,India_swas,India_सवसत,S2
11,S1-727602285,S2-947230367,India_swas,India_सवसत,S2
12,S1-727602285,S2-138660620,India_swas,India_llps,S2
13,S1-264156494,S2-184087846,India_diks,India_drdi,S2
14,S1-567308588,S2-191200521,US_zand,US_zblu,S2
15,S1-292935703,S2-195749344,US_cozy,US_gcoz,S2
16,S1-72310418,S2-516305116,India_burg,India_srib,S2
17,S1-491795528,S2-977672203,India_anus,India_msan,S2
18,S1-72444401,S2-973800896,India_news,India_नयसल,S2
19,S1-72444401,S2-503949813,India_news,India_नयसल,S2
20,S1-693111833,S2-540189532,India_vira,India_shri,S2
21,S1-561619160,S2-453284266,US_hutc,US_novi,S2
22,S1-553375105,S2-81940621,US_kozl,US_cira,S2
23,S1-152222475,S2-449137844,India_ramm,India_रममल,S2
24,S1-152222475,S2-981487936,India_ramm,India_raml,S2
25,S1-243930232,S2-950290299,US_qsta,US_qstá,S2
26,S1-243930232,S2-337942322,US_qsta,US_qstá,S2
27,S1-652339606,S2-731383297,India_libr,India_sril,S2
28,S1-816256578,S2-58277947,India_suns,India_सनसफ,S2
29,S1-816256578,S2-20898154,India_suns,India_5uns,S2
30,S1-816256578,S2-598783662,India_suns,India_sunl,S2
31,S1-649259801,S2-654066445,India_guru,India_ಗರಸಲ,S2
32,S1-453879293,S2-301969165,US_clar,US_dani,S2
33,S1-927655670,S2-226884833,India_jain,India_जनमर,S2
34,S1-385608858,S2-635808285,India_jana,India_shri,S2
35,S1-185938539,S2-456005244,India_saii,India_indi,S2
36,S1-654156225,S2-775493531,India_kbmr,India_priv,S2
37,S1-541270202,S2-657479988,US_sofi,US_odso,S2
38,S1-212509374,S2-997766473,US_hine,US_llch,S2
39,S1-862038247,S2-451274541,US_wate,US_aime,S2
40,S1-247801289,S2-752280842,US_blue,US_incb,S2
41,S1-618246590,S2-955993024,India_pret,India_smtp,S2
42,S1-618246590,S2-339477476,India_pret,India_srip,S2
43,S1-618246590,S2-981272489,India_pret,India_corp,S2
44,S1-854952911,S2-180445273,US_john,US_jhsn,S2
45,S1-929320417,S2-275012701,US_sqco,US_thes,S2
46,S1-83647344,S2-777713487,India_newi,India_shri,S2
47,S1-307962633,S2-415653047,US_hist,US_híst,S2
48,S1-425631822,S2-932399936,US_mode,US_serv,S2
49,S1-730297501,S2-913826284,US_guti,US_inc6,S2

In [30]:
s1_info = s1[
    [
        "entity_id",
        "business_name",
        "business_address",
        "country"
    ]
].rename(
    columns={
        "entity_id": "source1_entity_id",
        "business_name": "s1_name",
        "business_address": "s1_address",
        "country": "s1_country"
    }
)

s2_info = s2[
    [
        "entity_id",
        "business_name",
        "business_address",
        "country"
    ]
].rename(
    columns={
        "entity_id": "matched_entity_ids",
        "business_name": "matched_name",
        "business_address": "matched_address",
        "country": "matched_country"
    }
)

s3_info = s3[
    [
        "entity_id",
        "business_name",
        "business_address",
        "country"
    ]
].rename(
    columns={
        "entity_id": "matched_entity_ids",
        "business_name": "matched_name",
        "business_address": "matched_address",
        "country": "matched_country"
    }
)

In [32]:
# Check what columns are currently available
print(missed_s2.columns.tolist())
print(missed_s2.shape)

['source1_entity_id', 'matched_entity_ids', 's1_block_key', 'matched_block_key', 'captured']
(857384, 5)

In [35]:
print(
    missed_s2.groupby(
        ["s1_block_key", "matched_block_key"]
    )
    .size()
    .sort_values(ascending=False)
    .head(30)
)

s1_block_key  matched_block_key
India_east    India_ईसटर           2013
India_pion    India_पयनय           1994
India_inno    India_इनवट           1988
India_sout    India_सदरन           1988
India_digi    India_डजटल           1978
India_clas    India_कलसक           1977
India_dyna    India_डयनम           1972
India_adit    India_आदतय           1972
India_arih    India_अरहत           1970
India_futu    India_फयचर           1960
India_laxm    India_लकषम           1958
India_indi    India_इडयन           1944
India_tiru    India_तरपत           1944
India_smar    India_समरट           1943
India_glob    India_गलबल           1937
India_fort    India_फरचय           1929
India_gala    India_गलकस           1927
India_prem    India_परमय           1927
India_mode    India_मडरन           1920
India_silv    India_सलवर           1919
India_sunr    India_सनरइ           1907
India_whit    India_वहइट           1903
India_guja    India_गजरत           1895
India_unit    India_यनइट           1890
India_apex    India_एपकस           1889
India_urba    India_अरबन           1886
India_laks    India_लकषम           1875
India_univ    India_यनवर           1861
India_swas    India_सवसत           1855
India_prim    India_परइम           1855
dtype: int64

In [36]:
print(
    missed_s2["s1_block_key"].eq(
        missed_s2["matched_block_key"]
    ).value_counts()
)

False    857384
Name: count, dtype: int64

In [37]:
print(missed_s2["captured"].value_counts(dropna=False))

captured
False    857384
Name: count, dtype: int64

In [38]:
print(
    missed_s2["s1_block_key"]
    .value_counts()
    .head(30)
)

s1_block_key
India_shiv    12145
India_gold     8193
India_east     7958
India_sout     7903
India_shre     5725
India_indi     5146
India_tech     4813
India_glob     4371
India_blue     4359
India_gree     4345
India_kris     4290
India_inte     4277
India_star     4248
India_roya     4228
India_sury     4205
India_bala     4144
India_adit     4132
India_shak     4121
India_high     4116
India_anan     4112
India_real     4084
India_tiru     4083
India_indo     4081
India_guru     4073
India_supe     4073
India_bhar     4051
India_smar     4048
India_futu     4042
India_silv     4029
India_prem     4022
Name: count, dtype: int64

In [39]:
print(
    missed_s2["matched_block_key"]
    .value_counts()
    .head(30)
)

matched_block_key
India_priv    28186
India_shri    18943
India_limi    10159
US_cent        4334
US_serv        4283
India_लकषम     3833
US_llcc        3451
India_smts     3211
India_sris     3167
US_llcs        3036
US_llcp        2731
US_inco        2721
US_corp        2687
US_thec        2679
US_thes        2244
US_llcb        2203
US_llcm        2170
India_ईसटर     2013
India_पयनय     1994
India_सदरन     1988
India_इनवट     1988
India_डजटल     1978
India_कलसक     1977
India_डयनम     1972
India_आदतय     1972
India_अरहत     1970
India_फयचर     1960
India_इडयन     1954
India_हईटक     1953
India_तरपत     1944
Name: count, dtype: int64

In [40]:
%whos DataFrame

Variable             Type         Data/Info
-------------------------------------------
df                   DataFrame    Shape: (2206821, 2)
gt                   DataFrame    Shape: (2206821, 2)
gt_pairs             DataFrame    Shape: (7638365, 3)
gt_s2                DataFrame    Shape: (3693619, 5)
gt_s3                DataFrame    Shape: (3944746, 5)
missed               DataFrame    Shape: (1826338, 6)
missed_s2            DataFrame    Shape: (857384, 5)
missed_s3            DataFrame    Shape: (968954, 5)
s1                   DataFrame    Shape: (2206821, 5)
s1_blocks            DataFrame    Shape: (2206821, 2)
s1_info              DataFrame    Shape: (2206821, 4)
s2                   DataFrame    Shape: (5034616, 5)
s2_blocks            DataFrame    Shape: (5034616, 2)
s2_info              DataFrame    Shape: (5034616, 4)
s3                   DataFrame    Shape: (5285603, 5)
s3_blocks            DataFrame    Shape: (5285603, 2)
s3_info              DataFrame    Shape: (5285603, 4)
v1_candidate_pairs   DataFrame    Shape: (129478, 4)

In [41]:
print("S1 columns:")
print(s1.columns.tolist())

print("\nS2 columns:")
print(s2.columns.tolist())

print("\nS1 info columns:")
print(s1_info.columns.tolist())

print("\nS2 info columns:")
print(s2_info.columns.tolist())

S1 columns:
['entity_id', 'business_name', 'business_address', 'country', 'block_key']

S2 columns:
['entity_id', 'business_name', 'business_address', 'country', 'block_key']

S1 info columns:
['source1_entity_id', 's1_name', 's1_address', 's1_country']

S2 info columns:
['matched_entity_ids', 'matched_name', 'matched_address', 'matched_country']

In [43]:
display(
    s1.head(3)
)

display(
    s2.head(3)
)

,entity_id,business_name,business_address,country,block_key
0,S1-925783039,Orelee's Barbershop,"1795 Westchester Drive, High Point, NC",US,US_orel
1,S1-773889195,Prime Money,"17560 Ellis Road, Tahlequah, OK",US,US_prim
2,S1-377745466,B+ Retail Inc,"1712 Montebello Avenue, Phoenix, AZ",US,US_bret

,entity_id,business_name,business_address,country,block_key
0,S2-166376419,राम मार्केटिंग प्राइवेट लिमिटेड,"KH NO. -570/13, NEW DELHI, WEST DELHI, Delhi",India,India_रममर
1,S2-764573417,-- Holloway Peak Inc Seafood,"105 ELM ST, MORGANTON, NC",US,US_holl
2,S2-639257739,आदित्य प्रॉपर्टीज एलएलपी,"G-3/571, GULMOHAR COLONY, BHOPAL, Madhya Pradesh",India,India_आदतय

In [44]:
# Attach actual S1 and S2 records to missed S2 pairs

missed_s2_detail = (
    missed_s2[
        ["source1_entity_id", "matched_entity_ids",
         "s1_block_key", "matched_block_key"]
    ]
    .merge(
        s1[
            ["entity_id", "business_name",
             "business_address", "country"]
        ],
        left_on="source1_entity_id",
        right_on="entity_id",
        how="left"
    )
    .drop(columns=["entity_id"])
    .rename(columns={
        "business_name": "s1_name",
        "business_address": "s1_address",
        "country": "s1_country"
    })
    .merge(
        s2[
            ["entity_id", "business_name",
             "business_address", "country"]
        ],
        left_on="matched_entity_ids",
        right_on="entity_id",
        how="left"
    )
    .drop(columns=["entity_id"])
    .rename(columns={
        "business_name": "s2_name",
        "business_address": "s2_address",
        "country": "s2_country"
    })
)

print(missed_s2_detail.shape)

display(
    missed_s2_detail[
        [
            "source1_entity_id",
            "matched_entity_ids",
            "s1_name",
            "s2_name",
            "s1_address",
            "s2_address",
            "s1_country",
            "s2_country",
            "s1_block_key",
            "matched_block_key"
        ]
    ].head(30)
)

(857384, 10)

,source1_entity_id,matched_entity_ids,s1_name,s2_name,s1_address,s2_address,s1_country,s2_country,s1_block_key,matched_block_key
0,S1-55344266,S2-249013014,Raj Investments LLP,ராஜ் இன்வெஸ்ட்மெண்ட்ஸ் எல்எல்பி,"6(29), C.I.T. Colony, 2Nd Main Road Mylapore, ...","6(29), C.I.T. COLONY, 2ND MAIN ROAD MYLAPORE, ...",India,India,India_raji,India_ரஜஇன
1,S1-656753428,S2-153058913,Ss Food Private Limited,एसएस फूड प्राइवेट लिमिटेड,"Af-684, Nandgram Near Mother India Public Scho...","AF-0684, NANDGRAM NEAR MOTHER INDIA PUBLIC SCH...",India,India,India_ssfo,India_एसएस
2,S1-656753428,S2-24659151,Ss Food Private Limited,एसएस फूड प्राइवेट लिमिटेड,"Af-684, Nandgram Near Mother India Public Scho...","AF-0684, Uttar Pradesh, GHAZIABAD, 9487203",India,India,India_ssfo,India_एसएस
3,S1-318373630,S2-660036492,Red Ventures Private Limited,रेड वेंचर्स प्राइवेट लिमिटेड,"Rajasthan, Jaipur, Banipark, Gokul Apartment, ...","G-1, BANIPARK, JAIPUR, Rajasthan",India,India,India_redv,India_रडवच
4,S1-789009573,S2-383871912,Hotel Enterprises Limited,होटल एंटरप्राइजेज लिमिटेड,"Wz-187C Shop No.13, 14 Kh. No.47 S/F. Vikaspur...","WZ-187C SHOP NO.13, DELHI, WEST DELHI, Delhi",India,India,India_hote,India_हटलए
5,S1-546142636,S2-392804085,Crystal Staffing Solutions LLC,LLC Crystal Sttfrifng Solutions,"8706 Kentucky Derby Drive, Waxhaw, NC","8706 KENTUCKY DERBY DRIVE, WAXHAW, NC",US,US,US_crys,US_llcc
6,S1-503957000,S2-994658326,AP Hospitality Inc,AP INC SERVICE #80430,"20085 Us 23, Circleville, OH","20085 US 23, CIRCLEVILLE, OH",US,US,US_apho,US_apin
7,S1-503957000,S2-353308450,AP Hospitality Inc,AP Inc Hospitality,"20085 Us 23, Circleville, OH","20085 US 23, CIRCLEVILLE, OH",US,US,US_apho,US_apin
8,S1-503957000,S2-173295926,AP Hospitality Inc,AP Ínc Center,"20085 Us 23, Circleville, OH","20085 US 23, CIRCLEVILLE, OH",US,US,US_apho,US_apín
9,S1-561341312,S2-483615364,Balaji Investment Private Limited,బాలాజీ ఇన్వెస్ట్‌మెంట్ ప్రైవేట్ లిమిటెడ్,"Plot No. D-88 & D-90, Hyd, Telangana, Hyderaba...","H.NO 00516 PLOT NO. D-88 & D-90, JEEDIMETLA, H...",India,India,India_bala,India_బలజఇ
10,S1-727602285,S2-976870196,Swastik Om Solutions LLP,स्वस्तिक ॐ सॉल्यूशंस एलएलपी,"201/D, Aditya, Svp Nagar Andheri (W), Mumbai, ...","201/D, BHIWANDI, MUMBAI CITY, Maharashtra",India,India,India_swas,India_सवसत
11,S1-727602285,S2-947230367,Swastik Om Solutions LLP,स्वस्तिक ॐ सॉल्यूशंस एलएलपी,"201/D, Aditya, Svp Nagar Andheri (W), Mumbai, ...","201/D, ADITYA, SVP NAGAR ANDHERI (W), BHIWANDI...",India,India,India_swas,India_सवसत
12,S1-727602285,S2-138660620,Swastik Om Solutions LLP,[LLP] Swastik Om Solutions,"201/D, Aditya, Svp Nagar Andheri (W), Mumbai, ...","201/D, BHIWANDI, BOMBAY, Maharashtra",India,India,India_swas,India_llps
13,S1-264156494,S2-184087846,Diksha Technologies Private Limited,Dr Diksha Private Limited Services,"A-401, Nitesh Central Par, Bagalur Main Road, ...","A-401, NITESH CENTRAL PAR, BAGALUR MAIN ROAD, ...",India,India,India_diks,India_drdi
14,S1-567308588,S2-191200521,Zander Blue Co,zblue.com,"9236 Meadowmont View Drive, Charlotte, NC","9238 MEADOWMONT VIEW DR, CHRALOTTE CITY, NC",US,US,US_zand,US_zblu
15,S1-292935703,S2-195749344,Cozy Grill,gcozy.com,"617 Fourth Street, Watseka, IL","617 FOURTH ST, WATSEKA, IL",US,US,US_cozy,US_gcoz
16,S1-72310418,S2-516305116,Burger Solution Limited,Sri Burger Solution,"Flat No. A702, 1St Main, Mantri Classic, 8Th C...","DOOR NO 25 FLAT NO. A702, 1ST MAIN, MANTRI CLA...",India,India,India_burg,India_srib
17,S1-491795528,S2-977672203,Anushree Sangh,M/s Anushree Sangh,"Row House No B4, 14 /15, Hill View, Surekha Ni...","HN 31 ROW HOUSE NO B4, 14 /15, HILL VIEW, SURE...",India,India,India_anus,India_msan
18,S1-72444401,S2-973800896,New Solutions,न्यू सॉल्यूशंस,"113/154, 1St Floor, Swaroop Nagar, Swarup Naga...","113/154, SWARUP NAGAR, KANPUR NAGAR, Uttar Pra...",India,India,India_news,India_नयसल
19,S1-72444401,S2-503949813,New Solutions,न्यू सॉल्यूशंस,"113/154, 1St Floor, Swaroop Nagar, Swarup Naga...","113/154, SWARUP NAGAR, KANPUR NAGAR, Uttar Pra...",India,India,India_news,India_नयसल
20,S1-693111833,S2-540189532,Viraaj Brokerage (India) Corporation,Shri VIRAAJBROKERAGEINDIA.COM,"16 Tara Chand Dutta Street, 3Rd Floor, Kolkata...","16 TARA CHAND DUTTA STREET, 3RD FLOOR, KOLKATA...",India,India,India_vira,India_shri
21,S1-561619160,S2-453284266,Hutcherson Investments,Novinoviaria,"4170 Greer Road, Verona, IL","4170 GREER RD, VERONA, IL",US,US,US_hutc,US_novi
22,S1-553375105,S2-81940621,"Kozlowski, Lopez & Smith LLC",Ciralumyuma,"5842 Baileys Ridge Drive, New Kent County, VA","5842 BAILEYS RIDGE DR, PROVIDENCE FORGE, VA",US,US,US_kozl,US_cira
23,S1-152222475,S2-449137844,Ram Maa Logistics Private Limited,राम मां लॉजिस्टिक्स प्राइवेट लिमिटेड,"G-1, Floor-Grd, One Avighna Park, Mahadeo Pala...","G-1, CHURU, MUMBAI, Maharashtra",India,India,India_ramm,India_रममल
24,S1-152222475,S2-981487936,Ram Maa Logistics Private Limited,Ram Limited Logistics Private Maa,"G-1, Floor-Grd, One Avighna Park, Mahadeo Pala...","G-1-, FLOOR-GRD, ONE AVIGHNA PARK, MAHADEO PAL...",India,India,India_ramm,India_raml
25,S1-243930232,S2-950290299,Q+ State LLC,Q+ STÁTE LLC,"1641 Iliff Avenue, Cincinnati, OH","OH, 1641 ILIFF AVE, CINCINNATI",US,US,US_qsta,US_qstá
26,S1-243930232,S2-337942322,Q+ State LLC,Q+ Státe LLC,"1641 Iliff Avenue, Cincinnati, OH","1641 ILIFF AVE, CINCINNATI, OH",US,US,US_qsta,US_qstá
27,S1-652339606,S2-731383297,Libra Service Limited,Sri LIBRA SERVICE LIMITED,"2 Rwm, Ravwala Soubhagya, Ravwala, Bajju, Kola...",NaN,India,India,India_libr,India_sril
28,S1-816256578,S2-58277947,Sun Software Limited,सन सॉफ्टवेयर लिमिटेड,"5 Krishna Shopping Centre, Opp Dahisar Stn, P ...","#5 KRISHNA SHOPPING CENTRE, OPP DAHISAR STN, P...",India,India,India_suns,India_सनसफ
29,S1-816256578,S2-20898154,Sun Software Limited,5un Sun Software Limited,"5 Krishna Shopping Centre, Opp Dahisar Stn, P ...","5 KRISHNA SHOPPING CENTRE, OPP DAHISAR STN, P ...",India,India,India_suns,India_5uns

In [45]:
import re
import pandas as pd

def extract_postal(address):
    if pd.isna(address):
        return None
    
    address = str(address)

    # Indian PIN: exactly 6 digits
    m = re.search(r'(?<!\d)(\d{6})(?!\d)', address)
    if m:
        return m.group(1)

    # US ZIP: 5 digits or ZIP+4
    m = re.search(r'(?<!\d)(\d{5})(?:-\d{4})?(?!\d)', address)
    if m:
        return m.group(1)

    return None

In [46]:
s1["postal_key"] = s1["business_address"].apply(extract_postal)
s2["postal_key"] = s2["business_address"].apply(extract_postal)

print("S1 postal coverage:",
      s1["postal_key"].notna().mean())

print("S2 postal coverage:",
      s2["postal_key"].notna().mean())

S1 postal coverage: 0.06768559842415856
S2 postal coverage: 0.0755743834286468

In [47]:
s1_postal = s1[
    ["entity_id", "postal_key"]
].rename(
    columns={"entity_id": "source1_entity_id"}
)

s2_postal = s2[
    ["entity_id", "postal_key"]
].rename(
    columns={"entity_id": "matched_entity_ids"}
)

In [48]:
gt_postal = (
    gt_pairs
    .merge(
        s1_postal,
        on="source1_entity_id",
        how="left"
    )
    .merge(
        s2_postal,
        on="matched_entity_ids",
        how="left",
        suffixes=("_s1", "_s2")
    )
)

postal_captured = (
    gt_postal["postal_key_s1"].notna()
    &
    gt_postal["postal_key_s2"].notna()
    &
    (gt_postal["postal_key_s1"] == gt_postal["postal_key_s2"])
)

print("True pairs:", len(gt_postal))
print("Postal captured:", postal_captured.sum())
print("Postal recall:",
      postal_captured.mean() * 100)

True pairs: 7638365
Postal captured: 182275
Postal recall: 2.386309111963097

In [49]:
s1["postal_block"] = (
    s1["country"].astype(str)
    + "_"
    + s1["postal_key"].fillna("")
)

s2["postal_block"] = (
    s2["country"].astype(str)
    + "_"
    + s2["postal_key"].fillna("")
)

In [51]:
print(
    s1[s1["postal_key"].notna()]
    .groupby("postal_block")
    .size()
    .describe()
)

print(
    s2[s2["postal_key"].notna()]
    .groupby("postal_block")
    .size()
    .describe()
)

count    34472.000000
mean         4.333082
std          6.345921
min          1.000000
25%          1.000000
50%          2.000000
75%          5.000000
max         87.000000
dtype: float64
count    59981.000000
mean         6.343475
std          9.913418
min          1.000000
25%          1.000000
50%          3.000000
75%          7.000000
max        207.000000
dtype: float64

In [52]:
missed_postal = (
    missed_s2
    .merge(
        s1[
            ["entity_id", "postal_block"]
        ],
        left_on="source1_entity_id",
        right_on="entity_id",
        how="left"
    )
    .drop(columns=["entity_id"])
    .merge(
        s2[
            ["entity_id", "postal_block"]
        ],
        left_on="matched_entity_ids",
        right_on="entity_id",
        how="left",
        suffixes=("_s1", "_s2")
    )
    .drop(columns=["entity_id"])
)

postal_recovers_missed = (
    missed_postal["postal_block_s1"].notna()
    &
    missed_postal["postal_block_s2"].notna()
    &
    (
        missed_postal["postal_block_s1"]
        ==
        missed_postal["postal_block_s2"]
    )
)

print("Missed S2:", len(missed_s2))
print(
    "Recovered by postal:",
    postal_recovers_missed.sum()
)
print(
    "Recovery:",
    postal_recovers_missed.mean() * 100,
    "%"
)

Missed S2: 857384
Recovered by postal: 837176
Recovery: 97.64306308491878 %

In [54]:
print("Original S2 missed:", len(missed_s2))
print("Recovered by postal:", 837176)
print("Remaining S2 missed:", len(missed_s2) - 837176)

Original S2 missed: 857384
Recovered by postal: 837176
Remaining S2 missed: 20208

In [55]:
missed_s2_remaining = missed_s2[missed_s2["captured"] == False].copy()

print("Remaining S2 missed:", len(missed_s2_remaining))

Remaining S2 missed: 857384

In [61]:
import pandas as pd

for name, obj in globals().items():
    if isinstance(obj, pd.DataFrame):
        cols = set(obj.columns)

        if {
            "source1_entity_id",
            "matched_entity_ids"
        }.issubset(cols):

            if len(obj) == 837176:
                print(
                    "FOUND:",
                    name,
                    "| shape:",
                    obj.shape,
                    "| columns:",
                    list(obj.columns)
                )

In [63]:
import pandas as pd

print("DataFrames containing S2-related information:\n")

for name, obj in globals().items():
    if isinstance(obj, pd.DataFrame):

        cols = list(obj.columns)

        relevant = any(
            c in cols
            for c in [
                "source1_entity_id",
                "matched_entity_ids",
                "s1_entity_id",
                "s2_entity_id",
                "s1_postal",
                "s2_postal",
                "postal",
                "captured"
            ]
        )

        if relevant:
            print(
                f"{name:30} "
                f"shape={obj.shape} "
                f"columns={cols}"
            )

DataFrames containing S2-related information:

gt                             shape=(2206821, 2) columns=['source1_entity_id', 'matched_entity_ids']
df                             shape=(2206821, 2) columns=['source1_entity_id', 'matched_entity_ids']
gt_pairs                       shape=(7638365, 3) columns=['source1_entity_id', 'matched_entity_ids', 's1_block_key']
s1_blocks                      shape=(2206821, 2) columns=['source1_entity_id', 's1_block_key']
s2_blocks                      shape=(5034616, 2) columns=['matched_entity_ids', 'matched_block_key']
s3_blocks                      shape=(5285603, 2) columns=['matched_entity_ids', 'matched_block_key']
gt_s2                          shape=(3693619, 5) columns=['source1_entity_id', 'matched_entity_ids', 's1_block_key', 'matched_block_key', 'captured']
gt_s3                          shape=(3944746, 5) columns=['source1_entity_id', 'matched_entity_ids', 's1_block_key', 'matched_block_key', 'captured']
missed_s2                      shape=(857384, 5) columns=['source1_entity_id', 'matched_entity_ids', 's1_block_key', 'matched_block_key', 'captured']
missed_s3                      shape=(968954, 5) columns=['source1_entity_id', 'matched_entity_ids', 's1_block_key', 'matched_block_key', 'captured']
missed                         shape=(1826338, 6) columns=['source1_entity_id', 'matched_entity_ids', 's1_block_key', 'matched_block_key', 'captured', 'target_source']
s1_info                        shape=(2206821, 4) columns=['source1_entity_id', 's1_name', 's1_address', 's1_country']
s2_info                        shape=(5034616, 4) columns=['matched_entity_ids', 'matched_name', 'matched_address', 'matched_country']
s3_info                        shape=(5285603, 4) columns=['matched_entity_ids', 'matched_name', 'matched_address', 'matched_country']
missed_s2_detail               shape=(857384, 10) columns=['source1_entity_id', 'matched_entity_ids', 's1_block_key', 'matched_block_key', 's1_name', 's1_address', 's1_country', 's2_name', 's2_address', 's2_country']
s1_postal                      shape=(2206821, 2) columns=['source1_entity_id', 'postal_key']
s2_postal                      shape=(5034616, 2) columns=['matched_entity_ids', 'postal_key']
gt_postal                      shape=(7638365, 5) columns=['source1_entity_id', 'matched_entity_ids', 's1_block_key', 'postal_key_s1', 'postal_key_s2']
missed_postal                  shape=(857384, 7) columns=['source1_entity_id', 'matched_entity_ids', 's1_block_key', 'matched_block_key', 'captured', 'postal_block_s1', 'postal_block_s2']
missed_s2_remaining            shape=(857384, 6) columns=['source1_entity_id', 'matched_entity_ids', 's1_block_key', 'matched_block_key', 'captured', '_pair_key']

In [65]:
print("\nVariables containing 'postal', 's2', or 'miss':\n")

for name in globals():
    name_lower = name.lower()

    if (
        "postal" in name_lower
        or "s2" in name_lower
        or "miss" in name_lower
    ):
        obj = globals()[name]

        if isinstance(obj, pd.DataFrame):
            print(f"{name:30} DataFrame {obj.shape}")
        else:
            print(f"{name:30} {type(obj).__name__}")

Variables containing 'postal', 's2', or 'miss':

s2                             DataFrame (5034616, 7)
top_s2_keys                    Index
s2_blocks                      DataFrame (5034616, 2)
gt_s2                          DataFrame (3693619, 5)
missed_pairs                   int64
missed_s2                      DataFrame (857384, 5)
missed_s3                      DataFrame (968954, 5)
missed                         DataFrame (1826338, 6)
s2_info                        DataFrame (5034616, 4)
missed_s2_detail               DataFrame (857384, 10)
extract_postal                 function
s1_postal                      DataFrame (2206821, 2)
s2_postal                      DataFrame (5034616, 2)
gt_postal                      DataFrame (7638365, 5)
postal_captured                Series
missed_postal                  DataFrame (857384, 7)
postal_recovers_missed         Series
missed_s2_remaining            DataFrame (857384, 6)

In [66]:
# Make sure the postal recovery mask aligns with missed_s2
postal_recovers_missed = postal_recovers_missed.reindex(
    missed_s2.index,
    fill_value=False
)

# Keep only S2 pairs NOT recovered by postal blocking
missed_s2_remaining = missed_s2[
    ~postal_recovers_missed
].copy()

print("Original S2 missed:", len(missed_s2))
print("Recovered by postal:", postal_recovers_missed.sum())
print("Remaining S2 missed:", len(missed_s2_remaining))

Original S2 missed: 857384
Recovered by postal: 194364
Remaining S2 missed: 663020

In [67]:
print("Expected remaining:", 857384 - 837176)
print("Actual remaining:", len(missed_s2_remaining))

print("\nRecovery percentage:")
print(
    round(
        postal_recovers_missed.sum() / len(missed_s2) * 100,
        4
    ),
    "%"
)

Expected remaining: 20208
Actual remaining: 663020

Recovery percentage:
22.6694 %

In [69]:
print("missed_s2:", missed_s2.shape)
print("missed_postal:", missed_postal.shape)

print("\npostal_recovers_missed:")
print("length:", len(postal_recovers_missed))
print("index matches missed_s2:", postal_recovers_missed.index.equals(missed_s2.index))
print("True:", postal_recovers_missed.sum())
print("False:", (~postal_recovers_missed).sum())

print("\nmissed_postal columns:")
print(missed_postal.columns.tolist())

print("\nPostal block equality:")
postal_equal = (
    missed_postal["postal_block_s1"].notna()
    & missed_postal["postal_block_s2"].notna()
    & (
        missed_postal["postal_block_s1"]
        == missed_postal["postal_block_s2"]
    )
)

print("Equal postal blocks:", postal_equal.sum())
print("Not equal:", (~postal_equal).sum())

print("\nSample:")
display(
    missed_postal[
        [
            "source1_entity_id",
            "matched_entity_ids",
            "postal_block_s1",
            "postal_block_s2"
        ]
    ].head(20)
)

missed_s2: (857384, 5)
missed_postal: (857384, 7)

postal_recovers_missed:
length: 857384
index matches missed_s2: True
True: 194364
False: 663020

missed_postal columns:
['source1_entity_id', 'matched_entity_ids', 's1_block_key', 'matched_block_key', 'captured', 'postal_block_s1', 'postal_block_s2']

Postal block equality:
Equal postal blocks: 837176
Not equal: 20208

Sample:

   source1_entity_id matched_entity_ids postal_block_s1 postal_block_s2
0        S1-55344266       S2-249013014          India_          India_
1       S1-656753428       S2-153058913          India_          India_
2       S1-656753428        S2-24659151          India_          India_
3       S1-318373630       S2-660036492          India_          India_
4       S1-789009573       S2-383871912          India_          India_
5       S1-546142636       S2-392804085             US_             US_
6       S1-503957000       S2-994658326        US_20085        US_20085
7       S1-503957000       S2-353308450        US_20085        US_20085
8       S1-503957000       S2-173295926        US_20085        US_20085
9       S1-561341312       S2-483615364          India_     India_00516
10      S1-727602285       S2-976870196          India_          India_
11      S1-727602285       S2-947230367          India_          India_
12      S1-727602285       S2-138660620          India_          India_
13      S1-264156494       S2-184087846          India_          India_
14      S1-567308588       S2-191200521             US_             US_
15      S1-292935703       S2-195749344             US_             US_
16       S1-72310418       S2-516305116          India_          India_
17      S1-491795528       S2-977672203          India_          India_
18       S1-72444401       S2-973800896          India_          India_
19       S1-72444401       S2-503949813          India_          India_

In [72]:
# Valid postal match:
# 1. Both postal keys exist
# 2. They are equal
# 3. The key contains an actual postal value after "India_" / "US_"

postal_s1 = missed_postal["postal_block_s1"].fillna("").astype(str)
postal_s2 = missed_postal["postal_block_s2"].fillna("").astype(str)

valid_postal_recovery = (
    postal_s1.ne("")
    & postal_s2.ne("")
    & postal_s1.eq(postal_s2)
    & ~postal_s1.isin(["India_", "US_"])
)

print("Valid postal recoveries:", valid_postal_recovery.sum())
print("Invalid/remaining:", (~valid_postal_recovery).sum())

Valid postal recoveries: 23756
Invalid/remaining: 833628

In [73]:
empty_postal_match = (
    postal_s1.eq(postal_s2)
    & postal_s1.isin(["India_", "US_"])
)

print("Total equal postal keys:", postal_s1.eq(postal_s2).sum())
print("Empty postal matches:", empty_postal_match.sum())
print(
    "Actual postal matches:",
    postal_s1.eq(postal_s2).sum() - empty_postal_match.sum()
)

Total equal postal keys: 837176
Empty postal matches: 813420
Actual postal matches: 23756

In [81]:
# ============================================================
# STEP 4: VALID POSTAL RECOVERIES
# ============================================================

# Make sure both columns are strings
postal_s1 = missed_postal["postal_block_s1"].fillna("").astype(str)
postal_s2 = missed_postal["postal_block_s2"].fillna("").astype(str)

# Valid postal match:
# - both sides equal
# - not empty
# - not just "India_" or "US_"
valid_postal_mask = (
    postal_s1.eq(postal_s2)
    & postal_s1.ne("")
    & ~postal_s1.isin(["India_", "US_"])
)

print("Valid postal recoveries:", valid_postal_mask.sum())
print("Invalid/remaining:", (~valid_postal_mask).sum())

Valid postal recoveries: 23756
Invalid/remaining: 833628

In [85]:
# ============================================================
# STEP 5A — Build detailed remaining S2 dataframe
# ============================================================

missed_s2_remaining_detail = (
    missed_s2_remaining
    .merge(
        s1_info,
        on="source1_entity_id",
        how="left"
    )
    .merge(
        s2_info,
        on="matched_entity_ids",
        how="left"
    )
)

print("Shape:", missed_s2_remaining_detail.shape)
print("\nColumns:")
print(missed_s2_remaining_detail.columns.tolist())

Shape: (663020, 11)

Columns:
['source1_entity_id', 'matched_entity_ids', 's1_block_key', 'matched_block_key', 'captured', 's1_name', 's1_address', 's1_country', 'matched_name', 'matched_address', 'matched_country']

In [86]:
display(
    missed_s2_remaining_detail[
        [
            "source1_entity_id",
            "matched_entity_ids",
            "s1_name",
            "matched_name",
            "s1_address",
            "matched_address",
            "s1_country",
            "matched_country",
            "s1_block_key",
            "matched_block_key"
        ]
    ].head(30)
)

,source1_entity_id,matched_entity_ids,s1_name,matched_name,s1_address,matched_address,s1_country,matched_country,s1_block_key,matched_block_key
0,S1-307962633,S2-415653047,Historical Committee Inc.,HÍSTORICALCOMMITTEE.COM,"3823 Hidden Cove Court, Rockwall, TX","HIDDEN COVE CT, PMB 4364, ROCKWWALL, TX",US,US,US_hist,US_híst
1,S1-806616139,S2-512833764,Golden Power Pvt Ltd,gpower.com,"431, 441 F/F Front Side, Gali No.5 Guru Ram Da...","431, दिल्ली, EAST DELHI, 441 F/F FRONT SIDE, G...",India,India,India_gold,India_gpow
2,S1-740600107,S2-303262676,Tech Enterprises (India) Limited,Shri TECH ENTERPRISES LIMITED CENTER,"53/4, Nehru Nagar West, Coimbatore South, Coim...","53/4, NEHRU NAGAR WESM, COIMBATORE SOUTH, Tami...",India,India,India_tech,India_shri
3,S1-854707534,S2-19061664,Peridyn Chain LLC,LLC Peridyn Cháin,"NY, Brookhaven, 6 Heron Path","6-D HERON PATH, CORAM, NY",US,US,US_peri,US_llcp
4,S1-291419333,S2-352538774,Cozy Hypnosis!,C0zy Hypnósis!,"121 Friendship Street, Unit 2, Fall River, MA","FAL LRIVER, 121 FRIENDSHIP STREET, MA",US,US,US_cozy,US_c0zy
5,S1-602144510,S2-32696802,International Management Private Limited,इंटरनेशनल मैनेजमेंट प्राइवेट लिमिटेड,"C-93, G/F, Ring Road, Ndse-Ii, Delhi, New Delh...","C-93, DELHI, NEW DELHI, Delhi",India,India,India_inte,India_इटरन
6,S1-602144510,S2-64000798,International Management Private Limited,इंटरनेशनल मैनेजमेंट प्राइवेट लिमिटेड,"C-93, G/F, Ring Road, Ndse-Ii, Delhi, New Delh...","C-93, G/F, RING ROAD, NDSE-II, DELHI, NEW DELH...",India,India,India_inte,India_इटरन
7,S1-559249977,S2-312080751,My Investment Private Limited,माय इन्वेस्टमेंट प्राइवेट लिमिटेड,"C/O Mayank Anilkumar Sing, Chinchani District ...","C/O MAYANK ANILKUMAR SING, PALGHAR, THANE, Mah...",India,India,India_myin,India_मयइन
8,S1-507257254,S2-420623386,Galaxy Consultancy Limited,ಗ್ಯಾಲಕ್ಸಿ ಕನ್ಸಲ್ಟೆನ್ಸಿ ಲಿಮಿಟೆಡ್,"#270 10Th Main 2Nd Block Jayanagar, Bangalore,...","BENGALURU, #G-270 10TH MAIN 2ND BLOCK JAYANAGA...",India,India,India_gala,India_ಗಯಲಕ
9,S1-715642052,S2-484970278,Ds Properties Private Limited,Ds Limited Private Properties Properties,"Ambika Kunj, 194D, Satin Sen Sarani, 3Rd Floor...","পশ্চিমবঙ্গ, DOOR NO 112 AMBIKA KUNJ, 194D, SAT...",India,India,India_dspr,India_dsli
10,S1-805495186,S2-756829895,Bangalore South Engg Private Limited,Private Bangalore South Engg Limited,"Karnataka, No.2, Bangalore, Bangalore South, G...","DOOR NO 2, GROUND FLOOR, 16TH CROSS, KILARI RO...",India,India,India_bang,India_priv
11,S1-517951979,S2-974345181,Meeniya Rays Private Limited,Limited Meeniya Rays Center,"Maharashtra, 109/110, Penkar Pada, Gupta Compo...","0109/110, PENKAR PADA, GUPTA COMPOUND, BHANJI ...",India,India,India_meen,India_limi
12,S1-349849273,S2-164297098,Jajodia & Co Ltd,Dr Jajodia & Co Ltd,"B-303, Sai Anand Apartment, Sambhaji Nagar, Va...",NaN,India,India,India_jajo,India_drja
13,S1-996966377,S2-641682102,Lumin Educational Society,Dr Lumin Educational Society,"Bangalore North, Karnataka, Bangalore, Pradhan...","URBAN VAULT, PRADHANANI, WILSHIRE-1, NO 14, BA...",India,India,India_lumi,India_drlu
14,S1-657625699,S2-257177811,My Solutions Private Limited,माय सॉल्यूशंस प्राइवेट लिमिटेड,"Delhi, East Delhi, Delhi, C12 Gf Ganesh Nagar ...","C##12 GF GANESH NAGAR PANDAV NAGAR COMPLEX, DE...",India,India,India_myso,India_मयसल
15,S1-28453582,S2-72442936,Laxmi Foundation Pvt Ltd,லக்ஷ்மி ஃபவுண்டேஷன் பிரைவேட் லிமிடெட்,"No 45 F Karukinil, Amarthaval Koil Street, Kan...","DOOR NO #45 F KARUKINIL, AMARTHAVAL KOIL STREE...",India,India,India_laxm,India_லகஷம
16,S1-480158538,S2-121226226,Ram Logistics Private Limited,राम लॉजिस्टिक्स प्राइवेट लिमिटेड,"B-48, Hanuman Temple, Nr. Park Kiran Garden, U...","B-48, HANUMAN TEMPLE, NR. PARK KIRAN GARDEN, U...",India,India,India_raml,India_रमलज
17,S1-38241942,S2-568676161,Thasra Consultancy Private Limited,thásraconsultancy.com,"C/O Patel Manojkumar Ambalal, Near Bharat Petr...","C/O PATEL MANOJKUMAR AMBALAL, NEAR BHARAT PETR...",India,India,India_thas,India_thás
18,S1-973304639,S2-178208297,Good Finance,गुड फाइनेंस,"D-5, Gno 1, Khn 415, Sanjay Mohlla Bhajanpura,...","D-5, DELHI, NORTH EAST, Delhi",India,India,India_good,India_गडफइ
19,S1-34698027,S2-783389260,Unique Construction Pvt Ltd,यूनिक कंस्ट्रक्शन प्रा. लि.,S.No. 138/1 Green Olive Fl- A/501 Fl-A/501 Nr ...,S.NO. 138/1 GREEN OLIVE FL- A/501 FL-A/501 NR ...,India,India,India_uniq,India_यनकक
20,S1-34763037,S2-490957355,Sopan Advisors,S0PAN ADVISORS,"No.49, Chennai, Ganapathypuram 3Rd Main Road, ...","NO.49, GANAPATHYPURAM 3RD MAIN ROAD, CHENNAI, ...",India,India,India_sopa,India_s0pa
21,S1-762909028,S2-653449954,B 4 Supreme Mobile LLC,B 4 LLC Mobile Supreme,"4031 Caddy Way, IN, Indianapolis","4031 CADDY WAY, INDIANAPOLIS, IN",US,US,US_b4su,US_b4ll
22,S1-784019541,S2-149520139,Smith Healthcare,SMÍTHHEALTHCARE.COM,"134 320th Street, Town Of Cady, WI","320TH STREET, WILSON, WI",US,US,US_smit,US_smít
23,S1-244643323,S2-104793636,Good Life Services Pvt Ltd,गुड लाइफ सर्विसेज प्रा. लि.,"Plot No. 100-101, Sector-35, Hsiidc Udyog Viha...","DOOR NO 100-101/6, GURGAON, SADAR BAZAR, Haryana",India,India,India_good,India_गडलइ
24,S1-749692252,S2-656492795,Ace Tech Pvt Ltd,Ltd Ace Pvt Center,"Tirunelveli, Tamil Nadu, 7A, Tirunelveli, East...","TIRUNELVELI, Tamil Nadu, EAST BUS STAND STREET...",India,India,India_acet,India_ltda
25,S1-620524862,S2-717243563,Kassey's Holdings,Kadseei's Holdings,"50 Jefferson Avenue, Unit 101, Columbus, OH","JEFFERSON AVENUE, COLUMBUS, OH",US,US,US_kass,US_kads
26,S1-612826949,S2-381281396,Vision Care Limited,विजन केयर लिमिटेड,"Flat No: 1202, Tower-15, The Close South, Nirv...","C-881 FLAT NO: 1202, GURGAON, Haryana",India,India,India_visi,India_वजनक
27,S1-992567403,S2-756949980,Sai International Private Limited,साई इंटरनेशनल प्राइवेट लिमिटेड,"B36, Singh Bhumi, Khatipura, Kalwad, Rajasthan...","JAIPUR, SINGH BHUMI, KHATIPURA, KALWAD, राजस्थ...",India,India,India_saii,India_सईइट
28,S1-825190489,S2-499996460,Shree Estate,శ్రీ ఎస్టేట్,"Rangareddy, Telangana, 5-11-90, 301, Aryamitra...","5-11-90, HYDERABAD, RANGAREDDY, Telangana",India,India,India_shre,India_శరఎస
29,S1-761411416,S2-925497386,Bombay Products LLP,বোম্বে প্রোডাক্টস এলএলপি,"C/O Mallika Pailan, Daulatpur, Pailan, Bishnup...","DAULATPUR, PAILAN, BISHNUPUR - I, C/O MALLIKA ...",India,India,India_bomb,India_বমবপ

In [87]:
display(
    missed_s2_remaining_detail[
        [
            "source1_entity_id",
            "matched_entity_ids",
            "s1_name",
            "matched_name",
            "s1_address",
            "matched_address",
            "s1_country",
            "matched_country",
            "s1_block_key",
            "matched_block_key"
        ]
    ].head(30)
)

,source1_entity_id,matched_entity_ids,s1_name,matched_name,s1_address,matched_address,s1_country,matched_country,s1_block_key,matched_block_key
0,S1-307962633,S2-415653047,Historical Committee Inc.,HÍSTORICALCOMMITTEE.COM,"3823 Hidden Cove Court, Rockwall, TX","HIDDEN COVE CT, PMB 4364, ROCKWWALL, TX",US,US,US_hist,US_híst
1,S1-806616139,S2-512833764,Golden Power Pvt Ltd,gpower.com,"431, 441 F/F Front Side, Gali No.5 Guru Ram Da...","431, दिल्ली, EAST DELHI, 441 F/F FRONT SIDE, G...",India,India,India_gold,India_gpow
2,S1-740600107,S2-303262676,Tech Enterprises (India) Limited,Shri TECH ENTERPRISES LIMITED CENTER,"53/4, Nehru Nagar West, Coimbatore South, Coim...","53/4, NEHRU NAGAR WESM, COIMBATORE SOUTH, Tami...",India,India,India_tech,India_shri
3,S1-854707534,S2-19061664,Peridyn Chain LLC,LLC Peridyn Cháin,"NY, Brookhaven, 6 Heron Path","6-D HERON PATH, CORAM, NY",US,US,US_peri,US_llcp
4,S1-291419333,S2-352538774,Cozy Hypnosis!,C0zy Hypnósis!,"121 Friendship Street, Unit 2, Fall River, MA","FAL LRIVER, 121 FRIENDSHIP STREET, MA",US,US,US_cozy,US_c0zy
5,S1-602144510,S2-32696802,International Management Private Limited,इंटरनेशनल मैनेजमेंट प्राइवेट लिमिटेड,"C-93, G/F, Ring Road, Ndse-Ii, Delhi, New Delh...","C-93, DELHI, NEW DELHI, Delhi",India,India,India_inte,India_इटरन
6,S1-602144510,S2-64000798,International Management Private Limited,इंटरनेशनल मैनेजमेंट प्राइवेट लिमिटेड,"C-93, G/F, Ring Road, Ndse-Ii, Delhi, New Delh...","C-93, G/F, RING ROAD, NDSE-II, DELHI, NEW DELH...",India,India,India_inte,India_इटरन
7,S1-559249977,S2-312080751,My Investment Private Limited,माय इन्वेस्टमेंट प्राइवेट लिमिटेड,"C/O Mayank Anilkumar Sing, Chinchani District ...","C/O MAYANK ANILKUMAR SING, PALGHAR, THANE, Mah...",India,India,India_myin,India_मयइन
8,S1-507257254,S2-420623386,Galaxy Consultancy Limited,ಗ್ಯಾಲಕ್ಸಿ ಕನ್ಸಲ್ಟೆನ್ಸಿ ಲಿಮಿಟೆಡ್,"#270 10Th Main 2Nd Block Jayanagar, Bangalore,...","BENGALURU, #G-270 10TH MAIN 2ND BLOCK JAYANAGA...",India,India,India_gala,India_ಗಯಲಕ
9,S1-715642052,S2-484970278,Ds Properties Private Limited,Ds Limited Private Properties Properties,"Ambika Kunj, 194D, Satin Sen Sarani, 3Rd Floor...","পশ্চিমবঙ্গ, DOOR NO 112 AMBIKA KUNJ, 194D, SAT...",India,India,India_dspr,India_dsli
10,S1-805495186,S2-756829895,Bangalore South Engg Private Limited,Private Bangalore South Engg Limited,"Karnataka, No.2, Bangalore, Bangalore South, G...","DOOR NO 2, GROUND FLOOR, 16TH CROSS, KILARI RO...",India,India,India_bang,India_priv
11,S1-517951979,S2-974345181,Meeniya Rays Private Limited,Limited Meeniya Rays Center,"Maharashtra, 109/110, Penkar Pada, Gupta Compo...","0109/110, PENKAR PADA, GUPTA COMPOUND, BHANJI ...",India,India,India_meen,India_limi
12,S1-349849273,S2-164297098,Jajodia & Co Ltd,Dr Jajodia & Co Ltd,"B-303, Sai Anand Apartment, Sambhaji Nagar, Va...",NaN,India,India,India_jajo,India_drja
13,S1-996966377,S2-641682102,Lumin Educational Society,Dr Lumin Educational Society,"Bangalore North, Karnataka, Bangalore, Pradhan...","URBAN VAULT, PRADHANANI, WILSHIRE-1, NO 14, BA...",India,India,India_lumi,India_drlu
14,S1-657625699,S2-257177811,My Solutions Private Limited,माय सॉल्यूशंस प्राइवेट लिमिटेड,"Delhi, East Delhi, Delhi, C12 Gf Ganesh Nagar ...","C##12 GF GANESH NAGAR PANDAV NAGAR COMPLEX, DE...",India,India,India_myso,India_मयसल
15,S1-28453582,S2-72442936,Laxmi Foundation Pvt Ltd,லக்ஷ்மி ஃபவுண்டேஷன் பிரைவேட் லிமிடெட்,"No 45 F Karukinil, Amarthaval Koil Street, Kan...","DOOR NO #45 F KARUKINIL, AMARTHAVAL KOIL STREE...",India,India,India_laxm,India_லகஷம
16,S1-480158538,S2-121226226,Ram Logistics Private Limited,राम लॉजिस्टिक्स प्राइवेट लिमिटेड,"B-48, Hanuman Temple, Nr. Park Kiran Garden, U...","B-48, HANUMAN TEMPLE, NR. PARK KIRAN GARDEN, U...",India,India,India_raml,India_रमलज
17,S1-38241942,S2-568676161,Thasra Consultancy Private Limited,thásraconsultancy.com,"C/O Patel Manojkumar Ambalal, Near Bharat Petr...","C/O PATEL MANOJKUMAR AMBALAL, NEAR BHARAT PETR...",India,India,India_thas,India_thás
18,S1-973304639,S2-178208297,Good Finance,गुड फाइनेंस,"D-5, Gno 1, Khn 415, Sanjay Mohlla Bhajanpura,...","D-5, DELHI, NORTH EAST, Delhi",India,India,India_good,India_गडफइ
19,S1-34698027,S2-783389260,Unique Construction Pvt Ltd,यूनिक कंस्ट्रक्शन प्रा. लि.,S.No. 138/1 Green Olive Fl- A/501 Fl-A/501 Nr ...,S.NO. 138/1 GREEN OLIVE FL- A/501 FL-A/501 NR ...,India,India,India_uniq,India_यनकक
20,S1-34763037,S2-490957355,Sopan Advisors,S0PAN ADVISORS,"No.49, Chennai, Ganapathypuram 3Rd Main Road, ...","NO.49, GANAPATHYPURAM 3RD MAIN ROAD, CHENNAI, ...",India,India,India_sopa,India_s0pa
21,S1-762909028,S2-653449954,B 4 Supreme Mobile LLC,B 4 LLC Mobile Supreme,"4031 Caddy Way, IN, Indianapolis","4031 CADDY WAY, INDIANAPOLIS, IN",US,US,US_b4su,US_b4ll
22,S1-784019541,S2-149520139,Smith Healthcare,SMÍTHHEALTHCARE.COM,"134 320th Street, Town Of Cady, WI","320TH STREET, WILSON, WI",US,US,US_smit,US_smít
23,S1-244643323,S2-104793636,Good Life Services Pvt Ltd,गुड लाइफ सर्विसेज प्रा. लि.,"Plot No. 100-101, Sector-35, Hsiidc Udyog Viha...","DOOR NO 100-101/6, GURGAON, SADAR BAZAR, Haryana",India,India,India_good,India_गडलइ
24,S1-749692252,S2-656492795,Ace Tech Pvt Ltd,Ltd Ace Pvt Center,"Tirunelveli, Tamil Nadu, 7A, Tirunelveli, East...","TIRUNELVELI, Tamil Nadu, EAST BUS STAND STREET...",India,India,India_acet,India_ltda
25,S1-620524862,S2-717243563,Kassey's Holdings,Kadseei's Holdings,"50 Jefferson Avenue, Unit 101, Columbus, OH","JEFFERSON AVENUE, COLUMBUS, OH",US,US,US_kass,US_kads
26,S1-612826949,S2-381281396,Vision Care Limited,विजन केयर लिमिटेड,"Flat No: 1202, Tower-15, The Close South, Nirv...","C-881 FLAT NO: 1202, GURGAON, Haryana",India,India,India_visi,India_वजनक
27,S1-992567403,S2-756949980,Sai International Private Limited,साई इंटरनेशनल प्राइवेट लिमिटेड,"B36, Singh Bhumi, Khatipura, Kalwad, Rajasthan...","JAIPUR, SINGH BHUMI, KHATIPURA, KALWAD, राजस्थ...",India,India,India_saii,India_सईइट
28,S1-825190489,S2-499996460,Shree Estate,శ్రీ ఎస్టేట్,"Rangareddy, Telangana, 5-11-90, 301, Aryamitra...","5-11-90, HYDERABAD, RANGAREDDY, Telangana",India,India,India_shre,India_శరఎస
29,S1-761411416,S2-925497386,Bombay Products LLP,বোম্বে প্রোডাক্টস এলএলপি,"C/O Mallika Pailan, Daulatpur, Pailan, Bishnup...","DAULATPUR, PAILAN, BISHNUPUR - I, C/O MALLIKA ...",India,India,India_bomb,India_বমবপ

In [88]:
print(
    missed_s2_remaining_detail[
        ["s1_country", "matched_country"]
    ].value_counts()
)

s1_country  matched_country
India       India              459336
US          US                 203684
Name: count, dtype: int64

In [89]:
block_mismatch = (
    missed_s2_remaining_detail
    .groupby(
        ["s1_block_key", "matched_block_key"]
    )
    .size()
    .sort_values(ascending=False)
)

display(block_mismatch.head(50))

s1_block_key  matched_block_key
India_pion    India_पयनय           1605
India_east    India_ईसटर           1560
India_laxm    India_लकषम           1547
India_sout    India_सदरन           1542
India_inno    India_इनवट           1540
India_digi    India_डजटल           1533
India_tiru    India_तरपत           1526
India_fort    India_फरचय           1521
India_arih    India_अरहत           1518
India_clas    India_कलसक           1517
India_silv    India_सलवर           1506
India_guja    India_गजरत           1501
India_futu    India_फयचर           1497
India_adit    India_आदतय           1495
India_glob    India_गलबल           1494
India_sunr    India_सनरइ           1487
India_mode    India_मडरन           1487
India_indi    India_इडयन           1482
India_prem    India_परमय           1479
India_apex    India_एपकस           1471
India_whit    India_वहइट           1470
India_unit    India_यनइट           1469
India_gala    India_गलकस           1467
India_swas    India_सवसत           1466
India_dyna    India_डयनम           1466
India_smar    India_समरट           1465
India_urba    India_अरबन           1464
India_laks    India_लकषम           1460
India_univ    India_यनवर           1457
India_brig    India_बरइट           1441
India_supr    India_सपरम           1431
India_prim    India_परइम           1426
India_perf    India_परफक           1422
India_crea    India_करएट           1409
India_firs    India_फरसट           1403
India_hite    India_हईटक           1390
India_gold    India_गलडन           1389
India_inte    India_इटरन           1361
US_pedi       US_llcp               338
US_inte       US_lnte               310
India_bhar    India_भरतइ            293
US_inte       US_llci               291
India_shiv    India_शवकस            274
India_arih    India_అరహత            265
India_uniq    India_यनकइ            258
India_star    India_सटरइ            258
India_sout    India_ಸದರನ            258
India_smar    India_ஸமரட            256
India_shiv    India_शवपर            253
India_gold    India_गलडइ            252
dtype: int64

In [90]:
same_country = (
    missed_s2_remaining_detail["s1_country"]
    .astype(str)
    .str.lower()
    ==
    missed_s2_remaining_detail["matched_country"]
    .astype(str)
    .str.lower()
)

print("Same country:", same_country.sum())
print("Different country:", (~same_country).sum())
print("Same-country %:", same_country.mean() * 100)

Same country: 663020
Different country: 0
Same-country %: 100.0

In [95]:
import sys
!{sys.executable} -m pip install rapidfuzz

Collecting rapidfuzz
  Downloading rapidfuzz-3.14.6-cp312-cp312-win_amd64.whl.metadata (12 kB)
Downloading rapidfuzz-3.14.6-cp312-cp312-win_amd64.whl (1.7 MB)
   ---------------------------------------- 0.0/1.7 MB ? eta -:--:--
   ---------------------------------------- 1.7/1.7 MB 11.8 MB/s  0:00:00
Installing collected packages: rapidfuzz
Successfully installed rapidfuzz-3.14.6

In [96]:
import sys
print(sys.executable)

!{sys.executable} -m pip show rapidfuzz

c:\Users\HP\AppData\Local\Programs\Python\Python312\python.exe
Name: RapidFuzz
Version: 3.14.6
Summary: rapid fuzzy string matching
Home-page: https://github.com/rapidfuzz/RapidFuzz
Author:
Author-email: Max Bachmann <pypi@maxbachmann.de>
License-Expression: MIT
Location: c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages
Requires:
Required-by:

In [97]:
from rapidfuzz.fuzz import ratio

print(ratio("hello", "helo"))

88.88888888888889

In [98]:
import sys
print(sys.executable)

c:\Users\HP\AppData\Local\Programs\Python\Python312\python.exe

In [100]:
# Calculate name and address similarity
remaining = missed_s2_remaining_detail.copy()

remaining["name_s1_norm"] = remaining["s1_name"].map(normalize_text)
remaining["name_s2_norm"] = remaining["matched_name"].map(normalize_text)

remaining["address_s1_norm"] = remaining["s1_address"].map(normalize_text)
remaining["address_s2_norm"] = remaining["matched_address"].map(normalize_text)

remaining["name_score"] = [
    ratio(a, b)
    for a, b in zip(
        remaining["name_s1_norm"],
        remaining["name_s2_norm"]
    )
]

remaining["address_score"] = [
    ratio(a, b)
    for a, b in zip(
        remaining["address_s1_norm"],
        remaining["address_s2_norm"]
    )
]

remaining["combined_score"] = (
    0.65 * remaining["name_score"] +
    0.35 * remaining["address_score"]
)

print("Remaining candidates:", len(remaining))

print("\nScore distribution:")
display(
    remaining[
        ["name_score", "address_score", "combined_score"]
    ].describe()
)

Remaining candidates: 663020

Score distribution:

          name_score  address_score  combined_score
count  663020.000000  663020.000000   663020.000000
mean       46.723148      78.050844       57.687841
std        33.081084      20.378957       23.406681
min         0.000000       0.000000        8.666667
25%        10.526316      65.486726       36.468558
50%        54.054054      83.870968       60.443350
75%        78.260870      94.117647       79.402768
max        98.630137     100.000000       98.773585

In [101]:
display(
    remaining.sort_values(
        "combined_score",
        ascending=False
    )[
        [
            "source1_entity_id",
            "matched_entity_ids",
            "s1_name",
            "matched_name",
            "s1_address",
            "matched_address",
            "name_score",
            "address_score",
            "combined_score"
        ]
    ].head(100)
)

,source1_entity_id,matched_entity_ids,s1_name,matched_name,s1_address,matched_address,name_score,address_score,combined_score
323891,S1-917424756,S2-904051473,Michael Holdings Group LLC,Mnichael Holdings Group LLC,"2950 Arizona Way, Manchester, MD","#2950 ARIZONA WAY, MANCHESTER, MD",98.113208,100.0,98.773585
172544,S1-633447588,S2-971801269,Al Skilled Private Limited,Al Sakilled Private Limited,"Chinchani, Tal Tasgaon Dist Sangli, Sangli, Ma...","CHINCHANI, TAL TASGAON DIST SANGLI, SANGLI, Ma...",98.113208,100.0,98.773585
619790,S1-33212034,S2-446786670,CC Global Private Limited,CC Gnlobal Private Limited,"Flat No. A 501 Bcm Height, Pu-4 Scheme N0. 54,...","FLAT NO. A 501 BCM HEIGHT, PU-4 SCHEME N0. 54...",98.039216,100.0,98.725490
308687,S1-795310232,S2-976744875,AN Herbal Private Limited,AN Hgerbal Private Limited,"305 P H Complex Vijay Block, Laxmi Nagar, New ...","305 P H COMPLEX VIJAY BLOCK, LAXMI NAGAR, NEW ...",98.039216,100.0,98.725490
87716,S1-479403742,S2-64080606,Wareham Holdings Group LLC,Warham Holdings Group [LLC],"1013 Fargo Drive, Mckinney, TX","1013 FARGO DRIVE, MCKINNEY, TX",98.039216,100.0,98.725490
...,...,...,...,...,...,...,...,...,...
296535,S1-127580558,S2-847400591,Philippe Murphy Custom Frequency LLC,Phi1ippe Murphy Custom Frequency LLC,"92-62 Queens Boulevard, Rego Park, NY","92-62 QUEENS BOULEVARD, REGO PARK, NY",97.222222,100.0,98.194444
277188,S1-165700724,S2-934779565,Corporate Education Laboratories LLC,C0rporate Education Laboratories LLC,"55 Burton Road, Franklin, WV","55 BURTON ROAD, FRANKLIN, WV",97.222222,100.0,98.194444
126129,S1-395267752,S2-712084495,"Joletta Carlson Unified Vertical, Inc.","J0letta Carlson Unified Vertical, Inc.","38 Harbor Heights Road, Scituate, MA","38 Harbor Heights Road, SCITUATE, MA",97.222222,100.0,98.194444
11591,S1-685829932,S2-577038988,Usg (India) Infraconstructions Pvt Ltd,Usg (Índia) Infraconstructions Pvt Ltd,Flat No A/602 Rameshwar Neelkanth Heights Pokh...,FLAT NO A/602 RAMESHWAR NEELKANTH HEIGHTS POKH...,97.222222,100.0,98.194444
120646,S1-311359701,S2-86566910,Urology Frontier Care Associates LLC,Ur0logy Frontier Care Associates LLC,"Avon Lake, 33410 Chelsea Avenue, OH","AVON LAKE, 33410 Chelsea Avenue, OH",97.222222,100.0,98.194444

In [102]:
# Build a sample of known TRUE S2 pairs
true_s2 = gt_s2.copy()

# Attach S1 information
true_s2 = true_s2.merge(
    s1_info,
    on="source1_entity_id",
    how="left"
)

# Attach S2 information
true_s2 = true_s2.merge(
    s2_info,
    on="matched_entity_ids",
    how="left"
)

print("True S2 pairs:", len(true_s2))
print(true_s2.columns.tolist())

True S2 pairs: 3693619
['source1_entity_id', 'matched_entity_ids', 's1_block_key', 'matched_block_key', 'captured', 's1_name', 's1_address', 's1_country', 'matched_name', 'matched_address', 'matched_country']

In [103]:
true_s2["name_s1_norm"] = true_s2["s1_name"].map(normalize_text)
true_s2["name_s2_norm"] = true_s2["matched_name"].map(normalize_text)

true_s2["address_s1_norm"] = true_s2["s1_address"].map(normalize_text)
true_s2["address_s2_norm"] = true_s2["matched_address"].map(normalize_text)

true_s2["name_score"] = [
    ratio(a, b)
    for a, b in zip(
        true_s2["name_s1_norm"],
        true_s2["name_s2_norm"]
    )
]

true_s2["address_score"] = [
    ratio(a, b)
    for a, b in zip(
        true_s2["address_s1_norm"],
        true_s2["address_s2_norm"]
    )
]

true_s2["combined_score"] = (
    0.65 * true_s2["name_score"] +
    0.35 * true_s2["address_score"]
)

display(
    true_s2[
        ["name_score", "address_score", "combined_score"]
    ].describe()
)

         name_score  address_score  combined_score
count  3.693619e+06   3.693619e+06    3.693619e+06
mean   7.877297e+01   7.909784e+01    7.888667e+01
std    2.586183e+01   2.305207e+01    1.896701e+01
min    0.000000e+00   0.000000e+00    8.125000e+00
25%    7.272727e+01   7.111111e+01    7.282430e+01
50%    8.780488e+01   8.656716e+01    8.471272e+01
75%    9.615385e+01   9.473684e+01    9.225191e+01
max    1.000000e+02   1.000000e+02    1.000000e+02

In [104]:
display(
    true_s2.sort_values(
        "combined_score",
        ascending=True
    )[
        [
            "source1_entity_id",
            "matched_entity_ids",
            "s1_name",
            "matched_name",
            "s1_address",
            "matched_address",
            "name_score",
            "address_score",
            "combined_score"
        ]
    ].head(100)
)

,source1_entity_id,matched_entity_ids,s1_name,matched_name,s1_address,matched_address,name_score,address_score,combined_score
135233,S1-379082029,S2-980240110,# 4 NA Coinshares,# 4,"1477 Grayson Street, Nocona, TX",NaN,12.500000,0.000000,8.125000
2819644,S1-994168313,S2-601773616,D & N Clough LLC,#d,"Hebron, 3131 30, NY",NaN,13.333333,0.000000,8.666667
3300460,S1-6684419,S2-260842643,# 3 SE Research,# 3,"357 Delgany Trail, Haslet, TX",NaN,14.285714,0.000000,9.285714
1022891,S1-24835166,S2-928335426,P & L Lafayette,P (&),"4816 Ancestry Street, Haltom City, TX",NaN,14.285714,0.000000,9.285714
1308780,S1-313042577,S2-638425682,F & U Altenergy,F-&,"TN, 1448 Cottage Glen Lane, Maryville",NaN,14.285714,0.000000,9.285714
...,...,...,...,...,...,...,...,...,...
37841,S1-42151717,S2-71467835,Sai Infrastructure Private Limited,साई इंफ्रास्ट्रक्चर प्राइवेट लिमिटेड,"Fl C, 1401, M Sb, K S Galaxy, Plot 11 And 15 S...","RAIGARH, FL C, महाराष्ट्र",8.571429,19.298246,12.325815
2281911,S1-958515461,S2-826643271,Sunrise Foundation,सनराइज फाउंडेशन,"216, Kohinoor Arcade, 2Nd Floor Tilak Chowk, M...","216, PUNE, महाराष्ट्र",6.060606,24.000000,12.339394
179233,S1-861331864,S2-725468780,Global Construction,ગ્લોબલ કન્સ્ટ્રક્શન,"406 4Th Floor, W-1, Opp Psp House, B/H S. G. H...","ગુજરાત, AHMEDABD, ##406 4TH FLOOR",5.263158,25.490196,12.342621
2749513,S1-604801234,S2-151440931,Green Foundation,ಗ್ರೀನ್ ಫೌಂಡೇಶನ್,"Plot No. 21, 32, 33, 34, Kiadb Industrial Area...","316, MANDYA, ಕರ್ನಾಟಕ",7.142857,22.000000,12.342857
1920976,S1-975427321,S2-476895437,Digital Infrastructure LLP,डिजिटल इंफ्रास्ट्रक्चर एलएलपी,"C-103, Floor-1St, Plot-103/104, C Wing, Rajgir...","Maharashtra, C-03, AMRAVATI",7.407407,21.518987,12.346460

In [107]:
thresholds = [80, 85, 90, 92, 94, 95, 96, 97, 98]

print("REMAINING CANDIDATES")
print("=" * 70)

for t in thresholds:
    n = (remaining["combined_score"] >= t).sum()
    pct = n / len(remaining) * 100

    print(
        f"Threshold >= {t}: "
        f"{n:,} candidates ({pct:.2f}%)"
    )

print("\nTRUE S2 PAIRS")
print("=" * 70)

for t in thresholds:
    n = (true_s2_scored["combined_score"] >= t).sum()
    pct = n / len(true_s2_scored) * 100

    print(
        f"Threshold >= {t}: "
        f"{n:,} true pairs ({pct:.2f}% recall)"
    )

REMAINING CANDIDATES
======================================================================
Threshold >= 80: 158,897 candidates (23.97%)
Threshold >= 85: 99,629 candidates (15.03%)
Threshold >= 90: 45,486 candidates (6.86%)
Threshold >= 92: 27,402 candidates (4.13%)
Threshold >= 94: 13,427 candidates (2.03%)
Threshold >= 95: 8,194 candidates (1.24%)
Threshold >= 96: 3,911 candidates (0.59%)
Threshold >= 97: 1,474 candidates (0.22%)
Threshold >= 98: 197 candidates (0.03%)

TRUE S2 PAIRS
======================================================================

NameError: name 'true_s2_scored' is not defined

In [110]:
# ============================================
# Create scored ground-truth S2 pairs
# ============================================

import pandas as pd
import re
import unicodedata

# Start from the known TRUE S2 pairs
true_s2_scored = gt_s2.copy()

# Normalize text for fuzzy comparison
def normalize_text(x):
    if pd.isna(x):
        return ""
    
    x = str(x).lower()
    x = unicodedata.normalize("NFKD", x)
    x = "".join(c for c in x if not unicodedata.combining(c))
    x = re.sub(r"[^a-z0-9]+", " ", x)
    x = re.sub(r"\s+", " ", x).strip()
    
    return x


# Use the existing detailed information
true_s2_scored = true_s2_scored.merge(
    s1_info,
    on="source1_entity_id",
    how="left"
)

true_s2_scored = true_s2_scored.merge(
    s2_info,
    on="matched_entity_ids",
    how="left"
)

# Check columns
print("Columns:")
print(true_s2_scored.columns.tolist())

print("\nShape:")
print(true_s2_scored.shape)

Columns:
['source1_entity_id', 'matched_entity_ids', 's1_block_key', 'matched_block_key', 'captured', 's1_name', 's1_address', 's1_country', 'matched_name', 'matched_address', 'matched_country']

Shape:
(3693619, 11)

In [112]:
# ============================================
# Score TRUE S2 pairs
# ============================================

from difflib import SequenceMatcher

def similarity(a, b):
    a = normalize_text(a)
    b = normalize_text(b)

    if not a or not b:
        return 0.0

    return SequenceMatcher(None, a, b).ratio() * 100


true_s2_scored["name_score"] = true_s2_scored.apply(
    lambda r: similarity(
        r["s1_name"],
        r["matched_name"]
    ),
    axis=1
)

true_s2_scored["address_score"] = true_s2_scored.apply(
    lambda r: similarity(
        r["s1_address"],
        r["matched_address"]
    ),
    axis=1
)

# Same weighting as your remaining candidates
true_s2_scored["combined_score"] = (
    0.6 * true_s2_scored["name_score"]
    + 0.4 * true_s2_scored["address_score"]
)

print("TRUE S2 PAIRS:", len(true_s2_scored))

display(
    true_s2_scored[
        [
            "source1_entity_id",
            "matched_entity_ids",
            "s1_name",
            "matched_name",
            "s1_address",
            "matched_address",
            "name_score",
            "address_score",
            "combined_score"
        ]
    ].describe()
)

TRUE S2 PAIRS: 3693619

         name_score  address_score  combined_score
count  3.693619e+06   3.693619e+06    3.693619e+06
mean   7.799797e+01   7.910375e+01    7.844028e+01
std    2.864231e+01   2.337465e+01    1.993699e+01
min    0.000000e+00   0.000000e+00    1.739130e+00
25%    7.272727e+01   7.118644e+01    7.273657e+01
50%    8.800000e+01   8.709677e+01    8.468702e+01
75%    1.000000e+02   9.473684e+01    9.238896e+01
max    1.000000e+02   1.000000e+02    1.000000e+02

In [113]:
thresholds = [80, 85, 90, 92, 94, 95, 96, 97, 98]

print("=" * 75)
print("THRESHOLD ANALYSIS")
print("=" * 75)

print(
    f"{'Threshold':<12}"
    f"{'True Captured':<18}"
    f"{'True Recall':<18}"
    f"{'Remaining Candidates':<22}"
)

print("-" * 75)

for t in thresholds:

    true_captured = (
        true_s2_scored["combined_score"] >= t
    ).sum()

    true_recall = (
        true_captured /
        len(true_s2_scored) *
        100
    )

    remaining_candidates = (
        remaining["combined_score"] >= t
    ).sum()

    print(
        f"{t:<12}"
        f"{true_captured:<18,}"
        f"{true_recall:<18.2f}%"
        f"{remaining_candidates:<22,}"
    )

===========================================================================
THRESHOLD ANALYSIS
===========================================================================
Threshold   True Captured     True Recall       Remaining Candidates
---------------------------------------------------------------------------
80          2,297,560         62.20             %158,897
85          1,817,321         49.20             %99,629
90          1,241,447         33.61             %45,486
92          981,147           26.56             %27,402
94          711,489           19.26             %13,427
95          585,022           15.84             %8,194
96          465,206           12.59             %3,911
97          350,073           9.48              %1,474
98          237,186           6.42              %197

In [114]:
# ============================================
# STEP 1: Inspect scripts in remaining S2 pairs
# ============================================

import unicodedata
import pandas as pd

def detect_script(text):
    if pd.isna(text):
        return "EMPTY"

    text = str(text)

    scripts = set()

    for ch in text:
        if not ch.isalpha():
            continue

        name = unicodedata.name(ch, "")

        if "LATIN" in name:
            scripts.add("Latin")
        elif "DEVANAGARI" in name:
            scripts.add("Devanagari")
        elif "TELUGU" in name:
            scripts.add("Telugu")
        elif "KANNADA" in name:
            scripts.add("Kannada")
        elif "TAMIL" in name:
            scripts.add("Tamil")
        elif "GUJARATI" in name:
            scripts.add("Gujarati")
        elif "BENGALI" in name:
            scripts.add("Bengali")
        elif "MALAYALAM" in name:
            scripts.add("Malayalam")
        elif "GURMUKHI" in name:
            scripts.add("Gurmukhi")
        else:
            scripts.add("Other")

    if not scripts:
        return "EMPTY"

    return "+".join(sorted(scripts))


remaining["s1_script"] = remaining["s1_name"].apply(detect_script)
remaining["s2_script"] = remaining["matched_name"].apply(detect_script)

print("S1 scripts:")
print(remaining["s1_script"].value_counts())

print("\nS2 scripts:")
print(remaining["s2_script"].value_counts())

S1 scripts:
s1_script
Latin    663020
Name: count, dtype: int64

S2 scripts:
s2_script
Latin               401300
Devanagari          144968
Telugu               21142
Kannada              20227
Tamil                18127
Bengali              16567
Gujarati             16522
Malayalam            10213
Other                 3984
Gurmukhi              3653
Devanagari+Latin      3546
Latin+Telugu           515
Kannada+Latin          479
Latin+Tamil            461
Bengali+Latin          405
Gujarati+Latin         396
Latin+Malayalam        262
Latin+Other             98
Gurmukhi+Latin          92
EMPTY                   63
Name: count, dtype: int64

In [116]:
cross_script = remaining[
    remaining["s1_script"] != remaining["s2_script"]
].copy()

print("Total cross-script candidates:", len(cross_script))

display(
    cross_script[
        [
            "source1_entity_id",
            "matched_entity_ids",
            "s1_name",
            "matched_name",
            "s1_address",
            "matched_address",
            "name_score",
            "address_score",
            "combined_score",
            "s1_script",
            "s2_script"
        ]
    ].head(30)
)

Total cross-script candidates: 261720

,source1_entity_id,matched_entity_ids,s1_name,matched_name,s1_address,matched_address,name_score,address_score,combined_score,s1_script,s2_script
5,S1-602144510,S2-32696802,International Management Private Limited,इंटरनेशनल मैनेजमेंट प्राइवेट लिमिटेड,"C-93, G/F, Ring Road, Ndse-Ii, Delhi, New Delh...","C-93, DELHI, NEW DELHI, Delhi",8.000000,70.270270,29.794595,Latin,Devanagari
6,S1-602144510,S2-64000798,International Management Private Limited,इंटरनेशनल मैनेजमेंट प्राइवेट लिमिटेड,"C-93, G/F, Ring Road, Ndse-Ii, Delhi, New Delh...","C-93, G/F, RING ROAD, NDSE-II, DELHI, NEW DELH...",8.000000,100.000000,40.200000,Latin,Devanagari
7,S1-559249977,S2-312080751,My Investment Private Limited,माय इन्वेस्टमेंट प्राइवेट लिमिटेड,"C/O Mayank Anilkumar Sing, Chinchani District ...","C/O MAYANK ANILKUMAR SING, PALGHAR, THANE, Mah...",9.836066,80.314961,34.503679,Latin,Devanagari
8,S1-507257254,S2-420623386,Galaxy Consultancy Limited,ಗ್ಯಾಲಕ್ಸಿ ಕನ್ಸಲ್ಟೆನ್ಸಿ ಲಿಮಿಟೆಡ್,"#270 10Th Main 2Nd Block Jayanagar, Bangalore,...","BENGALURU, #G-270 10TH MAIN 2ND BLOCK JAYANAGA...",7.407407,89.830508,36.255493,Latin,Kannada
14,S1-657625699,S2-257177811,My Solutions Private Limited,माय सॉल्यूशंस प्राइवेट लिमिटेड,"Delhi, East Delhi, Delhi, C12 Gf Ganesh Nagar ...","C##12 GF GANESH NAGAR PANDAV NAGAR COMPLEX, DE...",10.344828,62.992126,28.771382,Latin,Devanagari
15,S1-28453582,S2-72442936,Laxmi Foundation Pvt Ltd,லக்ஷ்மி ஃபவுண்டேஷன் பிரைவேட் லிமிடெட்,"No 45 F Karukinil, Amarthaval Koil Street, Kan...","DOOR NO #45 F KARUKINIL, AMARTHAVAL KOIL STREE...",10.526316,96.815287,40.727456,Latin,Tamil
16,S1-480158538,S2-121226226,Ram Logistics Private Limited,राम लॉजिस्टिक्स प्राइवेट लिमिटेड,"B-48, Hanuman Temple, Nr. Park Kiran Garden, U...","B-48, HANUMAN TEMPLE, NR. PARK KIRAN GARDEN, U...",9.836066,100.000000,41.393443,Latin,Devanagari
18,S1-973304639,S2-178208297,Good Finance,गुड फाइनेंस,"D-5, Gno 1, Khn 415, Sanjay Mohlla Bhajanpura,...","D-5, DELHI, NORTH EAST, Delhi",9.090909,46.017699,22.015286,Latin,Devanagari
19,S1-34698027,S2-783389260,Unique Construction Pvt Ltd,यूनिक कंस्ट्रक्शन प्रा. लि.,S.No. 138/1 Green Olive Fl- A/501 Fl-A/501 Nr ...,S.NO. 138/1 GREEN OLIVE FL- A/501 FL-A/501 NR ...,12.000000,100.000000,42.800000,Latin,Devanagari
23,S1-244643323,S2-104793636,Good Life Services Pvt Ltd,गुड लाइफ सर्विसेज प्रा. लि.,"Plot No. 100-101, Sector-35, Hsiidc Udyog Viha...","DOOR NO 100-101/6, GURGAON, SADAR BAZAR, Haryana",16.326531,58.267717,31.005946,Latin,Devanagari
26,S1-612826949,S2-381281396,Vision Care Limited,विजन केयर लिमिटेड,"Flat No: 1202, Tower-15, The Close South, Nirv...","C-881 FLAT NO: 1202, GURGAON, Haryana",11.111111,49.557522,24.567355,Latin,Devanagari
27,S1-992567403,S2-756949980,Sai International Private Limited,साई इंटरनेशनल प्राइवेट लिमिटेड,"B36, Singh Bhumi, Khatipura, Kalwad, Rajasthan...","JAIPUR, SINGH BHUMI, KHATIPURA, KALWAD, राजस्थ...",9.523810,71.153846,31.094322,Latin,Devanagari
28,S1-825190489,S2-499996460,Shree Estate,శ్రీ ఎస్టేట్,"Rangareddy, Telangana, 5-11-90, 301, Aryamitra...","5-11-90, HYDERABAD, RANGAREDDY, Telangana",9.090909,34.965035,18.146853,Latin,Telugu
29,S1-761411416,S2-925497386,Bombay Products LLP,বোম্বে প্রোডাক্টস এলএলপি,"C/O Mallika Pailan, Daulatpur, Pailan, Bishnup...","DAULATPUR, PAILAN, BISHNUPUR - I, C/O MALLIKA ...",9.756098,62.337662,28.159645,Latin,Bengali
30,S1-520560165,S2-635497661,Gujarat Consultancy Private Limited,गुजरात कंसल्टेंसी प्राइवेट लिमिटेड,"S-318, First Floor, Greater Kailash-2, New Del...","S-318, FIRST FLOOR, GREATER KAILASH-2, NEW DEL...",8.955224,100.000000,40.820896,Latin,Devanagari
32,S1-679705210,S2-579842583,Innovative It Private Limited,इनोवेटिव आईटी प्राइवेट लिमिटेड,"C/O Shaheenasajjadkhan, Sn-60/4-6, Clover Heig...","C/O SHAHEENASAJJADKHAN, PUNE, SN-60/4-6, CLOVE...",10.344828,85.858586,36.774643,Latin,Devanagari
38,S1-124537839,S2-320411308,Surya Real Projects Private Limited,ସୂର୍ଯ୍ୟ ରିଅଲ୍ ପ୍ରୋଜେକ୍ଟସ୍ ପ୍ରାଇଭେଟ୍ ଲିମିଟେଡ୍,"G.A. Plot No-19, Goutam Nagar, Bhubaneswar, Kh...","G.A. PLOT NO-18, KHORDHA, BHUBANESWAR, GOUTAM ...",10.666667,66.666667,30.266667,Latin,Other
39,S1-580998526,S2-245233543,Urban Impex Private Limited,अर्बन इम्पेक्स प्राइवेट लिमिटेड,"Pune, Flat No 3, Bldg No 3 Koregaon Road, 5 Ko...","FLAT NO 3, BLDG NO 3 KOREGAON ROAD, 5 KOREGAON...",10.344828,94.736842,39.882033,Latin,Devanagari
43,S1-520076987,S2-174633696,Southern Builders,ಸದರ್ನ್ ಬಿಲ್ಡರ್ಸ್,"Karnataka, Halasulige, Magadi Village, Hassan,...","MAGADI VILLAGE, HALASULIGE POST SAKLESPUR TALU...",6.451613,69.662921,28.575571,Latin,Kannada
45,S1-569516464,S2-661268672,Real Krishna Energy Private Limited,रियल कृष्ण एनर्जी प्राइवेट लिमिटेड,"Haryana, Faridabad, Sector-10 Housing Board Co...","HOUSE NO. 111, SECTOR-10 HOUSING BOARD COLONY,...",11.764706,62.251656,29.435138,Latin,Devanagari
47,S1-886725766,S2-862465014,All It Private Limited,ஆல் ஐடி பிரைவேட் லிமிடெட்,"25/Ground Floor (Sf/115), Nelson Manickam Road...","NO 25/GROUND FLOOR (SF/115), EGMORE NUNGAMBAKK...",13.953488,72.222222,34.347545,Latin,Tamil
48,S1-326923183,S2-500550228,Dynamic Energy Private Limited,डायनामिक एनर्जी प्राइवेट लिमिटेड,"Agra, 46/1070D/8A Viram Nagar Kisore Pura, Utt...","46/1070D/8A VIRAM NAGAR KISORE PURA, AGRA, Utt...",9.836066,90.740741,38.152702,Latin,Devanagari
49,S1-321275283,S2-972840591,Indo International LLP,इंडो इंटरनेशनल एलएलपी,"Rajasthan, Jaipur, 30-A Rseb Colony Vaishali N...","30-A RSEB COLONY VAISHALI NAGAR, N/A, JAIPUR, ...",9.756098,62.626263,28.260655,Latin,Devanagari
53,S1-744328082,S2-57612835,Jain Hospitality,जैन हॉस्पिटैलिटी,C-509 Rahul Classicsaibaba Nagar Borivali West...,C-609 RAHUL CLASSICSAIBABA NAGAR BORIVALI WEST...,6.451613,92.207792,36.466276,Latin,Devanagari
55,S1-129074534,S2-657619281,Global Estate Pvt Ltd,ग्लोबल एस्टेट प्रा. लि.,"Flat No. 143, Gali No.4, Bank Colony Mandoli, ...","DOOR NO 143, SHAHDARA, NORTH EAST, Delhi",15.000000,55.445545,29.155941,Latin,Devanagari
63,S1-752723427,S2-360853655,Tech Builders Private Limited,टेक बिल्डर्स प्राइवेट लिमिटेड,"C-4 B/P 13/265 Janakpuri New Delhi, Delhi, Sou...","C-4 B/P 13/265 JANAKPURI NEW DELHI, Delhi, SOU...",10.344828,96.183206,40.388260,Latin,Devanagari
64,S1-345097478,S2-445734854,High Care Private Limited,हाई केयर प्राइवेट लिमिटेड,"South Delhi, Vardhman Star City Mall Sector-7,...","SHOP NO - 149, VARDHMAN STAR CITY MALL SECTOR-...",12.000000,75.949367,34.382278,Latin,Devanagari
65,S1-485617345,S2-518084344,Dynamic Infra Private Limited,டைனமிக் இன்ஃப்ரா பிரைவேட் லிமிடெட்,"New No 1 Tendulkar Street, Sy No. 165 6A, Said...","NEW NO 001 TENDULKAR STREET, null, SAIDAPET, K...",10.169492,75.757576,33.125321,Latin,Tamil
71,S1-928748198,S2-527169657,Ram East Products LLP,ರಾಮ್ ಈಸ್ಟ್ ಪ್ರೊಡಕ್ಟ್ಸ್ ಎಲ್ಎಲ್‌ಪಿ,No 829 2Nd Floor 26Th Main Opp 9Th A Cross Sec...,829 2ND FLOOR 26TH MAIN OPP 9TH A CROSS SECTOR...,12.500000,79.329609,35.890363,Latin,Kannada
82,S1-487074724,S2-683076543,Perfect Builders Private Limited,ପର୍ଫେକ୍ଟ୍ ବିଲଡର୍ସ୍ ପ୍ରାଇଭେଟ୍ ଲିମିଟେଡ୍,"Orissa, Saranya, Bhubaneswar, Khordha, Plot No...","H.NO 441 SARANYA, BHUBANESWAR, KHORDHA, Orissa",9.230769,48.226950,22.879433,Latin,Other

In [117]:
true_s2_scored["s1_script"] = (
    true_s2_scored["s1_name"].apply(detect_script)
)

true_s2_scored["s2_script"] = (
    true_s2_scored["matched_name"].apply(detect_script)
)

true_cross_script = true_s2_scored[
    true_s2_scored["s1_script"] != true_s2_scored["s2_script"]
].copy()

print(
    "True cross-script S2 pairs:",
    len(true_cross_script)
)

display(
    true_cross_script[
        [
            "s1_name",
            "matched_name",
            "name_score",
            "address_score",
            "combined_score",
            "s1_script",
            "s2_script"
        ]
    ].head(30)
)

True cross-script S2 pairs: 344641

,s1_name,matched_name,name_score,address_score,combined_score,s1_script,s2_script
2,Raj Investments LLP,ராஜ் இன்வெஸ்ட்மெண்ட்ஸ் எல்எல்பி,0.000000,100.000000,40.000000,Latin,Tamil
6,Ss Food Private Limited,एसएस फूड प्राइवेट लिमिटेड,0.000000,81.761006,32.704403,Latin,Devanagari
7,Ss Food Private Limited,एसएस फूड प्राइवेट लिमिटेड,0.000000,32.000000,12.800000,Latin,Devanagari
12,Red Ventures Private Limited,रेड वेंचर्स प्राइवेट लिमिटेड,0.000000,38.775510,15.510204,Latin,Devanagari
14,Hotel Enterprises Limited,होटल एंटरप्राइजेज लिमिटेड,0.000000,56.551724,22.620690,Latin,Devanagari
32,Balaji Investment Private Limited,బాలాజీ ఇన్వెస్ట్‌మెంట్ ప్రైవేట్ లిమిటెడ్,0.000000,53.913043,21.565217,Latin,Telugu
35,Swastik Om Solutions LLP,स्वस्तिक ॐ सॉल्यूशंस एलएलपी,0.000000,69.306931,27.722772,Latin,Devanagari
36,Swastik Om Solutions LLP,स्वस्तिक ॐ सॉल्यूशंस एलएलपी,0.000000,93.750000,37.500000,Latin,Devanagari
71,New Solutions,न्यू सॉल्यूशंस,0.000000,79.661017,31.864407,Latin,Devanagari
74,New Solutions,न्यू सॉल्यूशंस,0.000000,79.661017,31.864407,Latin,Devanagari
106,Ram Maa Logistics Private Limited,राम मां लॉजिस्टिक्स प्राइवेट लिमिटेड,0.000000,46.017699,18.407080,Latin,Devanagari
139,Sun Software Limited,सन सॉफ्टवेयर लिमिटेड,0.000000,100.000000,40.000000,Latin,Devanagari
144,Guru Solutions Pvt Ltd,ಗುರು ಸೊಲ್ಯೂಷನ್ಸ್ ಪ್ರೈವೇಟ್ ಲಿಮಿಟೆಡ್,0.000000,98.076923,39.230769,Latin,Kannada
148,Jain Marketing Private Limited,जैन मार्केटिंग प्राइवेट लिमिटेड,0.000000,70.769231,28.307692,Latin,Devanagari
232,Gold Projects Pvt Ltd,ಗೋಲ್ಡ್ ಪ್ರಾಜೆಕ್ಟ್ಸ್ ಪ್ರೈವೇಟ್ ಲಿಮಿಟೆಡ್,0.000000,93.805310,37.522124,Latin,Kannada
233,Gold Projects Pvt Ltd,ಗೋಲ್ಡ್ ಪ್ರಾಜೆಕ್ಟ್ಸ್ ಪ್ರೈವೇಟ್ ಲಿಮಿಟೆಡ್,0.000000,93.805310,37.522124,Latin,Kannada
235,Gold Projects Pvt Ltd,ಗೋಲ್ಡ್ ಪ್ರಾಜೆಕ್ಟ್ಸ್ ಪ್ರೈವೇಟ್ ಲಿಮಿಟೆಡ್,0.000000,65.740741,26.296296,Latin,Kannada
237,Red Global Limited,রেড গ্লোবাল লিমিটেড,0.000000,56.488550,22.595420,Latin,Bengali
242,South Estate Private Limited,साउथ एस्टेट प्राइवेट लिमिटेड,0.000000,100.000000,40.000000,Latin,Devanagari
253,Swastik Marketing,स्वस्तिक मार्केटिंग,0.000000,83.760684,33.504274,Latin,Devanagari
254,Shiva Exports,शिवा एक्सपोर्ट्स,0.000000,89.473684,35.789474,Latin,Devanagari
285,Jai Trading Private Limited,ജയ് ട്രേഡിംഗ് പ്രൈവറ്റ് ലിമിറ്റഡ്,0.000000,63.461538,25.384615,Latin,Malayalam
294,Hari Urban Ventures Pvt Ltd,హరి అర్బన్ వెంచర్స్ ప్రైవేట్ లిమిటెడ్,0.000000,69.291339,27.716535,Latin,Telugu
326,Prime Media Pvt Ltd,प्राइम मीडिया प्रा. लि.,0.000000,98.550725,39.420290,Latin,Devanagari
327,Prime Media Pvt Ltd,प्राइम मीडिया प्रा. लि.,0.000000,76.422764,30.569106,Latin,Devanagari
328,Prime Media Pvt Ltd,प्राइम मीडिया Pvt Ltd,53.846154,88.405797,67.670011,Latin,Devanagari+Latin
333,Om Investment,ओम Investment,86.956522,91.851852,88.914654,Latin,Devanagari+Latin
341,Future Management Pvt Ltd,फ्यूचर मैनेजमेंट प्रा. लि.,0.000000,68.750000,27.500000,Latin,Devanagari
360,Red Energy Pvt Ltd,ରେଡ୍ ଏନର୍ଜି ପ୍ରାଇଭେଟ୍ ଲିମିଟେଡ୍,0.000000,86.713287,34.685315,Latin,Other
374,Vijay Universal Exports Pvt Ltd,ವಿಜಯ್ ಯುನಿವರ್ಸಲ್ ಎಕ್ಸ್‌ಪೋರ್ಟ್ಸ್ ಪ್ರೈವೇಟ್ ಲಿಮಿಟೆಡ್,0.000000,60.215054,24.086022,Latin,Kannada

In [118]:
print("Cross-script related DataFrames:")

for name, obj in globals().items():
    if hasattr(obj, "columns") and isinstance(obj, pd.DataFrame):
        cols = set(obj.columns)

        if (
            "s1_script" in cols
            or "s2_script" in cols
            or "script" in name.lower()
            or "cross" in name.lower()
        ):
            print(f"{name:30} shape={obj.shape}")

Cross-script related DataFrames:
remaining                      shape=(663020, 20)
true_s2_scored                 shape=(3693619, 16)
cross_script                   shape=(261720, 20)
true_cross_script              shape=(344641, 16)

In [119]:
print("=" * 70)
print("CROSS-SCRIPT SCORE ANALYSIS")
print("=" * 70)

print("\nTrue cross-script pairs:", len(true_cross_script))
print("Remaining cross-script candidates:", len(cross_script))

print("\n--- TRUE CROSS-SCRIPT SCORE DISTRIBUTION ---")
display(
    true_cross_script[
        ["name_score", "address_score", "combined_score"]
    ].describe()
)

print("\n--- REMAINING CROSS-SCRIPT SCORE DISTRIBUTION ---")
display(
    cross_script[
        ["name_score", "address_score", "combined_score"]
    ].describe()
)

======================================================================
CROSS-SCRIPT SCORE ANALYSIS
======================================================================

True cross-script pairs: 344641
Remaining cross-script candidates: 261720

--- TRUE CROSS-SCRIPT SCORE DISTRIBUTION ---

          name_score  address_score  combined_score
count  344641.000000  344641.000000   344641.000000
mean        2.626982      74.924692       31.546066
std        13.191214      21.273499       11.845259
min         0.000000       0.000000        1.739130
25%         0.000000      58.974359       23.829787
50%         0.000000      80.000000       32.413793
75%         0.000000      93.333333       37.829457
max        95.652174     100.000000       97.108305

--- REMAINING CROSS-SCRIPT SCORE DISTRIBUTION ---

          name_score  address_score  combined_score
count  261720.000000  261720.000000   261720.000000
mean       11.380514      74.816863       33.583236
std         7.950937      20.151044        8.768197
min         0.000000       0.000000        9.285714
25%         9.090909      59.060403       27.499139
50%        10.000000      78.378378       34.324898
75%        11.320755      92.500000       39.333333
max        95.384615     100.000000       95.422535

In [120]:
thresholds = [50, 60, 65, 70, 75, 80, 85, 90, 92, 94, 95]

print("\n" + "=" * 70)
print("CROSS-SCRIPT THRESHOLD ANALYSIS")
print("=" * 70)

print(
    f"{'Threshold':<12}"
    f"{'True Captured':<18}"
    f"{'True Recall %':<18}"
)

print("-" * 50)

total_true = len(true_cross_script)

for t in thresholds:
    captured = (true_cross_script["combined_score"] >= t).sum()
    recall = captured / total_true * 100

    print(
        f"{t:<12}"
        f"{captured:<18}"
        f"{recall:<18.2f}"
    )

======================================================================
CROSS-SCRIPT THRESHOLD ANALYSIS
======================================================================
Threshold   True Captured     True Recall %
--------------------------------------------------
50          12894             3.74
60          10359             3.01
65          9023              2.62
70          7521              2.18
75          5810              1.69
80          4008              1.16
85          2227              0.65
90          770               0.22
92          379               0.11
94          129               0.04
95          58                0.02

In [121]:
cross_script_low = (
    true_cross_script
    .sort_values("combined_score", ascending=True)
)

display(
    cross_script_low[
        [
            "s1_name",
            "matched_name",
            "s1_address",
            "matched_address",
            "name_score",
            "address_score",
            "combined_score"
        ]
    ].head(100)
)

,s1_name,matched_name,s1_address,matched_address,name_score,address_score,combined_score
1130914,Seven Technologies Limited,सेवन टेक्नोलॉजीज लिमिटेड,"108, Bldg-5, Veena Saaz (Veena Swar), Opp. Tha...","GREATER BOMBAY, महाराष्ट्र, #950 108",0.0,4.347826,1.739130
1385516,Modern Global Private Limited,मॉडर्न ग्लोबल प्राइवेट लिमिटेड,"40, Rz Block South Extension Part-1, Uttam Nag...","DIVREPORTINGCIRCLE, 40, दिल्ली",0.0,4.444444,1.777778
3437553,Creative Food Private Limited,ક્રિએટિવ ફૂડ પ્રાઇવેટ લિમિટેડ,"32, First Floor, Krishnacomplex Radhanpur Char...","RAKSA, ગુજરાત, 32",0.0,4.819277,1.927711
2570991,Star Tech Private Limited,स्टार टेक प्राइवेट लिमिटेड,"315, Shivai Plaza, Bhd Ravi Vihar Hotel Lane T...","GREATOR BOMBAY, महाराष्ट्र, 315",0.0,5.084746,2.033898
2969562,Krishna Estate Private Limited,कृष्णा एस्टेट प्राइवेट लिमिटेड,"117, Pocket A-4 Konark Apartments, Kalkaji Ext...","SONIPAT, दिल्ली, 117",0.0,6.741573,2.696629
...,...,...,...,...,...,...,...
1813559,North It Private Limited,নর্থ আইটি প্রাইভেট লিমিটেড,"9A, Chatterjee International Chamber, 9Th Floo...","#9A, HOWRAH, পশ্চিমবঙ্গ",0.0,13.533835,5.413534
2820456,Sree Foundation Private Limited,ಶ್ರೀ ಫೌಂಡೇಶನ್ ಪ್ರೈವೇಟ್ ಲಿಮಿಟೆಡ್,"Lmcpl, 57/1A, 1St Floor, Unit-24, Devarabisana...","Karnataka, LMCPL, BENGALURU",0.0,13.533835,5.413534
1656744,North Technology Pvt Ltd,नॉर्थ टेक्नोलॉजी प्रा. लि.,"Level 10, Hudson And Ganges, Embassy Tech Zone...","Maharashtra, MULSHI, PUNE, LEVEL 10",0.0,13.580247,5.432099
2080386,Surya Foundation Private Limited,सूर्या फाउंडेशन प्राइवेट लिमिटेड,"Nashik, Shriram Niwas, Chhatrapati Colony, Vad...","8, NASHIK, महाराष्ट्र",0.0,13.592233,5.436893
3608830,Lakshmi Investments Private Limited,लक्ष्मी इन्वेस्टमेंट्स प्राइवेट लिमिटेड,"1/ 4233, Second Floor Ansari Road, Darya Ganj,...","GAUTAM BUDH NAGAR, दिल्ली, 1/ 4233",0.0,13.636364,5.454545

In [125]:
# STEP 4: Cross-script name transliteration
# ------------------------------------------

import re
import pandas as pd

# Install once if needed:
# !pip install indic-transliteration

from indic_transliteration import sanscript
from indic_transliteration.sanscript import transliterate


# --------------------------------------------------
# Script ranges
# --------------------------------------------------

SCRIPT_RANGES = {
    "Devanagari": (0x0900, 0x097F),
    "Bengali":    (0x0980, 0x09FF),
    "Gurmukhi":   (0x0A00, 0x0A7F),
    "Gujarati":   (0x0A80, 0x0AFF),
    "Tamil":      (0x0B80, 0x0BFF),
    "Telugu":     (0x0C00, 0x0C7F),
    "Kannada":    (0x0C80, 0x0CFF),
    "Malayalam":  (0x0D00, 0x0D7F),
}


SCRIPT_TO_SANSCRIPT = {
    "Devanagari": sanscript.DEVANAGARI,
    "Bengali":    sanscript.BENGALI,
    "Gurmukhi":   sanscript.GURMUKHI,
    "Gujarati":   sanscript.GUJARATI,
    "Tamil":      sanscript.TAMIL,
    "Telugu":     sanscript.TELUGU,
    "Kannada":    sanscript.KANNADA,
    "Malayalam":  sanscript.MALAYALAM,
}


def get_char_script(ch):
    cp = ord(ch)

    for script, (lo, hi) in SCRIPT_RANGES.items():
        if lo <= cp <= hi:
            return script

    return None


def transliterate_name(text):
    """
    Convert Indian-script portions to Latin while preserving
    existing Latin text, numbers and punctuation.
    """

    if pd.isna(text):
        return ""

    text = str(text)

    output = []
    current_script = None
    current_text = []

    def flush():
        nonlocal current_script, current_text

        if not current_text:
            return

        chunk = "".join(current_text)

        if current_script in SCRIPT_TO_SANSCRIPT:
            try:
                converted = transliterate(
                    chunk,
                    current_script_source,
                    sanscript.ITRANS
                )
            except Exception:
                converted = chunk
        else:
            converted = chunk

        output.append(converted)

        current_text = []

    for ch in text:

        script = get_char_script(ch)

        if script != current_script:

            # Flush previous run
            if current_text:

                if current_script in SCRIPT_TO_SANSCRIPT:
                    current_script_source = SCRIPT_TO_SANSCRIPT[current_script]

                    try:
                        output.append(
                            transliterate(
                                "".join(current_text),
                                current_script_source,
                                sanscript.ITRANS
                            )
                        )
                    except Exception:
                        output.append("".join(current_text))
                else:
                    output.append("".join(current_text))

                current_text = []

            current_script = script

        current_text.append(ch)

    # Flush final run
    if current_text:

        if current_script in SCRIPT_TO_SANSCRIPT:
            current_script_source = SCRIPT_TO_SANSCRIPT[current_script]

            try:
                output.append(
                    transliterate(
                        "".join(current_text),
                        current_script_source,
                        sanscript.ITRANS
                    )
                )
            except Exception:
                output.append("".join(current_text))
        else:
            output.append("".join(current_text))

    return "".join(output)


# --------------------------------------------------
# Test examples
# --------------------------------------------------

test_names = [
    "राज् इन्वेस्टमेंट्स एलएलपी",
    "एसएस फूड प्राइवेट लिमिटेड",
    "బాలాజీ ఇన్వెస్ట్‌మెంట్ ప్రైవేట్ లిమిటెడ్",
    "ಗುರು ಸೊಲ್ಯೂಷನ್ಸ್ ಪ್ರೈವೇಟ್ ಲಿಮಿಟೆಡ್",
    "ராஜ் இன்வெஸ்ட்மெண்ட்ஸ் எல்எல்பி",
    "রেড গ্লোবাল লিমিটেড",
]

for x in test_names:
    print(x)
    print(" -> ", transliterate_name(x))
    print()

राज् इन्वेस्टमेंट्स एलएलपी
 ->  rAj invesTameMTsa elaelapI

एसएस फूड प्राइवेट लिमिटेड
 ->  esaesa phUDa prAiveTa limiTeDa

బాలాజీ ఇన్వెస్ట్‌మెంట్ ప్రైవేట్ లిమిటెడ్
 ->  bAlAjI invèsT‌mèMT praiveT limiTèD

ಗುರು ಸೊಲ್ಯೂಷನ್ಸ್ ಪ್ರೈವೇಟ್ ಲಿಮಿಟೆಡ್
 ->  guru sòlyUShans praiveT limiTèD

ராஜ் இன்வெஸ்ட்மெண்ட்ஸ் எல்எல்பி
 ->  rAj iனvèsDhmèNDhs èlèlbhi

রেড গ্লোবাল লিমিটেড
 ->  reDa glovAla limiTeDa

In [126]:
# Create transliterated S2 names

cross_script = cross_script.copy()

cross_script["matched_name_latin"] = (
    cross_script["matched_name"]
    .fillna("")
    .apply(transliterate_name)
)

display(
    cross_script[
        [
            "s1_name",
            "matched_name",
            "matched_name_latin",
            "s1_script",
            "s2_script"
        ]
    ].head(50)
)

,s1_name,matched_name,matched_name_latin,s1_script,s2_script
5,International Management Private Limited,इंटरनेशनल मैनेजमेंट प्राइवेट लिमिटेड,iMTaraneshanala mainejameMTa prAiveTa limiTeDa,Latin,Devanagari
6,International Management Private Limited,इंटरनेशनल मैनेजमेंट प्राइवेट लिमिटेड,iMTaraneshanala mainejameMTa prAiveTa limiTeDa,Latin,Devanagari
7,My Investment Private Limited,माय इन्वेस्टमेंट प्राइवेट लिमिटेड,mAya invesTameMTa prAiveTa limiTeDa,Latin,Devanagari
8,Galaxy Consultancy Limited,ಗ್ಯಾಲಕ್ಸಿ ಕನ್ಸಲ್ಟೆನ್ಸಿ ಲಿಮಿಟೆಡ್,gyAlaksi kansalTènsi limiTèD,Latin,Kannada
14,My Solutions Private Limited,माय सॉल्यूशंस प्राइवेट लिमिटेड,mAya saॉlyUshaMsa prAiveTa limiTeDa,Latin,Devanagari
15,Laxmi Foundation Pvt Ltd,லக்ஷ்மி ஃபவுண்டேஷன் பிரைவேட் லிமிடெட்,lakShmi favuNDheShaன bhiraiveDh limiDhèDh,Latin,Tamil
16,Ram Logistics Private Limited,राम लॉजिस्टिक्स प्राइवेट लिमिटेड,rAma laॉjisTiksa prAiveTa limiTeDa,Latin,Devanagari
18,Good Finance,गुड फाइनेंस,guDa phAineMsa,Latin,Devanagari
19,Unique Construction Pvt Ltd,यूनिक कंस्ट्रक्शन प्रा. लि.,yUnika kaMsTrakshana prA. li.,Latin,Devanagari
23,Good Life Services Pvt Ltd,गुड लाइफ सर्विसेज प्रा. लि.,guDa lAipha sarviseja prA. li.,Latin,Devanagari
26,Vision Care Limited,विजन केयर लिमिटेड,vijana keyara limiTeDa,Latin,Devanagari
27,Sai International Private Limited,साई इंटरनेशनल प्राइवेट लिमिटेड,sAI iMTaraneshanala prAiveTa limiTeDa,Latin,Devanagari
28,Shree Estate,శ్రీ ఎస్టేట్,shrI èsTeT,Latin,Telugu
29,Bombay Products LLP,বোম্বে প্রোডাক্টস এলএলপি,vomve proDAkTasa elaelapi,Latin,Bengali
30,Gujarat Consultancy Private Limited,गुजरात कंसल्टेंसी प्राइवेट लिमिटेड,gujarAta kaMsalTeMsI prAiveTa limiTeDa,Latin,Devanagari
32,Innovative It Private Limited,इनोवेटिव आईटी प्राइवेट लिमिटेड,inoveTiva AITI prAiveTa limiTeDa,Latin,Devanagari
38,Surya Real Projects Private Limited,ସୂର୍ଯ୍ୟ ରିଅଲ୍ ପ୍ରୋଜେକ୍ଟସ୍ ପ୍ରାଇଭେଟ୍ ଲିମିଟେଡ୍,ସୂର୍ଯ୍ୟ ରିଅଲ୍ ପ୍ରୋଜେକ୍ଟସ୍ ପ୍ରାଇଭେଟ୍ ଲିମିଟେଡ୍,Latin,Other
39,Urban Impex Private Limited,अर्बन इम्पेक्स प्राइवेट लिमिटेड,arbana impeksa prAiveTa limiTeDa,Latin,Devanagari
43,Southern Builders,ಸದರ್ನ್ ಬಿಲ್ಡರ್ಸ್,sadarn bilDars,Latin,Kannada
45,Real Krishna Energy Private Limited,रियल कृष्ण एनर्जी प्राइवेट लिमिटेड,riyala kRRiShNa enarjI prAiveTa limiTeDa,Latin,Devanagari
47,All It Private Limited,ஆல் ஐடி பிரைவேட் லிமிடெட்,Al aiDhi bhiraiveDh limiDhèDh,Latin,Tamil
48,Dynamic Energy Private Limited,डायनामिक एनर्जी प्राइवेट लिमिटेड,DAyanAmika enarjI prAiveTa limiTeDa,Latin,Devanagari
49,Indo International LLP,इंडो इंटरनेशनल एलएलपी,iMDo iMTaraneshanala elaelapI,Latin,Devanagari
53,Jain Hospitality,जैन हॉस्पिटैलिटी,jaina haॉspiTailiTI,Latin,Devanagari
55,Global Estate Pvt Ltd,ग्लोबल एस्टेट प्रा. लि.,globala esTeTa prA. li.,Latin,Devanagari
63,Tech Builders Private Limited,टेक बिल्डर्स प्राइवेट लिमिटेड,Teka bilDarsa prAiveTa limiTeDa,Latin,Devanagari
64,High Care Private Limited,हाई केयर प्राइवेट लिमिटेड,hAI keyara prAiveTa limiTeDa,Latin,Devanagari
65,Dynamic Infra Private Limited,டைனமிக் இன்ஃப்ரா பிரைவேட் லிமிடெட்,Dhaiனmigh iனfrA bhiraiveDh limiDhèDh,Latin,Tamil
71,Ram East Products LLP,ರಾಮ್ ಈಸ್ಟ್ ಪ್ರೊಡಕ್ಟ್ಸ್ ಎಲ್ಎಲ್‌ಪಿ,rAm IsT pròDakTs èlèl‌pi,Latin,Kannada
82,Perfect Builders Private Limited,ପର୍ଫେକ୍ଟ୍ ବିଲଡର୍ସ୍ ପ୍ରାଇଭେଟ୍ ଲିମିଟେଡ୍,ପର୍ଫେକ୍ଟ୍ ବିଲଡର୍ସ୍ ପ୍ରାଇଭେଟ୍ ଲିମିଟେଡ୍,Latin,Other
83,All Media Private Limited,ऑल मीडिया प्राइवेट लिमिटेड,ऑla mIDiyA prAiveTa limiTeDa,Latin,Devanagari
84,Star Impex Private Limited,ಸ್ಟಾರ್ ಇಂಪೆಕ್ಸ್ ಪ್ರೈವೇಟ್ ಲಿಮಿಟೆಡ್,sTAr iMpèks praiveT limiTèD,Latin,Kannada
85,Hari Engineering Private Limited,हरि इंजीनियरिंग प्राइवेट लिमिटेड,hari iMjIniyariMga prAiveTa limiTeDa,Latin,Devanagari
90,Gujarat Consulting Private Limited,ಗುಜರಾತ್ ಕನ್ಸಲ್ಟಿಂಗ್ ಪ್ರೈವೇಟ್ ಲಿಮಿಟೆಡ್,gujarAt kansalTiMg praiveT limiTèD,Latin,Kannada
91,Gujarat Consulting Private Limited,ಗುಜರಾತ್ ಕನ್ಸಲ್ಟಿಂಗ್ ಪ್ರೈವೇಟ್ ಲಿಮಿಟೆಡ್,gujarAt kansalTiMg praiveT limiTèD,Latin,Kannada
94,Urban One Marketing Pvt Ltd,અર્બન વન માર્કેટિંગ પ્રા. લિ.,arbana vana mArkeTiMga prA. li.,Latin,Gujarati
97,Star Global Private Limited,स्टार ग्लोबल प्राइवेट लिमिटेड,sTAra globala prAiveTa limiTeDa,Latin,Devanagari
98,Baba Business LLP,बाबा बिजनेस एलएलपी,bAbA bijanesa elaelapI,Latin,Devanagari
99,Indian Trading Private Limited,इंडियन ट्रेडिंग प्राइवेट लिमिटेड,iMDiyana TreDiMga prAiveTa limiTeDa,Latin,Devanagari
103,Best Impex Private Limited,બેસ્ટ ઇમ્પેક્સ પ્રાઇવેટ લિમિટેડ,besTa impeksa prAiveTa limiTeDa,Latin,Gujarati
105,Shiva Food LLP,சிவா ஃபுட் எல்எல்பி,jhivA fuDh èlèlbhi,Latin,Tamil
106,Vijay Logistics Pvt Ltd,ವಿಜಯ್ ಲಾಜಿಸ್ಟಿಕ್ಸ್ ಪ್ರೈವೇಟ್ ಲಿಮಿಟೆಡ್,vijay lAjisTiks praiveT limiTèD,Latin,Kannada
108,Unique Surya Infrastructure Private Limited,यूनिक सूर्य इंफ्रास्ट्रक्चर प्राइवेट लिमिटेड,yUnika sUrya iMphrAsTrakchara prAiveTa limiTeDa,Latin,Devanagari
109,Lotus Foods Private Limited,लोटस फूड्स प्राइवेट लिमिटेड,loTasa phUDsa prAiveTa limiTeDa,Latin,Devanagari
114,High Constructions Private Limited,ಹೈ ಕನ್‌ಸ್ಟ್ರಕ್ಷನ್ಸ್ ಪ್ರೈವೇಟ್ ಲಿಮಿಟೆಡ್,hai kan‌sTrakShans praiveT limiTèD,Latin,Kannada
115,Life Engineering Private Limited,लाइफ इंजीनियरिंग प्राइवेट लिमिटेड,lAipha iMjIniyariMga prAiveTa limiTeDa,Latin,Devanagari
116,Arihant Hospitality,अरिहंत हॉस्पिटैलिटी,arihaMta haॉspiTailiTI,Latin,Devanagari
117,Prime Properties Private Limited,பிரைம் புராப்பர்ட்டீஸ் பிரைவேட் லிமிடெட்,bhiraiM bhurAbhbharDhDhIs bhiraiveDh limiDhèDh,Latin,Tamil
119,Big Management Pvt Ltd,ಬಿಗ್ ಮ್ಯಾನೇಜ್‌ಮೆಂಟ್ ಪ್ರೈವೇಟ್ ಲಿಮಿಟೆಡ್,big myAnej‌mèMT praiveT limiTèD,Latin,Kannada
122,Jai Care Private Limited,ജയ് കെയർ പ്രൈവറ്റ് ലിമിറ്റഡ്,jay kèyaർ praivaRR limiRRaD,Latin,Malayalam

In [127]:
from rapidfuzz.fuzz import ratio

def normalize_for_match(x):
    if pd.isna(x):
        return ""

    x = str(x).lower()

    # Replace ITRANS-style punctuation/symbols
    x = x.replace("'", "")
    x = x.replace("~", "")
    x = x.replace(":", "")

    # Keep only alphanumeric characters
    x = re.sub(r"[^a-z0-9]+", " ", x)

    # Collapse spaces
    x = re.sub(r"\s+", " ", x).strip()

    return x


cross_script["s1_name_norm"] = (
    cross_script["s1_name"]
    .apply(normalize_for_match)
)

cross_script["s2_name_latin_norm"] = (
    cross_script["matched_name_latin"]
    .apply(normalize_for_match)
)


cross_script["name_score_translit"] = cross_script.apply(
    lambda r: ratio(
        r["s1_name_norm"],
        r["s2_name_latin_norm"]
    ),
    axis=1
)


display(
    cross_script[
        [
            "s1_name",
            "matched_name",
            "matched_name_latin",
            "name_score",
            "name_score_translit"
        ]
    ].sort_values(
        "name_score_translit",
        ascending=False
    ).head(100)
)

,s1_name,matched_name,matched_name_latin,name_score,name_score_translit
324521,Alpha Agro Private Limited,ಆಲ್ಫಾ ಅಗ್ರೋ Private Limited,AlphA agro Private Limited,66.666667,100.0
511084,Lakshmi Enterprises Private Limited,लक्ष्मी Enterprises Private Limited,lakShmI Enterprises Private Limited,81.159420,100.0
646084,Aditya Consulting LLP,आदित्य Consulting LLP,Aditya Consulting LLP,71.428571,100.0
609499,Shiva Finance Pvt Ltd,శివ Finance Pvt Ltd,shiva Finance Pvt Ltd,80.000000,100.0
335504,Vijay International Limited,വിജയ് International Limited,vijay International Limited,83.018868,100.0
...,...,...,...,...,...
147460,Jain Properties Limited,ಜೈನ್ Properties Limited,jain Properties Limited,84.444444,100.0
479193,Alpha Foundation Private Limited,ಆಲ್ಫಾ Foundation Private Limited,AlphA Foundation Private Limited,85.714286,100.0
299849,Raj Agro,రాజ్ ఆగ్రో,rAj Agro,12.500000,100.0
113668,Shakti Marketing Private Limited,शक्ति Marketing Private Limited,shakti Marketing Private Limited,83.870968,100.0
21413,Shakti Future Exports Private Limited,शक्ति Future Exports Private Limited,shakti Future Exports Private Limited,86.111111,100.0

In [128]:
print("=" * 70)
print("CROSS-SCRIPT NAME TRANSLITERATION IMPROVEMENT")
print("=" * 70)

print("\nOld name score:")
print(cross_script["name_score"].describe())

print("\nNew transliterated name score:")
print(cross_script["name_score_translit"].describe())


print("\nScore >= thresholds")

for t in [50, 60, 70, 75, 80, 85, 90, 95]:

    old_count = (
        cross_script["name_score"] >= t
    ).sum()

    new_count = (
        cross_script["name_score_translit"] >= t
    ).sum()

    print(
        f"{t:>3} | "
        f"Old: {old_count:>8} | "
        f"New: {new_count:>8} | "
        f"Gain: {new_count-old_count:>8}"
    )

======================================================================
CROSS-SCRIPT NAME TRANSLITERATION IMPROVEMENT
======================================================================

Old name score:
count    261720.000000
mean         11.380514
std           7.950937
min           0.000000
25%           9.090909
50%          10.000000
75%          11.320755
max          95.384615
Name: name_score, dtype: float64

New transliterated name score:
count    261720.000000
mean         68.650388
std          13.326899
min           0.000000
25%          63.333333
50%          70.886076
75%          76.712329
max         100.000000
Name: name_score_translit, dtype: float64

Score >= thresholds
 50 | Old:     3711 | New:   246655 | Gain:   242944
 60 | Old:     2547 | New:   215002 | Gain:   212455
 70 | Old:     1838 | New:   141216 | Gain:   139378
 75 | Old:     1533 | New:    87164 | Gain:    85631
 80 | Old:     1141 | New:    38010 | Gain:    36869
 85 | Old:      561 | New:    10141 | Gain:     9580
 90 | Old:      164 | New:     2968 | Gain:     2804
 95 | Old:        1 | New:     1055 | Gain:     1054

In [129]:
cross_script["combined_score_translit"] = (
    0.60 * cross_script["name_score_translit"]
    + 0.40 * cross_script["address_score"]
)

In [130]:
cross_script_best = (
    cross_script
    .sort_values(
        "combined_score_translit",
        ascending=False
    )
)

display(
    cross_script_best[
        [
            "s1_name",
            "matched_name",
            "matched_name_latin",
            "s1_address",
            "matched_address",
            "name_score_translit",
            "address_score",
            "combined_score_translit"
        ]
    ].head(100)
)

,s1_name,matched_name,matched_name_latin,s1_address,matched_address,name_score_translit,address_score,combined_score_translit
167819,Vijay Management Private Limited,ವಿಜಯ್ Management Private Limited,vijay Management Private Limited,"Karnataka, No.119, Bangalore, Sri Puttanna Che...","Karnataka, NO.119, BANGALORE, SRI PUTTANNA CHE...",100.000000,100.000000,100.000000
438429,Global Engineering,ಗ್ಲೋಬಲ್ Engineering,global Engineering,"No 4, 1St Main 1St Block, R T Nagar, Bangalore...","NO 4, 1ST MAIN 1ST BLOCK, R T NAGAR, BANGALORE...",100.000000,100.000000,100.000000
618899,Tirupati Ventures Private Limited,तिरुपति Ventures Private Limited,tirupati Ventures Private Limited,"C/O Rajrani, Near Shiva Temple, Nawabganj, Bar...","C/O RAJRANI, NEAR SHIVA TEMPLE, NAWABGANJ, BAR...",100.000000,100.000000,100.000000
113538,Surya Builders Limited,सूर्या Builders Limited,sUryA Builders Limited,"Shiv Complex, Near Railway Station, Mainpuri, ...","SHIV COMPLEX, NEAR RAILWAY STATION, MAINPURI, ...",100.000000,100.000000,100.000000
108820,Baba Construction LLP,ਬਾਬਾ Construction LLP,bAbA Construction LLP,"179 Guru Nanak Colony, St No-02, Faridkot, Far...","179 GURU NANAK COLONY, ST NO-02, FARIDKOT, FAR...",100.000000,100.000000,100.000000
...,...,...,...,...,...,...,...,...
488679,Hotel Energy Pvt Ltd,হোটেল Energy Pvt Ltd,hoTela Energy Pvt Ltd,"Kamdevpur Delhi Roadsugandha, Hooghly, West Be...","KAMDEVPUR DELHI ROADSUGANDHA, HOOGHLY, West Be...",97.560976,100.000000,98.536585
552846,Red Global Private Limited,रेड Global Private Limited,reDa Global Private Limited,"1205, 12Th Floor, A-Building, Kumar Surabhi, S...","D/1205, 12TH FLOOR, A-BUILDING, KUMAR SURABHI,...",98.113208,99.019608,98.475768
442095,Best Infrastructure,बेस्ट Infrastructure,besTa Infrastructure,"Gangzala. Ward No.13, Saharsa Ps- Saharsa, Sah...","GANGZALA. WARD NO.13, SAHARSA PS- SAHARSA, SAH...",97.435897,100.000000,98.461538
609741,Great Modern Industries Private Limited,ग्रेट Modern Industries Private Limited,greTa Modern Industries Private Limited,"Flat No-692, Dda Flats Pocket-13, Phase-I Dwar...","FLAT NO-692, DDA FLATS POCKET-13, PHASE-I DWAR...",97.435897,100.000000,98.461538
612105,Gujarat Investments,गुजरात Investments,gujarAta Investments,"C06/01/1:3 Sector No 04 Cbd Belapur Washi, Nav...","C06/01/1:3 SECTOR NO 04 CBD BELAPUR WASHI, NAV...",97.435897,100.000000,98.461538

In [135]:
# ============================================================
# STEP 9 — ADD TRANSLITERATION SCORES TO TRUE CROSS-SCRIPT
# ============================================================

print("true_cross_script columns before:")
print(true_cross_script.columns.tolist())

print("\ncross_script columns:")
print(cross_script.columns.tolist())


# Get only the transliteration scores we already calculated
translit_scores = cross_script[
    [
        "source1_entity_id",
        "matched_entity_ids",
        "name_score_translit"
    ]
].copy()


# Remove any accidental duplicate pair rows
translit_scores = translit_scores.drop_duplicates(
    subset=["source1_entity_id", "matched_entity_ids"]
)


# Add transliteration score to true cross-script pairs
true_cross_script = true_cross_script.merge(
    translit_scores,
    on=["source1_entity_id", "matched_entity_ids"],
    how="left"
)


# Recalculate combined score
# Same weighting used earlier:
# 60% name + 40% address

true_cross_script["combined_score_translit"] = (
    0.60 * true_cross_script["name_score_translit"]
    + 0.40 * true_cross_script["address_score"]
)


print("\nAfter merge:")
print(true_cross_script.shape)

print("\nNew columns:")
print(
    true_cross_script[
        [
            "s1_name",
            "matched_name",
            "name_score_translit",
            "address_score",
            "combined_score_translit"
        ]
    ].head(20)
)

true_cross_script columns before:
['source1_entity_id', 'matched_entity_ids', 's1_block_key', 'matched_block_key', 'captured', 's1_name', 's1_address', 's1_country', 'matched_name', 'matched_address', 'matched_country', 'name_score', 'address_score', 'combined_score', 's1_script', 's2_script']

cross_script columns:
['source1_entity_id', 'matched_entity_ids', 's1_block_key', 'matched_block_key', 'captured', 's1_name', 's1_address', 's1_country', 'matched_name', 'matched_address', 'matched_country', 'name_s1_norm', 'name_s2_norm', 'address_s1_norm', 'address_s2_norm', 'name_score', 'address_score', 'combined_score', 's1_script', 's2_script', 'matched_name_latin', 's1_name_norm', 's2_name_latin_norm', 'name_score_translit', 'combined_score_translit']

After merge:
(344641, 18)

New columns:
                              s1_name  \
0                 Raj Investments LLP
1             Ss Food Private Limited
2             Ss Food Private Limited
3        Red Ventures Private Limited
4           Hotel Enterprises Limited
5   Balaji Investment Private Limited
6            Swastik Om Solutions LLP
7            Swastik Om Solutions LLP
8                       New Solutions
9                       New Solutions
10  Ram Maa Logistics Private Limited
11               Sun Software Limited
12             Guru Solutions Pvt Ltd
13     Jain Marketing Private Limited
14              Gold Projects Pvt Ltd
15              Gold Projects Pvt Ltd
16              Gold Projects Pvt Ltd
17                 Red Global Limited
18       South Estate Private Limited
19                  Swastik Marketing

                                matched_name  name_score_translit  \
0            ராஜ் இன்வெஸ்ட்மெண்ட்ஸ் எல்எல்பி                  NaN
1                  एसएस फूड प्राइवेट लिमिटेड                  NaN
2                  एसएस फूड प्राइवेट लिमिटेड                  NaN
3               रेड वेंचर्स प्राइवेट लिमिटेड                  NaN
4                  होटल एंटरप्राइजेज लिमिटेड                  NaN
5   బాలాజీ ఇన్వెస్ట్‌మెంట్ ప్రైవేట్ లిమిటెడ్                  NaN
6                स्वस्तिक ॐ सॉल्यूशंस एलएलपी                  NaN
7                स्वस्तिक ॐ सॉल्यूशंस एलएलपी                  NaN
8                             न्यू सॉल्यूशंस                  NaN
9                             न्यू सॉल्यूशंस                  NaN
10      राम मां लॉजिस्टिक्स प्राइवेट लिमिटेड                  NaN
11                      सन सॉफ्टवेयर लिमिटेड                  NaN
12        ಗುರು ಸೊಲ್ಯೂಷನ್ಸ್ ಪ್ರೈವೇಟ್ ಲಿಮಿಟೆಡ್                  NaN
13           जैन मार्केटिंग प्राइवेट लिमिटेड                  NaN
14     ಗೋಲ್ಡ್ ಪ್ರಾಜೆಕ್ಟ್ಸ್ ಪ್ರೈವೇಟ್ ಲಿಮಿಟೆಡ್                  NaN
15     ಗೋಲ್ಡ್ ಪ್ರಾಜೆಕ್ಟ್ಸ್ ಪ್ರೈವೇಟ್ ಲಿಮಿಟೆಡ್                  NaN
16     ಗೋಲ್ಡ್ ಪ್ರಾಜೆಕ್ಟ್ಸ್ ಪ್ರೈವೇಟ್ ಲಿಮಿಟೆಡ್                  NaN
17                       রেড গ্লোবাল লিমিটেড                  NaN
18              साउथ एस्टेट प्राइवेट लिमिटेड                  NaN
19                       स्वस्तिक मार्केटिंग                  NaN

    address_score  combined_score_translit
0      100.000000                      NaN
1       81.761006                      NaN
2       32.000000                      NaN
3       38.775510                      NaN
4       56.551724                      NaN
5       53.913043                      NaN
6       69.306931                      NaN
7       93.750000                      NaN
8       79.661017                      NaN
9       79.661017                      NaN
10      46.017699                      NaN
11     100.000000                      NaN
12      98.076923                      NaN
13      70.769231                      NaN
14      93.805310                      NaN
15      93.805310                      NaN
16      65.740741                      NaN
17      56.488550                      NaN
18     100.000000                      NaN
19      83.760684                      NaN

In [136]:
print(
    "Missing transliteration scores:",
    true_cross_script["name_score_translit"].isna().sum()
)

print(
    "Missing combined scores:",
    true_cross_script["combined_score_translit"].isna().sum()
)

Missing transliteration scores: 82921
Missing combined scores: 82921

In [138]:
true_cross_script["matched_name_latin"] = (
    true_cross_script["matched_name"]
    .fillna("")
    .apply(transliterate_name)
)

In [139]:
# STEP 11: Recalculate missing cross-script transliteration scores
# ---------------------------------------------------------------

# Work only on rows where transliteration score is missing
missing_mask = cross_script["name_score_translit"].isna()

print("Missing transliteration scores before:", missing_mask.sum())

cross_script.loc[missing_mask, "matched_name_latin"] = (
    cross_script.loc[missing_mask, "matched_name"]
    .fillna("")
    .apply(transliterate_name)
)

# Normalize both names before scoring
cross_script.loc[missing_mask, "s1_name_norm"] = (
    cross_script.loc[missing_mask, "s1_name"]
    .fillna("")
    .astype(str)
    .str.lower()
    .str.strip()
)

cross_script.loc[missing_mask, "s2_name_latin_norm"] = (
    cross_script.loc[missing_mask, "matched_name_latin"]
    .fillna("")
    .astype(str)
    .str.lower()
    .str.strip()
)

# Recalculate name score
cross_script.loc[missing_mask, "name_score_translit"] = (
    cross_script.loc[missing_mask]
    .apply(
        lambda row: ratio(
            row["s1_name_norm"],
            row["s2_name_latin_norm"]
        ),
        axis=1
    )
)

# Recalculate combined score
cross_script.loc[missing_mask, "combined_score_translit"] = (
    0.6 * cross_script.loc[missing_mask, "name_score_translit"]
    + 0.4 * cross_script.loc[missing_mask, "address_score"]
)

print("Missing transliteration scores after:",
      cross_script["name_score_translit"].isna().sum())

print("Missing combined scores after:",
      cross_script["combined_score_translit"].isna().sum())

Missing transliteration scores before: 0
Missing transliteration scores after: 0
Missing combined scores after: 0

In [140]:
print("Cross-script shape:", cross_script.shape)

print("\nScore statistics:")
print(
    cross_script[
        [
            "name_score_translit",
            "address_score",
            "combined_score_translit"
        ]
    ].describe()
)

print("\nMissing values:")
print(
    cross_script[
        [
            "matched_name_latin",
            "name_score_translit",
            "combined_score_translit"
        ]
    ].isna().sum()
)

Cross-script shape: (261720, 25)

Score statistics:
       name_score_translit  address_score  combined_score_translit
count        261720.000000  261720.000000            261720.000000
mean             68.650388      74.816863                71.116978
std              13.326899      20.151044                11.339909
min               0.000000       0.000000                 8.571429
25%              63.333333      59.060403                64.310345
50%              70.886076      78.378378                72.313842
75%              76.712329      92.500000                79.473684
max             100.000000     100.000000               100.000000

Missing values:
matched_name_latin         0
name_score_translit        0
combined_score_translit    0
dtype: int64

In [141]:
print("Missing transliteration scores after:",
      cross_script["name_score_translit"].isna().sum())

print("Missing combined scores after:",
      cross_script["combined_score_translit"].isna().sum())

Missing transliteration scores after: 0
Missing combined scores after: 0

In [142]:
# STEP 12: Update true cross-script pairs with transliteration scores
# ------------------------------------------------------------------

score_cols = [
    "source1_entity_id",
    "matched_entity_ids",
    "name_score_translit",
    "combined_score_translit"
]

true_cross_script = true_cross_script.drop(
    columns=["name_score_translit", "combined_score_translit"],
    errors="ignore"
)

true_cross_script = true_cross_script.merge(
    cross_script[score_cols],
    on=["source1_entity_id", "matched_entity_ids"],
    how="left"
)

print("Shape:", true_cross_script.shape)

print("\nColumns:")
print(true_cross_script.columns.tolist())

print("\nMissing scores:")
print(
    true_cross_script[
        ["name_score_translit", "combined_score_translit"]
    ].isna().sum()
)

Shape: (344641, 19)

Columns:
['source1_entity_id', 'matched_entity_ids', 's1_block_key', 'matched_block_key', 'captured', 's1_name', 's1_address', 's1_country', 'matched_name', 'matched_address', 'matched_country', 'name_score', 'address_score', 'combined_score', 's1_script', 's2_script', 'matched_name_latin', 'name_score_translit', 'combined_score_translit']

Missing scores:
name_score_translit        82921
combined_score_translit    82921
dtype: int64

In [143]:
print("=" * 70)
print("TRUE CROSS-SCRIPT — TRANSLITERATED SCORE DISTRIBUTION")
print("=" * 70)

print(
    true_cross_script[
        [
            "name_score_translit",
            "address_score",
            "combined_score_translit"
        ]
    ].describe()
)

======================================================================
TRUE CROSS-SCRIPT — TRANSLITERATED SCORE DISTRIBUTION
======================================================================
       name_score_translit  address_score  combined_score_translit
count        261720.000000  344641.000000            261720.000000
mean             68.650388      74.924692                71.116978
std              13.326899      21.273499                11.339909
min               0.000000       0.000000                 8.571429
25%              63.333333      58.974359                64.310345
50%              70.886076      80.000000                72.313842
75%              76.712329      93.333333                79.473684
max             100.000000     100.000000               100.000000

In [144]:
# STEP 14: Threshold analysis after transliteration
# --------------------------------------------------

total_true = len(true_cross_script)

thresholds = [50, 60, 70, 75, 80, 85, 90, 92, 94, 95, 96, 97, 98]

print("=" * 80)
print("CROSS-SCRIPT TRANSLITERATION THRESHOLD ANALYSIS")
print("=" * 80)

print(
    f"{'Threshold':<12}"
    f"{'True Captured':<18}"
    f"{'True Recall %':<18}"
)

print("-" * 50)

for t in thresholds:

    captured = (
        true_cross_script["combined_score_translit"] >= t
    ).sum()

    recall = captured / total_true * 100

    print(
        f"{t:<12}"
        f"{captured:<18}"
        f"{recall:<18.2f}"
    )

================================================================================
CROSS-SCRIPT TRANSLITERATION THRESHOLD ANALYSIS
================================================================================
Threshold   True Captured     True Recall %
--------------------------------------------------
50          252013            73.12
60          222624            64.60
70          151378            43.92
75          106570            30.92
80          61572             17.87
85          22059             6.40
90          3542              1.03
92          1509              0.44
94          714               0.21
95          478               0.14
96          334               0.10
97          214               0.06
98          133               0.04

In [145]:
# STEP 15: Score ALL true cross-script pairs
# -------------------------------------------

true_cross_script["matched_name_latin"] = (
    true_cross_script["matched_name"]
    .fillna("")
    .apply(transliterate_name)
)

true_cross_script["s1_name_norm"] = (
    true_cross_script["s1_name"]
    .fillna("")
    .astype(str)
    .str.lower()
    .str.strip()
)

true_cross_script["matched_name_latin_norm"] = (
    true_cross_script["matched_name_latin"]
    .fillna("")
    .astype(str)
    .str.lower()
    .str.strip()
)

true_cross_script["name_score_translit"] = (
    true_cross_script.apply(
        lambda row: ratio(
            row["s1_name_norm"],
            row["matched_name_latin_norm"]
        ),
        axis=1
    )
)

true_cross_script["combined_score_translit"] = (
    0.6 * true_cross_script["name_score_translit"]
    + 0.4 * true_cross_script["address_score"]
)

print("Shape:", true_cross_script.shape)

print("\nMissing scores:")
print(
    true_cross_script[
        ["name_score_translit", "combined_score_translit"]
    ].isna().sum()
)

Shape: (344641, 21)

Missing scores:
name_score_translit        0
combined_score_translit    0
dtype: int64

In [146]:
print(
    true_cross_script[
        [
            "name_score_translit",
            "address_score",
            "combined_score_translit"
        ]
    ].describe()
)

       name_score_translit  address_score  combined_score_translit
count        344641.000000  344641.000000            344641.000000
mean             68.692936      74.924692                71.185638
std              12.938073      21.273499                11.567723
min               0.000000       0.000000                12.857143
25%              62.857143      58.974359                63.950311
50%              70.833333      80.000000                72.521515
75%              76.923077      93.333333                79.984556
max             100.000000     100.000000               100.000000

In [147]:
thresholds = [50, 60, 70, 75, 80, 85, 90, 92, 94, 95, 96, 97, 98]

total_true = len(true_cross_script)

print("=" * 80)
print("CROSS-SCRIPT TRANSLITERATION THRESHOLD ANALYSIS")
print("=" * 80)

print(
    f"{'Threshold':<12}"
    f"{'True Captured':<18}"
    f"{'True Recall %':<18}"
)

print("-" * 50)

for t in thresholds:

    captured = (
        true_cross_script["combined_score_translit"] >= t
    ).sum()

    recall = captured / total_true * 100

    print(
        f"{t:<12}"
        f"{captured:<18}"
        f"{recall:<18.2f}"
    )

================================================================================
CROSS-SCRIPT TRANSLITERATION THRESHOLD ANALYSIS
================================================================================
Threshold   True Captured     True Recall %
--------------------------------------------------
50          329238            95.53
60          288486            83.71
70          200185            58.09
75          144200            41.84
80          86105             24.98
85          32572             9.45
90          6249              1.81
92          2938              0.85
94          1377              0.40
95          874               0.25
96          577               0.17
97          365               0.11
98          207               0.06

In [148]:
# STEP 18: Transliterate and score all cross-script candidates
# ------------------------------------------------------------

cross_script["matched_name_latin"] = (
    cross_script["matched_name"]
    .fillna("")
    .apply(transliterate_name)
)

cross_script["s1_name_norm"] = (
    cross_script["s1_name"]
    .fillna("")
    .astype(str)
    .str.lower()
    .str.strip()
)

cross_script["matched_name_latin_norm"] = (
    cross_script["matched_name_latin"]
    .fillna("")
    .astype(str)
    .str.lower()
    .str.strip()
)

cross_script["name_score_translit"] = (
    cross_script.apply(
        lambda row: ratio(
            row["s1_name_norm"],
            row["matched_name_latin_norm"]
        ),
        axis=1
    )
)

cross_script["combined_score_translit"] = (
    0.6 * cross_script["name_score_translit"]
    + 0.4 * cross_script["address_score"]
)

print("Shape:", cross_script.shape)

print("\nMissing scores:")
print(
    cross_script[
        ["name_score_translit", "combined_score_translit"]
    ].isna().sum()
)

Shape: (261720, 26)

Missing scores:
name_score_translit        0
combined_score_translit    0
dtype: int64

In [149]:
print(
    cross_script[
        [
            "name_score_translit",
            "address_score",
            "combined_score_translit"
        ]
    ].describe()
)

       name_score_translit  address_score  combined_score_translit
count        261720.000000  261720.000000            261720.000000
mean             68.437306      74.816863                70.989129
std              12.823218      20.151044                11.128637
min               0.000000       0.000000                14.948898
25%              62.686567      59.060403                64.048318
50%              70.588235      78.378378                72.067355
75%              76.666667      92.500000                79.344262
max             100.000000     100.000000               100.000000

In [150]:
# STEP 19: Compare true vs candidate cross-script scores
# ------------------------------------------------------

thresholds = [50, 60, 70, 75, 80, 85, 90, 92, 94, 95, 96, 97, 98]

total_true = len(true_cross_script)
total_candidates = len(cross_script)

print("=" * 100)
print("CROSS-SCRIPT TRUE vs CANDIDATE THRESHOLD ANALYSIS")
print("=" * 100)

print(
    f"{'Threshold':<12}"
    f"{'True Captured':<18}"
    f"{'True Recall %':<18}"
    f"{'Candidates Passing':<22}"
    f"{'Candidate %':<15}"
)

print("-" * 100)

for t in thresholds:

    true_captured = (
        true_cross_script["combined_score_translit"] >= t
    ).sum()

    candidates_passing = (
        cross_script["combined_score_translit"] >= t
    ).sum()

    true_recall = true_captured / total_true * 100
    candidate_pct = candidates_passing / total_candidates * 100

    print(
        f"{t:<12}"
        f"{true_captured:<18}"
        f"{true_recall:<18.2f}"
        f"{candidates_passing:<22}"
        f"{candidate_pct:<15.2f}"
    )

====================================================================================================
CROSS-SCRIPT TRUE vs CANDIDATE THRESHOLD ANALYSIS
====================================================================================================
Threshold   True Captured     True Recall %     Candidates Passing    Candidate %
----------------------------------------------------------------------------------------------------
50          329238            95.53             251421                96.06
60          288486            83.71             221172                84.51
70          200185            58.09             149183                57.00
75          144200            41.84             104591                39.96
80          86105             24.98             60397                 23.08
85          32572             9.45              21675                 8.28
90          6249              1.81              3505                  1.34
92          2938              0.85              1495                  0.57
94          1377              0.40              702                   0.27
95          874               0.25              469                   0.18
96          577               0.17              330                   0.13
97          365               0.11              211                   0.08
98          207               0.06              130                   0.05

In [151]:
# STEP 20: Inspect strongest cross-script candidates
# --------------------------------------------------

cols = [
    "source1_entity_id",
    "matched_entity_ids",
    "s1_name",
    "matched_name",
    "matched_name_latin",
    "s1_address",
    "matched_address",
    "name_score_translit",
    "address_score",
    "combined_score_translit"
]

display(
    cross_script
    .sort_values("combined_score_translit", ascending=False)
    [cols]
    .head(100)
)

,source1_entity_id,matched_entity_ids,s1_name,matched_name,matched_name_latin,s1_address,matched_address,name_score_translit,address_score,combined_score_translit
291405,S1-147882651,S2-67009607,Jain Energy Private Limited,జైన్ Energy Private Limited,jain Energy Private Limited,"6-21/1/1, Kukatpally Y Junction Moosapet, Hyde...","6-21/1/1, KUKATPALLY Y JUNCTION MOOSAPET, HYDE...",100.000000,100.000000,100.000000
219215,S1-670295316,S2-869031009,Surya Guru Trading Private Limited,సూర్య Guru Trading Private Limited,sUrya Guru Trading Private Limited,"Flat No 502, Kaizenresidency, Hig 13 & 14 Kphb...","FLAT NO 502, KAIZENRESIDENCY, HIG 13 & 14 KPHB...",100.000000,100.000000,100.000000
625263,S1-436440403,S2-995045138,Shiva Trading,शिवा Trading,shivA Trading,"Du- 176 Pitampura, Delhi, North West, Delhi","DU- 176 PITAMPURA, DELHI, NORTH WEST, Delhi",100.000000,100.000000,100.000000
57743,S1-136489621,S2-343737045,Shiva Foundation Private Limited,शिवा Foundation Private Limited,shivA Foundation Private Limited,"Sr No 32/13/1, Row House 101, Sai Shraddha Bun...","SR NO 32/13/1, ROW HOUSE 101, SAI SHRADDHA BUN...",100.000000,100.000000,100.000000
56643,S1-551643922,S2-10097846,Alpha Agro,આલ્ફા Agro,AlphA Agro,"Office No 121, 1St Floor, Sahajanand Luxuria, ...","OFFICE NO 121, 1ST FLOOR, SAHAJANAND LUXURIA, ...",100.000000,100.000000,100.000000
...,...,...,...,...,...,...,...,...,...,...
609741,S1-789731765,S2-506218604,Great Modern Industries Private Limited,ग्रेट Modern Industries Private Limited,greTa Modern Industries Private Limited,"Flat No-692, Dda Flats Pocket-13, Phase-I Dwar...","FLAT NO-692, DDA FLATS POCKET-13, PHASE-I DWAR...",97.435897,100.000000,98.461538
442095,S1-717148219,S2-189611704,Best Infrastructure,बेस्ट Infrastructure,besTa Infrastructure,"Gangzala. Ward No.13, Saharsa Ps- Saharsa, Sah...","GANGZALA. WARD NO.13, SAHARSA PS- SAHARSA, SAH...",97.435897,100.000000,98.461538
612105,S1-611180125,S2-105583678,Gujarat Investments,गुजरात Investments,gujarAta Investments,"C06/01/1:3 Sector No 04 Cbd Belapur Washi, Nav...","C06/01/1:3 SECTOR NO 04 CBD BELAPUR WASHI, NAV...",97.435897,100.000000,98.461538
539077,S1-202953391,S2-654210712,Gujarat Consultancy,गुजरात Consultancy,gujarAta Consultancy,"12/132 Geeta Colony Gandhi Nagar, Delhi, East ...","#12/132 GEETA COLONY GANDHI NAGAR, DELHI, EAST...",97.435897,100.000000,98.461538
110664,S1-78918948,S2-122464387,Jay Infrastructure Limited,जय Infrastructure Limited,jaya Infrastructure Limited,"A/402, Swapnadeep Co Op H Soc, Swapna Nagari, ...","A/402/4, SWAPNADEEP CO OP H SOC, SWAPNA NAGARI...",98.113208,98.947368,98.446872

In [152]:
display(
    cross_script[
        (cross_script["combined_score_translit"] >= 70) &
        (cross_script["combined_score_translit"] < 80)
    ]
    .sort_values("combined_score_translit", ascending=False)
    [cols]
    .head(100)
)

,source1_entity_id,matched_entity_ids,s1_name,matched_name,matched_name_latin,s1_address,matched_address,name_score_translit,address_score,combined_score_translit
555797,S1-855716763,S2-236482785,Supreme Projects Private Limited,सुप्रीम प्रोजेक्ट्स प्राइवेट लिमिटेड,suprIma projekTsa prAiveTa limiTeDa,"Pali Agolpurkadipur Dostpur Road Sultanpur, Ut...",DOOR NO 3-710 PALI AGOLPURKADIPUR DOSTPUR ROAD...,80.597015,79.096045,79.996627
178330,S1-205226738,S2-374065691,Surya Logistics Private Limited,সূর্য লজিস্টিকস প্রাইভেট লিমিটেড,sUrya lajisTikasa prAibheTa limiTeDa,"Elegant Towers 224A, Acharya Jagdish Chandra B...","ELEGANT TOWERS 224A, ACHARYA JAGDISH CHANDRA B...",74.626866,88.050314,79.996245
338222,S1-277063950,S2-90469192,Shyam Developers LLP,શ્યામ ડેવલપર્સ એલએલપી,shyAma Devalaparsa elaelapI,"Plot No. 96, 97 And 98, Rs. No. 40/1 P 1, Gold...","DOOR NO 96, 97 AND 98, RS. NO. 40/1 P 1, GOLDE...",72.340426,91.479821,79.996184
506912,S1-244499461,S2-680484552,Universal Estate Private Limited,ಯುನಿವರ್ಸಲ್ ಎಸ್ಟೇಟ್ ಪ್ರೈವೇಟ್ ಲಿಮಿಟೆಡ್,yunivarsal èsTeT praiveT limiTèD,"202, 2Nd Floor, Naya Gruha Apts Rachenahalli, ...","Karnataka, 2ND FLOOR, NAYA GRUHA APTS RACHENAH...",78.125000,82.802548,79.996019
31094,S1-517331417,S2-242193420,Al Impex Private Limited,अल इम्पेक्स प्राइवेट लिमिटेड,ala impeksa prAiveTa limiTeDa,"2Nd Floor Above Max Mart Akharaghat Road, Muza...",DOOR NO 2ND FLOOR ABOVE MAX MART AKHARAGHAT RO...,79.245283,81.118881,79.994722
...,...,...,...,...,...,...,...,...,...,...
61925,S1-960564491,S2-512855322,Smart Care Private Limited,स्मार्ट केयर प्राइवेट लिमिटेड,smArTa keyara prAiveTa limiTeDa,"602 Wing A Jangid Heights Chsl, Nr Vidyapeeth ...","H.NO 602 WING A JANGID HEIGHTS CHSL, NR VIDYAP...",77.192982,84.146341,79.974326
95755,S1-545169300,S2-121502087,Premier Management Private Limited,प्रीमियर मैनेजमेंट प्राइवेट लिमिटेड,prImiyara mainejameMTa prAiveTa limiTeDa,"165-D Aravali Apartments, Sector -56, Noida, G...","165-D ARAVALI APARTMENTS, GAUTAM BUDH NAGAR, G...",72.972973,90.476190,79.974260
200833,S1-50383319,S2-620174825,Tirupati Logistics Private Limited,ਤਿਰੂਪਤੀ ਲੌਜਿਸਟਿਕਸ ਪ੍ਰਾਈਵੇਟ ਲਿਮਟਿਡ,tirUpatI laujisaTikasa prAIveTa limaTiDa,"Muktsar, Punjab, 1281 K. Thande Wala Road, Muk...","MUKTSAR, #1281 K. THANDE WALA ROAD, Punjab, B ...",72.972973,90.476190,79.974260
543431,S1-857548759,S2-696412183,Surya Media Private Limited,सूर्य मीडिया प्राइवेट लिमिटेड,sUrya mIDiyA prAiveTa limiTeDa,"Delhi, East Delhi, 3Rd Floor, Plot No.76 & 77,...","OFFICE NO.301, 3RD FLOOR, PLOT NO.76 & 77, KH ...",84.210526,73.619632,79.974169
543432,S1-857548759,S2-723850143,Surya Media Private Limited,सूर्या मीडिया प्राइवेट लिमिटेड,sUryA mIDiyA prAiveTa limiTeDa,"Delhi, East Delhi, 3Rd Floor, Plot No.76 & 77,...","OFFICE NO.301, 3RD FLOOR, PLOT NO.76 & 77, KH ...",84.210526,73.619632,79.974169

In [153]:
# ============================================================
# STEP 21: HIGH-CONFIDENCE CROSS-SCRIPT MATCH INSPECTION
# ============================================================

THRESHOLD = 80

high_conf_cross = cross_script[
    cross_script["combined_score_translit"] >= THRESHOLD
].copy()

print("=" * 100)
print(f"CROSS-SCRIPT HIGH-CONFIDENCE MATCHES — SCORE >= {THRESHOLD}")
print("=" * 100)

print("Shape:", high_conf_cross.shape)

print("\nScore statistics:")
print(
    high_conf_cross[
        [
            "name_score_translit",
            "address_score",
            "combined_score_translit"
        ]
    ].describe()
)

# Display the most convincing matches
display(
    high_conf_cross[
        [
            "source1_entity_id",
            "matched_entity_ids",
            "s1_name",
            "matched_name",
            "matched_name_latin",
            "s1_address",
            "matched_address",
            "name_score_translit",
            "address_score",
            "combined_score_translit"
        ]
    ]
    .sort_values("combined_score_translit", ascending=False)
    .head(100)
)

====================================================================================================
CROSS-SCRIPT HIGH-CONFIDENCE MATCHES — SCORE >= 80
====================================================================================================
Shape: (60397, 26)

Score statistics:
       name_score_translit  address_score  combined_score_translit
count         60397.000000   60397.000000             60397.000000
mean             77.766204      94.004471                84.261510
std               6.079962       7.119952                 3.256511
min              66.666667      50.000000                80.000000
25%              73.469388      90.058480                81.683453
50%              77.419355      96.428571                83.636364
75%              81.355932     100.000000                86.153846
max             100.000000     100.000000               100.000000

,source1_entity_id,matched_entity_ids,s1_name,matched_name,matched_name_latin,s1_address,matched_address,name_score_translit,address_score,combined_score_translit
349257,S1-317518698,S2-603572544,Tirupati Marketing Private Limited,तिरुपति Marketing Private Limited,tirupati Marketing Private Limited,"3-4, 'Aishwarya Sankul', S. No. 17, G. A. Kulk...","3-4, 'AISHWARYA SANKUL', S. NO. 17, G. A. KULK...",100.000000,100.000000,100.000000
304685,S1-124302163,S2-379692379,Shakti Builders Private Limited,शक्ति Builders Private Limited,shakti Builders Private Limited,"C-5 Maharani Bagh, New Delhi, South Delhi, Delhi","C-5 MAHARANI BAGH, NEW DELHI, SOUTH DELHI, Delhi",100.000000,100.000000,100.000000
401029,S1-160667531,S2-715261542,Surya Sree Solutions Limited,सूर्या Sree Solutions Limited,sUryA Sree Solutions Limited,F No 403 M/S Aryadurga Bankar Enterprises Mulu...,F NO 403 M/S ARYADURGA BANKAR ENTERPRISES MULU...,100.000000,100.000000,100.000000
47179,S1-999303555,S2-67942461,Guru Foundation Limited,ಗುರು Foundation Limited,guru Foundation Limited,"No.24, Saberi Complex, Residency Road, Bangalo...","NO.24, SABERI COMPLEX, RESIDENCY ROAD, BANGALO...",100.000000,100.000000,100.000000
326213,S1-327871566,S2-727527025,Surya Infotech Pvt Ltd,সূর্য Infotech Pvt Ltd,sUrya Infotech Pvt Ltd,"5, Puran Chand Nahar Avenue, Kolkata, Kolkata,...","5, PURAN CHAND NAHAR AVENUE, KOLKATA, KOLKATA,...",100.000000,100.000000,100.000000
...,...,...,...,...,...,...,...,...,...,...
442095,S1-717148219,S2-189611704,Best Infrastructure,बेस्ट Infrastructure,besTa Infrastructure,"Gangzala. Ward No.13, Saharsa Ps- Saharsa, Sah...","GANGZALA. WARD NO.13, SAHARSA PS- SAHARSA, SAH...",97.435897,100.000000,98.461538
612105,S1-611180125,S2-105583678,Gujarat Investments,गुजरात Investments,gujarAta Investments,"C06/01/1:3 Sector No 04 Cbd Belapur Washi, Nav...","C06/01/1:3 SECTOR NO 04 CBD BELAPUR WASHI, NAV...",97.435897,100.000000,98.461538
539077,S1-202953391,S2-654210712,Gujarat Consultancy,गुजरात Consultancy,gujarAta Consultancy,"12/132 Geeta Colony Gandhi Nagar, Delhi, East ...","#12/132 GEETA COLONY GANDHI NAGAR, DELHI, EAST...",97.435897,100.000000,98.461538
609741,S1-789731765,S2-506218604,Great Modern Industries Private Limited,ग्रेट Modern Industries Private Limited,greTa Modern Industries Private Limited,"Flat No-692, Dda Flats Pocket-13, Phase-I Dwar...","FLAT NO-692, DDA FLATS POCKET-13, PHASE-I DWAR...",97.435897,100.000000,98.461538
110664,S1-78918948,S2-122464387,Jay Infrastructure Limited,जय Infrastructure Limited,jaya Infrastructure Limited,"A/402, Swapnadeep Co Op H Soc, Swapna Nagari, ...","A/402/4, SWAPNADEEP CO OP H SOC, SWAPNA NAGARI...",98.113208,98.947368,98.446872

In [154]:
# ============================================================
# STEP 22: BORDERLINE MATCH INSPECTION
# ============================================================

borderline_cross = cross_script[
    (cross_script["combined_score_translit"] >= 70) &
    (cross_script["combined_score_translit"] < 80)
].copy()

print("=" * 100)
print("CROSS-SCRIPT BORDERLINE MATCHES — 70 <= SCORE < 80")
print("=" * 100)

print("Shape:", borderline_cross.shape)

display(
    borderline_cross[
        [
            "source1_entity_id",
            "matched_entity_ids",
            "s1_name",
            "matched_name",
            "matched_name_latin",
            "s1_address",
            "matched_address",
            "name_score_translit",
            "address_score",
            "combined_score_translit"
        ]
    ]
    .sort_values("combined_score_translit", ascending=False)
    .head(100)
)

====================================================================================================
CROSS-SCRIPT BORDERLINE MATCHES — 70 <= SCORE < 80
====================================================================================================
Shape: (88786, 26)

,source1_entity_id,matched_entity_ids,s1_name,matched_name,matched_name_latin,s1_address,matched_address,name_score_translit,address_score,combined_score_translit
555797,S1-855716763,S2-236482785,Supreme Projects Private Limited,सुप्रीम प्रोजेक्ट्स प्राइवेट लिमिटेड,suprIma projekTsa prAiveTa limiTeDa,"Pali Agolpurkadipur Dostpur Road Sultanpur, Ut...",DOOR NO 3-710 PALI AGOLPURKADIPUR DOSTPUR ROAD...,80.597015,79.096045,79.996627
178330,S1-205226738,S2-374065691,Surya Logistics Private Limited,সূর্য লজিস্টিকস প্রাইভেট লিমিটেড,sUrya lajisTikasa prAibheTa limiTeDa,"Elegant Towers 224A, Acharya Jagdish Chandra B...","ELEGANT TOWERS 224A, ACHARYA JAGDISH CHANDRA B...",74.626866,88.050314,79.996245
338222,S1-277063950,S2-90469192,Shyam Developers LLP,શ્યામ ડેવલપર્સ એલએલપી,shyAma Devalaparsa elaelapI,"Plot No. 96, 97 And 98, Rs. No. 40/1 P 1, Gold...","DOOR NO 96, 97 AND 98, RS. NO. 40/1 P 1, GOLDE...",72.340426,91.479821,79.996184
506912,S1-244499461,S2-680484552,Universal Estate Private Limited,ಯುನಿವರ್ಸಲ್ ಎಸ್ಟೇಟ್ ಪ್ರೈವೇಟ್ ಲಿಮಿಟೆಡ್,yunivarsal èsTeT praiveT limiTèD,"202, 2Nd Floor, Naya Gruha Apts Rachenahalli, ...","Karnataka, 2ND FLOOR, NAYA GRUHA APTS RACHENAH...",78.125000,82.802548,79.996019
31094,S1-517331417,S2-242193420,Al Impex Private Limited,अल इम्पेक्स प्राइवेट लिमिटेड,ala impeksa prAiveTa limiTeDa,"2Nd Floor Above Max Mart Akharaghat Road, Muza...",DOOR NO 2ND FLOOR ABOVE MAX MART AKHARAGHAT RO...,79.245283,81.118881,79.994722
...,...,...,...,...,...,...,...,...,...,...
61925,S1-960564491,S2-512855322,Smart Care Private Limited,स्मार्ट केयर प्राइवेट लिमिटेड,smArTa keyara prAiveTa limiTeDa,"602 Wing A Jangid Heights Chsl, Nr Vidyapeeth ...","H.NO 602 WING A JANGID HEIGHTS CHSL, NR VIDYAP...",77.192982,84.146341,79.974326
95755,S1-545169300,S2-121502087,Premier Management Private Limited,प्रीमियर मैनेजमेंट प्राइवेट लिमिटेड,prImiyara mainejameMTa prAiveTa limiTeDa,"165-D Aravali Apartments, Sector -56, Noida, G...","165-D ARAVALI APARTMENTS, GAUTAM BUDH NAGAR, G...",72.972973,90.476190,79.974260
200833,S1-50383319,S2-620174825,Tirupati Logistics Private Limited,ਤਿਰੂਪਤੀ ਲੌਜਿਸਟਿਕਸ ਪ੍ਰਾਈਵੇਟ ਲਿਮਟਿਡ,tirUpatI laujisaTikasa prAIveTa limaTiDa,"Muktsar, Punjab, 1281 K. Thande Wala Road, Muk...","MUKTSAR, #1281 K. THANDE WALA ROAD, Punjab, B ...",72.972973,90.476190,79.974260
543431,S1-857548759,S2-696412183,Surya Media Private Limited,सूर्य मीडिया प्राइवेट लिमिटेड,sUrya mIDiyA prAiveTa limiTeDa,"Delhi, East Delhi, 3Rd Floor, Plot No.76 & 77,...","OFFICE NO.301, 3RD FLOOR, PLOT NO.76 & 77, KH ...",84.210526,73.619632,79.974169
543432,S1-857548759,S2-723850143,Surya Media Private Limited,सूर्या मीडिया प्राइवेट लिमिटेड,sUryA mIDiyA prAiveTa limiTeDa,"Delhi, East Delhi, 3Rd Floor, Plot No.76 & 77,...","OFFICE NO.301, 3RD FLOOR, PLOT NO.76 & 77, KH ...",84.210526,73.619632,79.974169

In [155]:
# ============================================================
# STEP 23: CROSS-SCRIPT SCORE BAND ANALYSIS
# ============================================================

import pandas as pd

score_col = "combined_score_translit"

bins = [0, 50, 60, 70, 75, 80, 85, 90, 95, 100.000001]
labels = [
    "<50",
    "50-60",
    "60-70",
    "70-75",
    "75-80",
    "80-85",
    "85-90",
    "90-95",
    "95-100"
]

# ------------------------------------------------------------
# Candidate distribution
# ------------------------------------------------------------

candidate_bands = pd.cut(
    cross_script[score_col],
    bins=bins,
    labels=labels,
    right=False,
    include_lowest=True
)

candidate_counts = candidate_bands.value_counts(
    sort=False
)

# ------------------------------------------------------------
# True-pair distribution
# ------------------------------------------------------------

true_bands = pd.cut(
    true_cross_script[score_col],
    bins=bins,
    labels=labels,
    right=False,
    include_lowest=True
)

true_counts = true_bands.value_counts(
    sort=False
)

# ------------------------------------------------------------
# Combine
# ------------------------------------------------------------

band_analysis = pd.DataFrame({
    "Score Band": labels,
    "Candidates": candidate_counts.values,
    "True Pairs": true_counts.values
})

band_analysis["Candidate %"] = (
    band_analysis["Candidates"] /
    len(cross_script) * 100
)

band_analysis["True %"] = (
    band_analysis["True Pairs"] /
    len(true_cross_script) * 100
)

print("=" * 100)
print("CROSS-SCRIPT SCORE BAND ANALYSIS")
print("=" * 100)

display(band_analysis)

====================================================================================================
CROSS-SCRIPT SCORE BAND ANALYSIS
====================================================================================================

  Score Band  Candidates  True Pairs  Candidate %     True %
0        <50       10299       15403     3.935122   4.469288
1      50-60       30249       40752    11.557772  11.824478
2      60-70       71989       88301    27.506113  25.621154
3      70-75       44592       55985    17.038056  16.244440
4      75-80       44194       58095    16.885985  16.856671
5      80-85       38722       53533    14.795201  15.532975
6      85-90       18170       26323     6.942534   7.637803
7      90-95        3036        5375     1.160018   1.559594
8     95-100         469         874     0.179199   0.253597

In [156]:
# ============================================================
# STEP 24: CUMULATIVE CROSS-SCRIPT THRESHOLD METRICS
# ============================================================

thresholds = [50, 60, 70, 75, 80, 85, 90, 95]

total_candidates = len(cross_script)
total_true = len(true_cross_script)

results = []

for t in thresholds:

    candidate_mask = (
        cross_script[score_col] >= t
    )

    true_mask = (
        true_cross_script[score_col] >= t
    )

    candidates = candidate_mask.sum()
    true_captured = true_mask.sum()

    recall = (
        true_captured / total_true * 100
        if total_true > 0 else 0
    )

    candidate_rate = (
        candidates / total_candidates * 100
        if total_candidates > 0 else 0
    )

    results.append({
        "Threshold": t,
        "Candidates": candidates,
        "True Captured": true_captured,
        "True Recall %": recall,
        "Candidate %": candidate_rate
    })

threshold_analysis = pd.DataFrame(results)

print("=" * 100)
print("CROSS-SCRIPT CUMULATIVE THRESHOLD METRICS")
print("=" * 100)

display(threshold_analysis)

====================================================================================================
CROSS-SCRIPT CUMULATIVE THRESHOLD METRICS
====================================================================================================

   Threshold  Candidates  True Captured  True Recall %  Candidate %
0         50      251421         329238      95.530712    96.064878
1         60      221172         288486      83.706233    84.507107
2         70      149183         200185      58.085080    57.000993
3         75      104591         144200      41.840640    39.962937
4         80       60397          86105      24.983969    23.076952
5         85       21675          32572       9.450994     8.281751
6         90        3505           6249       1.813191     1.339217
7         95         469            874       0.253597     0.179199

In [157]:
# ============================================================
# STEP 25: MULTIPLE-CANDIDATE ANALYSIS
# ============================================================

THRESHOLD = 80

qualified = cross_script[
    cross_script["combined_score_translit"] >= THRESHOLD
].copy()

print("=" * 100)
print(f"MULTIPLE-CANDIDATE ANALYSIS — SCORE >= {THRESHOLD}")
print("=" * 100)

# Number of candidates per S1 entity
candidate_counts = (
    qualified
    .groupby("source1_entity_id")
    .size()
    .reset_index(name="candidate_count")
)

print("\nS1 entities with qualified candidates:", len(candidate_counts))

print("\nCandidate-count distribution:")
print(
    candidate_counts["candidate_count"]
    .value_counts()
    .sort_index()
    .head(20)
)

print("\nMaximum candidates for one S1 entity:",
      candidate_counts["candidate_count"].max())

# Entities having more than one candidate
multiple_candidates = candidate_counts[
    candidate_counts["candidate_count"] > 1
].copy()

print("\nS1 entities with >1 candidate:",
      len(multiple_candidates))

print("\nTotal qualified candidate rows:",
      len(qualified))

print("\nTop S1 entities with many candidates:")
display(
    multiple_candidates
    .sort_values("candidate_count", ascending=False)
    .head(20)
)

====================================================================================================
MULTIPLE-CANDIDATE ANALYSIS — SCORE >= 80
====================================================================================================

S1 entities with qualified candidates: 50811

Candidate-count distribution:
candidate_count
1    42206
2     7691
3      850
4       61
5        3
Name: count, dtype: int64

Maximum candidates for one S1 entity: 5

S1 entities with >1 candidate: 8605

Total qualified candidate rows: 60397

Top S1 entities with many candidates:

      source1_entity_id  candidate_count
8163       S1-246004420                5
25013      S1-540969303                5
40863       S1-82443192                5
6202       S1-210692425                4
50731      S1-998568047                4
23032      S1-506220317                4
16827       S1-39811475                4
7151       S1-227874238                4
9392       S1-267533518                4
13307      S1-336541763                4
2428       S1-142579261                4
11565      S1-305412443                4
2059       S1-136248523                4
15179      S1-368934507                4
12264      S1-318531872                4
25111      S1-542658927                4
7146       S1-227742668                4
11793       S1-30996154                4
8869       S1-258309426                4
9848       S1-274969382                4

In [158]:
# ============================================================
# STEP 26: INSPECT MULTIPLE MATCHES
# ============================================================

top_ids = multiple_candidates.nlargest(
    10,
    "candidate_count"
)["source1_entity_id"]

multiple_examples = qualified[
    qualified["source1_entity_id"].isin(top_ids)
].copy()

display(
    multiple_examples[
        [
            "source1_entity_id",
            "matched_entity_ids",
            "s1_name",
            "matched_name",
            "matched_name_latin",
            "s1_address",
            "matched_address",
            "name_score_translit",
            "address_score",
            "combined_score_translit"
        ]
    ]
    .sort_values(
        ["source1_entity_id", "combined_score_translit"],
        ascending=[True, False]
    )
)

,source1_entity_id,matched_entity_ids,s1_name,matched_name,matched_name_latin,s1_address,matched_address,name_score_translit,address_score,combined_score_translit
451382,S1-116730104,S2-949242721,Gold Baba Builders Private Limited,गोल्ड बाबा बिल्डर्स प्राइवेट लिमिटेड,golDa bAbA bilDarsa prAiveTa limiTeDa,"C-804, South End Homes Opp. Gyan Vihar Univers...","C-804, SOUTH END HOMES OPP. GYAN VIHAR UNIVERS...",84.507042,93.670886,88.172580
451383,S1-116730104,S2-525738619,Gold Baba Builders Private Limited,गोल्ड बाबा बिल्डर्स प्राइवेट लिमिटेड,golDa bAbA bilDarsa prAiveTa limiTeDa,"C-804, South End Homes Opp. Gyan Vihar Univers...","C-804, SOUTH END HOMES OPP. GYAN VIHAR UNIVERS...",84.507042,86.624204,85.353907
451384,S1-116730104,S2-581850772,Gold Baba Builders Private Limited,गोल्ड बाबा बिल्डर्स प्राइवेट लिमिटेड,golDa bAbA bilDarsa prAiveTa limiTeDa,"C-804, South End Homes Opp. Gyan Vihar Univers...","Rajasthan, C-804, JAIPUR, SOUTH END HOMES OPP....",84.507042,81.012658,83.109289
451381,S1-116730104,S2-373279353,Gold Baba Builders Private Limited,गोल्ड बाबा बिल्डर्स प्राइवेट लिमिटेड,golDa bAbA bilDarsa prAiveTa limiTeDa,"C-804, South End Homes Opp. Gyan Vihar Univers...","Rajasthan, SOUTH END HOMES OPP. GYAN VIHAR UNI...",84.507042,79.746835,82.602960
341290,S1-136248523,S2-582148603,Sree Tech Private Limited,श्री टेक Private Limited,shrI Teka Private Limited,907/111Maharaja Aggarsen Market 1St Floor Chaw...,DOOR NO G-907/111MAHARAJA AGGARSEN MARKET 1ST ...,84.000000,93.670886,87.868354
341288,S1-136248523,S2-331656205,Sree Tech Private Limited,श्री टेक प्राइवेट लिमिटेड,shrI Teka prAiveTa limiTeDa,907/111Maharaja Aggarsen Market 1St Floor Chaw...,G-907/111MAHARAJA AGGARSEN MARKET 1ST FLOOR CH...,73.076923,94.871795,81.794872
341289,S1-136248523,S2-548876044,Sree Tech Private Limited,श्री टेक प्राइवेट लिमिटेड,shrI Teka prAiveTa limiTeDa,907/111Maharaja Aggarsen Market 1St Floor Chaw...,G-907/111MAHARAJA AGGARSEN MARKET 1ST FLOOR CH...,73.076923,94.871795,81.794872
341287,S1-136248523,S2-116369112,Sree Tech Private Limited,श्री टेक प्राइवेट लिमिटेड,shrI Teka prAiveTa limiTeDa,907/111Maharaja Aggarsen Market 1St Floor Chaw...,NO G-907/111MAHARAJA AGGARSEN MARKET 1ST FLOOR...,73.076923,93.081761,81.078858
662549,S1-142579261,S2-996810134,Vijay Technologies Private Limited,విజయ్ టెక్నాలజీస్ ప్రైవేట్ లిమిటెడ్,vijay TèknAlajIs praiveT limiTèD,"12-463/A G1-Doctors Paradise Tadepalle, Guntur...","12-463/A G1-DOCTORS PARADISE TADEPALLE, GUNTUR...",72.727273,100.000000,83.636364
662550,S1-142579261,S2-613770789,Vijay Technologies Private Limited,విజయ్ టెక్నాలజీస్ ప్రైవేట్ లిమిటెడ్,vijay TèknAlajIs praiveT limiTèD,"12-463/A G1-Doctors Paradise Tadepalle, Guntur...","12-463/A G1-DOCTORS PARADISE TADEPALLE, GUNTUR...",72.727273,100.000000,83.636364
662551,S1-142579261,S2-189669243,Vijay Technologies Private Limited,విజయ్ టెక్నాలజీస్ ప్రైవేట్ లిమిటెడ్,vijay TèknAlajIs praiveT limiTèD,"12-463/A G1-Doctors Paradise Tadepalle, Guntur...","#12-463/A G1-DOCTORS PARADISE TADEPALLE, GUNTU...",72.727273,100.000000,83.636364
662552,S1-142579261,S2-736174563,Vijay Technologies Private Limited,విజయ్ టెక్నాలజీస్ ప్రైవేట్ లిమిటెడ్,vijay TèknAlajIs praiveT limiTèD,"12-463/A G1-Doctors Paradise Tadepalle, Guntur...","12-463/A G1-DOCTORS PARADISE TADEPALLE, GUNTUR...",72.727273,100.000000,83.636364
500692,S1-210692425,S2-136971823,Bharat Investments,भारत इन्वेस्टमेंट्स,bhArata invesTameMTsa,"A-5Plot-5A Jindal Mansion, Dr Gopalrao Deshmuk...","A-5PLOT-5A JINDAL MANSION, DR GOPALRAO DESHMUK...",87.179487,100.000000,92.307692
500693,S1-210692425,S2-268517999,Bharat Investments,भारत इन्वेस्टमेंट्स,bhArata invesTameMTsa,"A-5Plot-5A Jindal Mansion, Dr Gopalrao Deshmuk...","A-5PLOT-5A JINDAL MANSION, DR GOPALRAO DESHMUK...",87.179487,100.000000,92.307692
500690,S1-210692425,S2-746674087,Bharat Investments,भारत इन्वेस्टमेंट्स,bhArata invesTameMTsa,"A-5Plot-5A Jindal Mansion, Dr Gopalrao Deshmuk...","A-5PLOT-5A JINDAL MANSION, DR GOPALRAO DESHMUK...",87.179487,84.892086,86.264527
500691,S1-210692425,S2-76191591,Bharat Investments,भारत इन्वेस्टमेंट्स,bhArata invesTameMTsa,"A-5Plot-5A Jindal Mansion, Dr Gopalrao Deshmuk...","A-5PLOT-5A JINDAL MANSION, MUMBAI, Maharashtra",87.179487,77.192982,83.184885
245301,S1-227742668,S2-639891026,Surya Business Private Limited,સૂર્ય બિઝનેસ પ્રાઇવેટ લિમિટેડ,sUrya bijhanesa prAiveTa limiTeDa,"802, Fortune Devlopers, Fortune Business Hub, ...","0641 802, FORTUNE DEVLOPERS, FORTUNE BUSINESS ...",79.365079,97.237569,86.514075
245299,S1-227742668,S2-399347744,Surya Business Private Limited,સૂર્ય બિઝનેસ પ્રાઇવેટ લિમિટેડ,sUrya bijhanesa prAiveTa limiTeDa,"802, Fortune Devlopers, Fortune Business Hub, ...","H.NO 0641 802, FORTUNE DEVLOPERS, FORTUNE BUSI...",79.365079,94.623656,85.468510
245298,S1-227742668,S2-314793044,Surya Business Private Limited,સૂર્ય બિઝનેસ પ્રાઇવેટ લિમિટેડ,sUrya bijhanesa prAiveTa limiTeDa,"802, Fortune Devlopers, Fortune Business Hub, ...","H.NO 0641 802, FORTUNE DEVLOPERS, FORTUNE BUSI...",79.365079,87.567568,82.646075
245300,S1-227742668,S2-271459381,Surya Business Private Limited,સૂર્ય બિઝનેસ પ્રાઇવેટ લિમિટેડ,sUrya bijhanesa prAiveTa limiTeDa,"802, Fortune Devlopers, Fortune Business Hub, ...","H.NO 0641 802, FORTUNE DEVLOPERS, FORTUNE BUSI...",79.365079,87.567568,82.646075
206783,S1-227874238,S2-497607035,Modern Investments Private Limited,మోడర్న్ ఇన్వెస్ట్‌మెంట్స్ ప్రైవేట్ లిమిటెడ్,moDarn invèsT‌mèMTs praiveT limiTèD,"D.No.190/A/B Ganapavaram, Guntur, Krishna, And...","NO 190/A/B/3 GANAPAVARAM, GUNTUR, KRISHNA, And...",78.260870,96.296296,85.475040
206784,S1-227874238,S2-602287423,Modern Investments Private Limited,మోడర్న్ ఇన్వెస్ట్‌మెంట్స్ ప్రైవేట్ లిమిటెడ్,moDarn invèsT‌mèMTs praiveT limiTèD,"D.No.190/A/B Ganapavaram, Guntur, Krishna, And...","NO 190/A/B/3 GANAPAVARAM, GUNTUR, KRISHNA, And...",78.260870,96.296296,85.475040
206785,S1-227874238,S2-121660877,Modern Investments Private Limited,మోడర్న్ Investments Private Limited,moDarn Investments Private Limited,"D.No.190/A/B Ganapavaram, Guntur, Krishna, And...","GUNTUR, D.NO.190/A/B/3 GANAPAVARAM, KRISHNA, ఆ...",97.058824,63.551402,83.655855
206786,S1-227874238,S2-652330367,Modern Investments Private Limited,మోడర్న్ ఇన్వెస్ట్‌మెంట్స్ ప్రైవేట్ లిమిటెడ్,moDarn invèsT‌mèMTs praiveT limiTèD,"D.No.190/A/B Ganapavaram, Guntur, Krishna, And...","H.NO 190/A/B/3 GANAPAVARAM, KRISHNA, GUNTUR, A...",78.260870,83.636364,80.411067
458245,S1-246004420,S2-673770047,Om Hospitality Private Limited,ओम Hospitality Private Limited,oma Hospitality Private Limited,"Vivek Industrial Estate, Gala 17, Walbhat Rd, ...","महाराष्ट्र, null, MUMBAI, VIVEK INDUSTRIAL EST...",98.360656,67.469880,86.004345
458244,S1-246004420,S2-551947540,Om Hospitality Private Limited,ॐ हॉस्पिटैलिटी प्राइवेट लिमिटेड,OM haॉspiTailiTI prAiveTa limiTeDa,"Vivek Industrial Estate, Gala 17, Walbhat Rd, ...","VIVEK INDUSTRIAL ESTATE, GALA 17, WALBHAT RD, ...",81.250000,93.023256,85.959302
458247,S1-246004420,S2-213733537,Om Hospitality Private Limited,ॐ हॉस्पिटैलिटी प्राइवेट लिमिटेड,OM haॉspiTailiTI prAiveTa limiTeDa,"Vivek Industrial Estate, Gala 17, Walbhat Rd, ...","VIVEK INDUSTRIAL ESTATE, GALA 17, WALBHAT RD, ...",81.250000,92.215569,85.636228
458243,S1-246004420,S2-337627917,Om Hospitality Private Limited,ॐ हॉस्पिटैलिटी प्राइवेट लिमिटेड,OM haॉspiTailiTI prAiveTa limiTeDa,"Vivek Industrial Estate, Gala 17, Walbhat Rd, ...","VCVEK INDUSTRIAL ESTATE, GALA 17, WALBHAT RD, ...",81.250000,91.017964,85.157186
458246,S1-246004420,S2-476010839,Om Hospitality Private Limited,ॐ हॉस्पिटैलिटी प्राइवेट लिमिटेड,OM haॉspiTailiTI prAiveTa limiTeDa,"Vivek Industrial Estate, Gala 17, Walbhat Rd, ...","VIVEK INDUSTRIAL ESTATE, GALA 17, WALBHAT RD, ...",81.250000,80.722892,81.039157
287579,S1-25484047,S2-631464103,Future Consultants Limited,ફ્યુચર કન્સલ્ટન્ટ્સ લિમિટેડ,phyuchara kansalTanTsa limiTeDa,"580, 581, 582, 617, Navapura Dhumad, Savali, V...","580, 581, 582, 617, NAVAPURA DHUMAD, SAVALI, V...",66.666667,100.000000,80.000000
287580,S1-25484047,S2-383891588,Future Consultants Limited,ફ્યુચર કન્સલ્ટન્ટ્સ લિમિટેડ,phyuchara kansalTanTsa limiTeDa,"580, 581, 582, 617, Navapura Dhumad, Savali, V...","580, 581, 582, 617, NAVAPURA DHUMAD, SAVALI, V...",66.666667,100.000000,80.000000
287581,S1-25484047,S2-623722998,Future Consultants Limited,ફ્યુચર કન્સલ્ટન્ટ્સ લિમિટેડ,phyuchara kansalTanTsa limiTeDa,"580, 581, 582, 617, Navapura Dhumad, Savali, V...","580, 581, 582, 617, NAVAPURA DHUMAD, SAVALI, V...",66.666667,100.000000,80.000000
287582,S1-25484047,S2-567889224,Future Consultants Limited,ફ્યુચર કન્સલ્ટન્ટ્સ લિમિટેડ,phyuchara kansalTanTsa limiTeDa,"580, 581, 582, 617, Navapura Dhumad, Savali, V...","580, 581, 582, 617, NAVAPURA DHUMAD, SAVALI, V...",66.666667,100.000000,80.000000
187756,S1-540969303,S2-864911434,Shiv Super Media Private Limited,शिव सुपर मीडिया प्राइवेट लिमिटेड,shiva supara mIDiyA prAiveTa limiTeDa,C/O Nabila Arshad R/O A-44 Third Floor Shaheen...,C/O NABILA ARSHAD R/O A-44 THIRD FLOOR SHAHEEN...,81.159420,100.000000,88.695652
187757,S1-540969303,S2-850017273,Shiv Super Media Private Limited,शिव सुपर मीडिया प्राइवेट लिमिटेड,shiva supara mIDiyA prAiveTa limiTeDa,C/O Nabila Arshad R/O A-44 Third Floor Shaheen...,C/O NABILA ARSHAD R/O A-44 THIRD FLOOR SHAHEEN...,81.159420,100.000000,88.695652
187758,S1-540969303,S2-879633245,Shiv Super Media Private Limited,शिव सुपर मीडिया प्राइवेट लिमिटेड,shiva supara mIDiyA prAiveTa limiTeDa,C/O Nabila Arshad R/O A-44 Third Floor Shaheen...,C/O NABILA ARSHAD R/O A-44 THIRD FLOOR SHAHEEN...,81.159420,100.000000,88.695652
187759,S1-540969303,S2-288035176,Shiv Super Media Private Limited,शिव सुपर मीडिया प्राइवेट लिमिटेड,shiva supara mIDiyA prAiveTa limiTeDa,C/O Nabila Arshad R/O A-44 Third Floor Shaheen...,C/O NABILA ARSHAD R/O A-44 THIRD FLOOR SHAHEEN...,81.159420,100.000000,88.695652
187760,S1-540969303,S2-265195429,Shiv Super Media Private Limited,शिव सुपर मीडिया प्राइवेट लिमिटेड,shiva supara mIDiyA prAiveTa limiTeDa,C/O Nabila Arshad R/O A-44 Third Floor Shaheen...,C/O NABILA ARSHAD R/O A-44 THIRD FLOOR SHAHEEN...,81.159420,100.000000,88.695652
377527,S1-82443192,S2-577124023,East Guru Food Private Limited,ಈಸ್ಟ್ ಗುರು ಫುಡ್ ಪ್ರೈವೇಟ್ ಲಿಮಿಟೆಡ್,IsT guru phuD praiveT limiTèD,"No.59/3, 21St A Main, 16Th Cross Sector 1, Hsr...","NO 59/3, 21ST A MAIN, 16TH CROSS SECTOR 1, HSR...",74.576271,100.000000,84.745763
377530,S1-82443192,S2-914863960,East Guru Food Private Limited,ಈಸ್ಟ್ ಗುರು ಫುಡ್ ಪ್ರೈವೇಟ್ ಲಿಮಿಟೆಡ್,IsT guru phuD praiveT limiTèD,"No.59/3, 21St A Main, 16Th Cross Sector 1, Hsr...","NO.59/3, 21ST A MAIN, 16TH CROSS SECTOR 1, HSR...",74.576271,100.000000,84.745763
377529,S1-82443192,S2-567703573,East Guru Food Private Limited,ಈಸ್ಟ್ ಗುರು ಫುಡ್ ಪ್ರೈವೇಟ್ ಲಿಮಿಟೆಡ್,IsT guru phuD praiveT limiTèD,"No.59/3, 21St A Main, 16Th Cross Sector 1, Hsr...","H.NO 59/3, 21ST A MAIN, 16TH CROSS SECTOR 1, H...",74.576271,98.591549,84.182382
377528,S1-82443192,S2-13233676,East Guru Food Private Limited,ಈಸ್ಟ್ ಗುರು ಫುಡ್ ಪ್ರೈವೇಟ್ ಲಿಮಿಟೆಡ್,IsT guru phuD praiveT limiTèD,"No.59/3, 21St A Main, 16Th Cross Sector 1, Hsr...","NO 59/3, 21ST A MAIN, 16TH CROSS SECTOR 1, HSR...",74.576271,88.405797,80.108082
377531,S1-82443192,S2-457305579,East Guru Food Private Limited,ಈಸ್ಟ್ ಗುರು ಫುಡ್ ಪ್ರೈವೇಟ್ ಲಿಮಿಟೆಡ್,IsT guru phuD praiveT limiTèD,"No.59/3, 21St A Main, 16Th Cross Sector 1, Hsr...","NO.59/3, 21ST A MAIN, 16TH CROSS SECTOR 1, HSR...",74.576271,88.405797,80.108082

In [160]:
# ============================================================
# STEP 26: CANDIDATE SCORE-GAP ANALYSIS — FINAL FIX
# ============================================================

import pandas as pd
import numpy as np

THRESHOLD = 80

# ------------------------------------------------------------
# 1. Keep qualified candidates
# ------------------------------------------------------------

qualified = cross_script[
    cross_script["combined_score_translit"] >= THRESHOLD
].copy()

# ------------------------------------------------------------
# 2. Sort candidates from highest to lowest score
# ------------------------------------------------------------

qualified = qualified.sort_values(
    ["source1_entity_id", "combined_score_translit"],
    ascending=[True, False]
).copy()

# ------------------------------------------------------------
# 3. Assign candidate rank
# ------------------------------------------------------------

qualified["candidate_rank"] = (
    qualified
    .groupby("source1_entity_id")
    .cumcount() + 1
)

# ------------------------------------------------------------
# 4. Create one row per S1 entity
#    Columns = candidate ranks
# ------------------------------------------------------------

score_table = qualified.pivot_table(
    index="source1_entity_id",
    columns="candidate_rank",
    values="combined_score_translit",
    aggfunc="first"
)

# Rename candidate columns
score_table = score_table.rename(
    columns={
        1: "best_score",
        2: "second_score",
        3: "third_score",
        4: "fourth_score",
        5: "fifth_score"
    }
)

# ------------------------------------------------------------
# 5. Candidate count
# ------------------------------------------------------------

candidate_counts = (
    qualified
    .groupby("source1_entity_id")
    .size()
    .rename("candidate_count")
)

# ------------------------------------------------------------
# 6. Combine
# ------------------------------------------------------------

ambiguity = score_table.join(candidate_counts)

# ------------------------------------------------------------
# 7. Score gap
# ------------------------------------------------------------

ambiguity["score_gap"] = (
    ambiguity["best_score"] -
    ambiguity["second_score"]
)

print("=" * 100)
print("CROSS-SCRIPT CANDIDATE SCORE-GAP ANALYSIS")
print("=" * 100)

print("\nShape:", ambiguity.shape)

print("\nCandidate-count distribution:")
print(
    ambiguity["candidate_count"]
    .value_counts()
    .sort_index()
)

print("\nScore-gap statistics — multiple candidates only:")

multiple = ambiguity[
    ambiguity["candidate_count"] > 1
].copy()

print(
    multiple["score_gap"]
    .describe()
)

# ------------------------------------------------------------
# 8. Score-gap bands
# ------------------------------------------------------------

print("\n" + "=" * 100)
print("SCORE-GAP BANDS")
print("=" * 100)

gap_bins = [-0.0001, 1, 2, 5, 10, 20, 1000]

gap_labels = [
    "0-1",
    "1-2",
    "2-5",
    "5-10",
    "10-20",
    "20+"
]

gap_distribution = pd.cut(
    multiple["score_gap"],
    bins=gap_bins,
    labels=gap_labels,
    include_lowest=True
).value_counts().sort_index()

print(gap_distribution)

# ------------------------------------------------------------
# 9. Exact tied candidates
# ------------------------------------------------------------

exact_ties = multiple[
    multiple["score_gap"] == 0
]

print("\nExact ties:")
print(len(exact_ties))

# ------------------------------------------------------------
# 10. Most ambiguous S1 entities
# ------------------------------------------------------------

print("\n" + "=" * 100)
print("MOST AMBIGUOUS S1 ENTITIES")
print("=" * 100)

most_ambiguous_ids = (
    multiple
    .sort_values(
        ["score_gap", "candidate_count"],
        ascending=[True, False]
    )
    .head(20)
    .index
)

display(
    qualified[
        qualified["source1_entity_id"]
        .isin(most_ambiguous_ids)
    ][
        [
            "source1_entity_id",
            "matched_entity_ids",
            "s1_name",
            "matched_name",
            "matched_name_latin",
            "s1_address",
            "matched_address",
            "name_score_translit",
            "address_score",
            "combined_score_translit",
            "candidate_rank"
        ]
    ]
    .sort_values(
        ["source1_entity_id", "candidate_rank"]
    )
)

# ------------------------------------------------------------
# 11. Consistency checks
# ------------------------------------------------------------

print("\n" + "=" * 100)
print("CONSISTENCY CHECK")
print("=" * 100)

print(
    "Qualified candidate rows:",
    len(qualified)
)

print(
    "Unique S1 entities:",
    qualified["source1_entity_id"].nunique()
)

print(
    "Ambiguous S1 entities:",
    len(multiple)
)

print(
    "Maximum candidates:",
    int(ambiguity["candidate_count"].max())
)

print(
    "Score gaps available:",
    ambiguity["score_gap"].notna().sum()
)

====================================================================================================
CROSS-SCRIPT CANDIDATE SCORE-GAP ANALYSIS
====================================================================================================

Shape: (50811, 7)

Candidate-count distribution:
candidate_count
1    42206
2     7691
3      850
4       61
5        3
Name: count, dtype: int64

Score-gap statistics — multiple candidates only:
count    8605.000000
mean        2.141611
std         2.935199
min         0.000000
25%         0.000000
50%         0.817050
75%         3.448276
max        19.104478
Name: score_gap, dtype: float64

====================================================================================================
SCORE-GAP BANDS
====================================================================================================
score_gap
0-1      4511
1-2       851
2-5      1975
5-10     1029
10-20     239
20+         0
Name: count, dtype: int64

Exact ties:
3460

====================================================================================================
MOST AMBIGUOUS S1 ENTITIES
====================================================================================================

,source1_entity_id,matched_entity_ids,s1_name,matched_name,matched_name_latin,s1_address,matched_address,name_score_translit,address_score,combined_score_translit,candidate_rank
662549,S1-142579261,S2-996810134,Vijay Technologies Private Limited,విజయ్ టెక్నాలజీస్ ప్రైవేట్ లిమిటెడ్,vijay TèknAlajIs praiveT limiTèD,"12-463/A G1-Doctors Paradise Tadepalle, Guntur...","12-463/A G1-DOCTORS PARADISE TADEPALLE, GUNTUR...",72.727273,100.000000,83.636364,1
662550,S1-142579261,S2-613770789,Vijay Technologies Private Limited,విజయ్ టెక్నాలజీస్ ప్రైవేట్ లిమిటెడ్,vijay TèknAlajIs praiveT limiTèD,"12-463/A G1-Doctors Paradise Tadepalle, Guntur...","12-463/A G1-DOCTORS PARADISE TADEPALLE, GUNTUR...",72.727273,100.000000,83.636364,2
662551,S1-142579261,S2-189669243,Vijay Technologies Private Limited,విజయ్ టెక్నాలజీస్ ప్రైవేట్ లిమిటెడ్,vijay TèknAlajIs praiveT limiTèD,"12-463/A G1-Doctors Paradise Tadepalle, Guntur...","#12-463/A G1-DOCTORS PARADISE TADEPALLE, GUNTU...",72.727273,100.000000,83.636364,3
662552,S1-142579261,S2-736174563,Vijay Technologies Private Limited,విజయ్ టెక్నాలజీస్ ప్రైవేట్ లిమిటెడ్,vijay TèknAlajIs praiveT limiTèD,"12-463/A G1-Doctors Paradise Tadepalle, Guntur...","12-463/A G1-DOCTORS PARADISE TADEPALLE, GUNTUR...",72.727273,100.000000,83.636364,4
500692,S1-210692425,S2-136971823,Bharat Investments,भारत इन्वेस्टमेंट्स,bhArata invesTameMTsa,"A-5Plot-5A Jindal Mansion, Dr Gopalrao Deshmuk...","A-5PLOT-5A JINDAL MANSION, DR GOPALRAO DESHMUK...",87.179487,100.000000,92.307692,1
...,...,...,...,...,...,...,...,...,...,...,...
377527,S1-82443192,S2-577124023,East Guru Food Private Limited,ಈಸ್ಟ್ ಗುರು ಫುಡ್ ಪ್ರೈವೇಟ್ ಲಿಮಿಟೆಡ್,IsT guru phuD praiveT limiTèD,"No.59/3, 21St A Main, 16Th Cross Sector 1, Hsr...","NO 59/3, 21ST A MAIN, 16TH CROSS SECTOR 1, HSR...",74.576271,100.000000,84.745763,1
377530,S1-82443192,S2-914863960,East Guru Food Private Limited,ಈಸ್ಟ್ ಗುರು ಫುಡ್ ಪ್ರೈವೇಟ್ ಲಿಮಿಟೆಡ್,IsT guru phuD praiveT limiTèD,"No.59/3, 21St A Main, 16Th Cross Sector 1, Hsr...","NO.59/3, 21ST A MAIN, 16TH CROSS SECTOR 1, HSR...",74.576271,100.000000,84.745763,2
377529,S1-82443192,S2-567703573,East Guru Food Private Limited,ಈಸ್ಟ್ ಗುರು ಫುಡ್ ಪ್ರೈವೇಟ್ ಲಿಮಿಟೆಡ್,IsT guru phuD praiveT limiTèD,"No.59/3, 21St A Main, 16Th Cross Sector 1, Hsr...","H.NO 59/3, 21ST A MAIN, 16TH CROSS SECTOR 1, H...",74.576271,98.591549,84.182382,3
377528,S1-82443192,S2-13233676,East Guru Food Private Limited,ಈಸ್ಟ್ ಗುರು ಫುಡ್ ಪ್ರೈವೇಟ್ ಲಿಮಿಟೆಡ್,IsT guru phuD praiveT limiTèD,"No.59/3, 21St A Main, 16Th Cross Sector 1, Hsr...","NO 59/3, 21ST A MAIN, 16TH CROSS SECTOR 1, HSR...",74.576271,88.405797,80.108082,4
377531,S1-82443192,S2-457305579,East Guru Food Private Limited,ಈಸ್ಟ್ ಗುರು ಫುಡ್ ಪ್ರೈವೇಟ್ ಲಿಮಿಟೆಡ್,IsT guru phuD praiveT limiTèD,"No.59/3, 21St A Main, 16Th Cross Sector 1, Hsr...","NO.59/3, 21ST A MAIN, 16TH CROSS SECTOR 1, HSR...",74.576271,88.405797,80.108082,5

====================================================================================================
CONSISTENCY CHECK
====================================================================================================
Qualified candidate rows: 60397
Unique S1 entities: 50811
Ambiguous S1 entities: 8605
Maximum candidates: 5
Score gaps available: 8605

In [163]:
# Show dataframes currently available that contain candidate information
for name, obj in globals().items():
    if hasattr(obj, "columns"):
        cols = list(obj.columns)
        if "candidate_rank" in cols or "candidate_count" in cols:
            print(name, "->", obj.shape)
            print(cols)
            print()

v1_candidate_pairs -> (129478, 4)
['s1_count', 's2_count', 's3_count', 'candidate_count']

qualified -> (60397, 27)
['source1_entity_id', 'matched_entity_ids', 's1_block_key', 'matched_block_key', 'captured', 's1_name', 's1_address', 's1_country', 'matched_name', 'matched_address', 'matched_country', 'name_s1_norm', 'name_s2_norm', 'address_s1_norm', 'address_s2_norm', 'name_score', 'address_score', 'combined_score', 's1_script', 's2_script', 'matched_name_latin', 's1_name_norm', 's2_name_latin_norm', 'name_score_translit', 'combined_score_translit', 'matched_name_latin_norm', 'candidate_rank']

multiple_candidates -> (8605, 2)
['source1_entity_id', 'candidate_count']

ambiguity -> (50811, 7)
['best_score', 'second_score', 'third_score', 'fourth_score', 'fifth_score', 'candidate_count', 'score_gap']

ambiguous -> (8605, 4)
['best_score', 'second_score', 'candidate_count', 'score_gap']

multiple -> (8605, 7)
['best_score', 'second_score', 'third_score', 'fourth_score', 'fifth_score', 'candidate_count', 'score_gap']

exact_ties -> (3460, 7)
['best_score', 'second_score', 'third_score', 'fourth_score', 'fifth_score', 'candidate_count', 'score_gap']

In [164]:
# ============================================================
# STEP 28: AMBIGUOUS CANDIDATE FEATURE ANALYSIS
# ============================================================

print("=" * 100)
print("STEP 28 — AMBIGUOUS CANDIDATE FEATURE ANALYSIS")
print("=" * 100)

# ------------------------------------------------------------
# 1. Get candidate counts from qualified
# ------------------------------------------------------------

candidate_counts = (
    qualified
    .groupby("source1_entity_id")
    .size()
    .rename("candidate_count")
)

# ------------------------------------------------------------
# 2. Keep only S1 entities having multiple candidates
# ------------------------------------------------------------

ambiguous_candidates = qualified[
    qualified["source1_entity_id"].isin(
        candidate_counts[candidate_counts > 1].index
    )
].copy()

# ------------------------------------------------------------
# 3. Calculate score gap
# ------------------------------------------------------------

score_ranked = (
    ambiguous_candidates
    .sort_values(
        ["source1_entity_id", "combined_score_translit"],
        ascending=[True, False]
    )
    .copy()
)

score_ranked["candidate_rank"] = (
    score_ranked
    .groupby("source1_entity_id")
    .cumcount() + 1
)

best_scores = (
    score_ranked
    .groupby("source1_entity_id")["combined_score_translit"]
    .agg(
        best_score="first",
        second_score=lambda x: x.iloc[1] if len(x) > 1 else None
    )
)

best_scores["score_gap"] = (
    best_scores["best_score"] -
    best_scores["second_score"]
)

# ------------------------------------------------------------
# 4. Attach gap information
# ------------------------------------------------------------

score_ranked = score_ranked.merge(
    best_scores[["best_score", "second_score", "score_gap"]],
    left_on="source1_entity_id",
    right_index=True,
    how="left"
)

print("\nAmbiguous S1 entities:",
      score_ranked["source1_entity_id"].nunique())

# ------------------------------------------------------------
# 5. Score-gap statistics
# ------------------------------------------------------------

print("\nScore-gap statistics — multiple candidates only:")

print(
    best_scores["score_gap"].describe()
)

# ------------------------------------------------------------
# 6. Score-gap bands
# ------------------------------------------------------------

def gap_band(x):
    if x < 1:
        return "0-1"
    elif x < 2:
        return "1-2"
    elif x < 5:
        return "2-5"
    elif x < 10:
        return "5-10"
    elif x < 20:
        return "10-20"
    else:
        return "20+"

gap_bands = (
    best_scores["score_gap"]
    .apply(gap_band)
    .value_counts()
    .reindex(
        ["0-1", "1-2", "2-5", "5-10", "10-20", "20+"],
        fill_value=0
    )
)

print("\n" + "=" * 100)
print("SCORE-GAP BANDS")
print("=" * 100)

print(gap_bands)

# ------------------------------------------------------------
# 7. Exact ties
# ------------------------------------------------------------

exact_ties_count = (
    best_scores["score_gap"] == 0
).sum()

print("\nExact ties:")
print(exact_ties_count)

# ------------------------------------------------------------
# 8. Hardest ambiguous cases
# ------------------------------------------------------------

print("\n" + "=" * 100)
print("HARDEST AMBIGUOUS CASES — GAP < 1")
print("=" * 100)

hard_ambiguous = score_ranked[
    score_ranked["score_gap"] < 1
].copy()

print(
    "S1 entities with gap < 1:",
    hard_ambiguous["source1_entity_id"].nunique()
)

display(
    hard_ambiguous[
        [
            "source1_entity_id",
            "matched_entity_ids",
            "s1_name",
            "matched_name",
            "matched_name_latin",
            "s1_address",
            "matched_address",
            "name_score_translit",
            "address_score",
            "combined_score_translit",
            "candidate_rank",
            "score_gap"
        ]
    ]
    .sort_values(
        ["source1_entity_id", "candidate_rank"]
    )
    .head(150)
)

====================================================================================================
STEP 28 — AMBIGUOUS CANDIDATE FEATURE ANALYSIS
====================================================================================================

Ambiguous S1 entities: 8605

Score-gap statistics — multiple candidates only:
count    8605.000000
mean        2.141611
std         2.935199
min         0.000000
25%         0.000000
50%         0.817050
75%         3.448276
max        19.104478
Name: score_gap, dtype: float64

====================================================================================================
SCORE-GAP BANDS
====================================================================================================
score_gap
0-1      4507
1-2       850
2-5      1972
5-10     1034
10-20     242
20+         0
Name: count, dtype: int64

Exact ties:
3460

====================================================================================================
HARDEST AMBIGUOUS CASES — GAP < 1
====================================================================================================
S1 entities with gap < 1: 4507

,source1_entity_id,matched_entity_ids,s1_name,matched_name,matched_name_latin,s1_address,matched_address,name_score_translit,address_score,combined_score_translit,candidate_rank,score_gap
152834,S1-100449828,S2-100119491,Hotel Care Private Limited,होटल केयर प्राइवेट लिमिटेड,hoTala keyara prAiveTa limiTeDa,"Office No-1104, G Square Business Park, Plot N...","OFFICE NO-1104, G SQUARE BUSINESS PARK, PLOT N...",73.684211,90.625000,80.460526,1,0.000000
152835,S1-100449828,S2-226476559,Hotel Care Private Limited,होटल केयर प्राइवेट लिमिटेड,hoTala keyara prAiveTa limiTeDa,"Office No-1104, G Square Business Park, Plot N...","OFFICE NO-1104, G SQUARE BUSINESS PARK, PLOT N...",73.684211,90.625000,80.460526,2,0.000000
600591,S1-100469064,S2-512775597,First Investment Private Limited,फर्स्ट इन्वेस्टमेंट प्राइवेट लिमिटेड,pharsTa invesTameMTa prAiveTa limiTeDa,"711 Narayan Pethkaxmi Road, Pune, Maharashtra","711 NARAYAN PETHKAXMI ROAD, PUNE, Maharashtra",77.142857,100.000000,86.285714,1,0.470588
600593,S1-100469064,S2-48744415,First Investment Private Limited,फर्स्ट इन्वेस्टमेंट प्राइवेट लिमिटेड,pharsTa invesTameMTa prAiveTa limiTeDa,"711 Narayan Pethkaxmi Road, Pune, Maharashtra","711 NARAYAN PETHKAXMI ROD, PUNE, Maharashtra",77.142857,98.823529,85.815126,2,0.470588
283404,S1-101107998,S2-643645483,Sky Shakti Industries Private Limited,स्काई शक्ति इंडस्ट्रीज प्राइवेट लिमिटेड,skAI shakti iMDasTrIja prAiveTa limiTeDa,"C/O.Babalya Vithal Jadhav, A/Pkolape Tal. Boud...","C/O.BABALYA VITHAL JADHAV, A/PKOLAPE TAL. BOUD...",77.922078,86.904762,81.515152,1,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...
439867,S1-115699208,S2-898714572,My Trading Private Limited,माय ट्रेडिंग प्राइवेट लिमिटेड,mAya TreDiMga prAiveTa limiTeDa,"Plot No. Rz -8-A, F/F, Kh. No. 59/9, 13, 19 & ...","Delhi, PLOT NO. RZ -8-A, F/F, KH. NO. 59/9, 13...",77.192982,93.750000,83.815789,2,0.000000
145223,S1-115781627,S2-630037767,Gold Foundation Private Limited,गोल्ड फाउंडेशन प्राइवेट लिमिटेड,golDa phAuMDeshana prAiveTa limiTeDa,"250, Chuna Bhatti, Dudhia, Indore, Madhya Pradesh","250, CHUNA BHATTI, DUDHIA, INDORE, Madhya Pradesh",68.656716,100.000000,81.194030,1,0.000000
145224,S1-115781627,S2-204575964,Gold Foundation Private Limited,गोल्ड फाउंडेशन प्राइवेट लिमिटेड,golDa phAuMDeshana prAiveTa limiTeDa,"250, Chuna Bhatti, Dudhia, Indore, Madhya Pradesh","250, CHUNA BHATTI, DUDHIA, INDORE, Madhya Pradesh",68.656716,100.000000,81.194030,2,0.000000
369016,S1-115788461,S2-70497646,East Media Private Limited,ईस्ट मीडिया प्राइवेट लिमिटेड,IsTa mIDiyA prAiveTa limiTeDa,"Akbar Villa Qayyum Nagar, Moradabad, Uttar Pra...","AKBAR VILLA QAYYUM NAGAR, MORADABAD, Uttar Pra...",76.363636,100.000000,85.818182,1,0.833333
369015,S1-115788461,S2-130388754,East Media Private Limited,ईस्ट मीडिया प्राइवेट लिमिटेड,IsTa mIDiyA prAiveTa limiTeDa,"Akbar Villa Qayyum Nagar, Moradabad, Uttar Pra...","AKBAR VILLA QAYUYM NAGAR, MORADABAD, Uttar Pra...",76.363636,97.916667,84.984848,2,0.833333

In [167]:
# ============================================================
# STEP 29: CROSS-SCRIPT RANK QUALITY ANALYSIS
# ============================================================

print("=" * 100)
print("STEP 29 — CROSS-SCRIPT RANK QUALITY ANALYSIS")
print("=" * 100)

df = score_ranked.copy()

# ------------------------------------------------------------
# 1. True / false candidate counts per S1
# ------------------------------------------------------------

true_counts = (
    df.groupby("source1_entity_id")["captured"]
      .sum()
      .rename("true_candidate_count")
)

df = df.merge(
    true_counts,
    left_on="source1_entity_id",
    right_index=True,
    how="left"
)

print("\nTrue-candidate distribution among ambiguous S1 entities:")
print(
    true_counts.value_counts().sort_index()
)

# ------------------------------------------------------------
# 2. Is the top-ranked candidate true?
# ------------------------------------------------------------

top1 = df[df["candidate_rank"] == 1].copy()

top1_true = top1["captured"].sum()
top1_total = len(top1)

print("\n" + "=" * 100)
print("TOP-1 PERFORMANCE")
print("=" * 100)

print("Ambiguous S1 entities:", top1_total)
print("Top-1 true:", int(top1_true))
print(
    "Top-1 accuracy: {:.2f}%".format(
        100 * top1_true / top1_total
    )
)

# ------------------------------------------------------------
# 3. True candidate by rank
# ------------------------------------------------------------

rank_analysis = (
    df.groupby("candidate_rank")
      .agg(
          candidates=("captured", "size"),
          true_candidates=("captured", "sum")
      )
)

rank_analysis["true_rate_%"] = (
    100 *
    rank_analysis["true_candidates"] /
    rank_analysis["candidates"]
)

print("\n" + "=" * 100)
print("TRUE RATE BY CANDIDATE RANK")
print("=" * 100)

print(rank_analysis)

# ------------------------------------------------------------
# 4. Top candidate vs whether S1 has multiple true matches
# ------------------------------------------------------------

# Make sure top1 has candidate_count
# candidate_count is the number of qualified candidates for each S1 entity
candidate_counts = (
    qualified
    .groupby("source1_entity_id")
    .size()
    .rename("candidate_count")
    .reset_index()
)

# Count TRUE matches for each S1 entity
true_match_counts = (
    qualified
    .groupby("source1_entity_id")["captured"]
    .sum()
    .rename("true_match_count")
    .reset_index()
)

# Add candidate_count and true_match_count to top1
top1_analysis = (
    top1
    .drop(columns=["candidate_count", "true_match_count"], errors="ignore")
    .merge(candidate_counts, on="source1_entity_id", how="left")
    .merge(true_match_counts, on="source1_entity_id", how="left")
)

# Fill missing values safely
top1_analysis["candidate_count"] = (
    top1_analysis["candidate_count"]
    .fillna(0)
    .astype(int)
)

top1_analysis["true_match_count"] = (
    top1_analysis["true_match_count"]
    .fillna(0)
    .astype(int)
)

# Flag whether S1 has multiple true matches
top1_analysis["multiple_true_matches"] = (
    top1_analysis["true_match_count"] > 1
)

print("\n" + "=" * 100)
print("TOP-1 CANDIDATE VS TRUE MATCH COUNT")
print("=" * 100)

print(
    "S1 entities with multiple candidates:",
    (top1_analysis["candidate_count"] > 1).sum()
)

print(
    "S1 entities with multiple true matches:",
    top1_analysis["multiple_true_matches"].sum()
)

# ------------------------------------------------------------
# Display top-1 analysis
# ------------------------------------------------------------

display(
    top1_analysis[
        [
            "source1_entity_id",
            "matched_entity_ids",
            "s1_name",
            "matched_name",
            "matched_name_latin",
            "s1_address",
            "matched_address",
            "name_score_translit",
            "address_score",
            "combined_score_translit",
            "candidate_count",
            "true_match_count",
            "multiple_true_matches"
        ]
    ]
    .sort_values(
        ["candidate_count", "combined_score_translit"],
        ascending=[False, False]
    )
    .head(150)
)
# ------------------------------------------------------------
# 5. Exact ties
# ------------------------------------------------------------

print("\n" + "=" * 100)
print("EXACT-TIE ANALYSIS")
print("=" * 100)

exact_tie_s1 = best_scores[
    best_scores["score_gap"] == 0
].index

ties = df[
    df["source1_entity_id"].isin(exact_tie_s1)
].copy()

tie_summary = (
    ties.groupby("source1_entity_id")
        .agg(
            candidate_count=("matched_entity_ids", "size"),
            true_count=("captured", "sum")
        )
)

tie_summary["all_candidates_true"] = (
    tie_summary["true_count"] ==
    tie_summary["candidate_count"]
)

tie_summary["no_candidates_true"] = (
    tie_summary["true_count"] == 0
)

tie_summary["partial_true"] = (
    (tie_summary["true_count"] > 0) &
    (tie_summary["true_count"] <
     tie_summary["candidate_count"])
)

print("\nExact-tie S1 entities:", len(tie_summary))

print(
    "\nAll tied candidates true:",
    int(tie_summary["all_candidates_true"].sum())
)

print(
    "No tied candidates true:",
    int(tie_summary["no_candidates_true"].sum())
)

print(
    "Some tied candidates true:",
    int(tie_summary["partial_true"].sum())
)

# ------------------------------------------------------------
# 6. Show partial ties
# ------------------------------------------------------------

partial_tie_ids = tie_summary[
    tie_summary["partial_true"]
].index

partial_ties = ties[
    ties["source1_entity_id"].isin(partial_tie_ids)
].copy()

print("\n" + "=" * 100)
print("PARTIAL EXACT TIES — MOST IMPORTANT CASES")
print("=" * 100)

display(
    partial_ties[
        [
            "source1_entity_id",
            "matched_entity_ids",
            "s1_name",
            "matched_name",
            "matched_name_latin",
            "s1_address",
            "matched_address",
            "name_score_translit",
            "address_score",
            "combined_score_translit",
            "candidate_rank",
            "captured"
        ]
    ]
    .sort_values(
        ["source1_entity_id", "candidate_rank"]
    )
    .head(150)
)

====================================================================================================
STEP 29 — CROSS-SCRIPT RANK QUALITY ANALYSIS
====================================================================================================

True-candidate distribution among ambiguous S1 entities:
true_candidate_count
0    8605
Name: count, dtype: int64

====================================================================================================
TOP-1 PERFORMANCE
====================================================================================================
Ambiguous S1 entities: 8605
Top-1 true: 0
Top-1 accuracy: 0.00%

====================================================================================================
TRUE RATE BY CANDIDATE RANK
====================================================================================================
                candidates  true_candidates  true_rate_%
candidate_rank
1                     8605                0          0.0
2                     8605                0          0.0
3                      914                0          0.0
4                       64                0          0.0
5                        3                0          0.0

====================================================================================================
TOP-1 CANDIDATE VS TRUE MATCH COUNT
====================================================================================================
S1 entities with multiple candidates: 8605
S1 entities with multiple true matches: 0

,source1_entity_id,matched_entity_ids,s1_name,matched_name,matched_name_latin,s1_address,matched_address,name_score_translit,address_score,combined_score_translit,candidate_count,true_match_count,multiple_true_matches
4228,S1-540969303,S2-864911434,Shiv Super Media Private Limited,शिव सुपर मीडिया प्राइवेट लिमिटेड,shiva supara mIDiyA prAiveTa limiTeDa,C/O Nabila Arshad R/O A-44 Third Floor Shaheen...,C/O NABILA ARSHAD R/O A-44 THIRD FLOOR SHAHEEN...,81.159420,100.000000,88.695652,5,0,False
1367,S1-246004420,S2-673770047,Om Hospitality Private Limited,ओम Hospitality Private Limited,oma Hospitality Private Limited,"Vivek Industrial Estate, Gala 17, Walbhat Rd, ...","महाराष्ट्र, null, MUMBAI, VIVEK INDUSTRIAL EST...",98.360656,67.469880,86.004345,5,0,False
6918,S1-82443192,S2-577124023,East Guru Food Private Limited,ಈಸ್ಟ್ ಗುರು ಫುಡ್ ಪ್ರೈವೇಟ್ ಲಿಮಿಟೆಡ್,IsT guru phuD praiveT limiTèD,"No.59/3, 21St A Main, 16Th Cross Sector 1, Hsr...","NO 59/3, 21ST A MAIN, 16TH CROSS SECTOR 1, HSR...",74.576271,100.000000,84.745763,5,0,False
3180,S1-433054591,S2-220418946,Tirupati Hospitality Limited,తిరుపతి Hospitality లిమిటెడ్,tirupati Hospitality limiTèD,"6-3-898 Somajiguda, Hyderabad, Telangana","6-3-898 SOMAJIGUDA, HYDERABAD, Telangana",96.428571,100.000000,97.857143,4,0,False
1943,S1-303887578,S2-327902918,Al Projects Private Limited,अल प्रोजेक्ट्स Private Limited,ala projekTsa Private Limited,"Flat No.. 301, Gh.No.-7, Sec-45, Sector -45, G...","FLAT NO.. 301, GH.NO.-7, SEC-45, SECTOR -45, G...",92.857143,100.000000,95.714286,4,0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6066,S1-734317100,S2-508044149,Jay Apex Investments Limited,जय एपेक्स Investments लिमिटेड,jaya epeksa Investments limiTeDa,"B 34 Ist Floorlaxmi Nagar Vikas Marg, Delhi, E...","B 34. IST FLOORLAXMI NAGAR VIKAS MARG, DELHI, ...",86.666667,100.000000,92.000000,3,0,False
7887,S1-926096865,S2-229741669,Shyam Global Private Limited,श्याम ग्लोबल प्राइवेट लिमिटेड,shyAma globala prAiveTa limiTeDa,"Khs-260 Green Park Colony, Jalpura, Dadri, Gau...","KHS-260 GREEN PARK COLONY, JALPURA, DADRI, GAU...",86.666667,100.000000,92.000000,3,0,False
2255,S1-335685499,S2-429530928,Balaji Marketing Private Limited,बालाजी मार्केटिंग प्राइवेट लिमिटेड,bAlAjI mArkeTiMga prAiveTa limiTeDa,"81 Electric Dp Ke Pass Soni Colony, Guna, Madh...","81 ELECTRIC DP KE PASS SONI COLONY, GUNA, Madh...",86.567164,100.000000,91.940299,3,0,False
8041,S1-941656647,S2-101885606,Vision Energy Private Limited,विजन Energy Private Limited,vijana Energy Private Limited,H No. 165 K Sighi-2 Singhi Thana Sahatwar Teh ...,DOOR NO 16 K SIGHI-2 SINGHI THANA SAHATWR TEH ...,89.655172,95.238095,91.888342,3,0,False
2954,S1-408827121,S2-582447111,All Investment Limited,ऑल Investment Limited,ऑla Investment Limited,302 Iiird Floor G-Blockpankaj Tower-I Vikas Pu...,302 IIIRD FLOOR G-BLOCKPANKAJ TOWER-I VIKAS PU...,90.909091,93.333333,91.878788,3,0,False

====================================================================================================
EXACT-TIE ANALYSIS
====================================================================================================

Exact-tie S1 entities: 3460

All tied candidates true: 0
No tied candidates true: 3460
Some tied candidates true: 0

====================================================================================================
PARTIAL EXACT TIES — MOST IMPORTANT CASES
====================================================================================================

Empty DataFrame
Columns: [source1_entity_id, matched_entity_ids, s1_name, matched_name, matched_name_latin, s1_address, matched_address, name_score_translit, address_score, combined_score_translit, candidate_rank, captured]
Index: []

In [169]:
[x for x in globals().keys()
 if any(k in x.lower() for k in ["true", "match", "ground", "label", "pair"])]

['gt_pairs',
 'total_pairs',
 'captured_pairs',
 'missed_pairs',
 'v1_candidate_pairs',
 'empty_postal_match',
 'block_mismatch',
 'true_s2',
 'true_s2_scored',
 'SequenceMatcher',
 'true_captured',
 'true_recall',
 'true_cross_script',
 'total_true',
 'normalize_for_match',
 'labels',
 'true_bands',
 'true_counts',
 'true_mask',
 'gap_labels',
 'top1_true',
 'true_match_counts',
 'all_tied_true',
 'no_tied_true',
 'some_tied_true']

In [170]:
# ============================================================
# INSPECT GROUND-TRUTH STRUCTURE
# ============================================================

print("gt_pairs shape:", gt_pairs.shape)
print("gt_pairs columns:")
print(gt_pairs.columns.tolist())

print("\nFirst 10 ground-truth rows:")
display(gt_pairs.head(10))

print("\nqualified columns:")
print(qualified.columns.tolist())

gt_pairs shape: (7638365, 3)
gt_pairs columns:
['source1_entity_id', 'matched_entity_ids', 's1_block_key']

First 10 ground-truth rows:

  source1_entity_id matched_entity_ids s1_block_key
0         S1-965667       S2-681193310      US_maur
1         S1-965667       S2-743505751      US_maur
2         S1-965667       S3-775321672      US_maur
3         S1-965667        S3-11291185      US_maur
4         S1-965667       S3-860443364      US_maur
5       S1-55344266       S2-249013014   India_raji
6       S1-55344266       S2-197070651   India_raji
7       S1-55344266       S3-478195123   India_raji
8       S1-55344266       S3-384364074   India_raji
9      S1-343815751       S2-790675320      US_dahl

qualified columns:
['source1_entity_id', 'matched_entity_ids', 's1_block_key', 'matched_block_key', 'captured', 's1_name', 's1_address', 's1_country', 'matched_name', 'matched_address', 'matched_country', 'name_s1_norm', 'name_s2_norm', 'address_s1_norm', 'address_s2_norm', 'name_score', 'address_score', 'combined_score', 's1_script', 's2_script', 'matched_name_latin', 's1_name_norm', 's2_name_latin_norm', 'name_score_translit', 'combined_score_translit', 'matched_name_latin_norm', 'candidate_rank']

In [171]:
# ============================================================
# CHECK WHETHER GT PAIRS CAN BE MATCHED TO QUALIFIED
# ============================================================

print("Ground truth rows:", len(gt_pairs))
print("Qualified rows:", len(qualified))

# Show likely ID columns
print("\nGT dtypes:")
print(gt_pairs.dtypes)

print("\nQualified dtypes:")
print(
    qualified[
        ["source1_entity_id", "matched_entity_ids"]
    ].dtypes
)

Ground truth rows: 7638365
Qualified rows: 60397

GT dtypes:
source1_entity_id     str
matched_entity_ids    str
s1_block_key          str
dtype: object

Qualified dtypes:
source1_entity_id     str
matched_entity_ids    str
dtype: object

In [172]:
# ============================================================
# STEP 29 — CROSS-SCRIPT RANK QUALITY ANALYSIS
# ============================================================

import pandas as pd
import numpy as np

print("=" * 100)
print("STEP 29 — CROSS-SCRIPT RANK QUALITY ANALYSIS")
print("=" * 100)


# ------------------------------------------------------------
# 1. BUILD GROUND-TRUTH PAIR SET
# ------------------------------------------------------------

gt_pair_keys = pd.MultiIndex.from_frame(
    gt_pairs[
        ["source1_entity_id", "matched_entity_ids"]
    ]
)

qualified_pair_keys = pd.MultiIndex.from_frame(
    qualified[
        ["source1_entity_id", "matched_entity_ids"]
    ]
)

qualified = qualified.copy()

qualified["is_true"] = (
    qualified_pair_keys.isin(gt_pair_keys)
)

print("\nGround-truth rows:", len(gt_pairs))
print("Qualified candidate rows:", len(qualified))
print("True qualified candidates:", qualified["is_true"].sum())
print(
    "False qualified candidates:",
    (~qualified["is_true"]).sum()
)


# ------------------------------------------------------------
# 2. TRUE-CANDIDATE COUNT PER S1
# ------------------------------------------------------------

true_match_counts = (
    qualified
    .groupby("source1_entity_id")["is_true"]
    .sum()
    .rename("true_candidate_count")
)

candidate_counts = (
    qualified
    .groupby("source1_entity_id")
    .size()
    .rename("candidate_count")
)

entity_summary = pd.concat(
    [candidate_counts, true_match_counts],
    axis=1
).fillna(0)

entity_summary["candidate_count"] = (
    entity_summary["candidate_count"].astype(int)
)

entity_summary["true_candidate_count"] = (
    entity_summary["true_candidate_count"].astype(int)
)

entity_summary["multiple_true_matches"] = (
    entity_summary["true_candidate_count"] > 1
)


# ------------------------------------------------------------
# 3. AMBIGUOUS S1 ENTITIES
# ------------------------------------------------------------

ambiguous_ids = entity_summary.index[
    entity_summary["candidate_count"] > 1
]

ambiguous = entity_summary.loc[
    ambiguous_ids
].copy()

print("\n" + "=" * 100)
print("TRUE-CANDIDATE DISTRIBUTION AMONG AMBIGUOUS S1 ENTITIES")
print("=" * 100)

print(
    ambiguous["true_candidate_count"]
    .value_counts()
    .sort_index()
)


# ------------------------------------------------------------
# 4. TOP-1 PERFORMANCE
# ------------------------------------------------------------

top1 = (
    qualified[
        qualified["candidate_rank"] == 1
    ]
    .copy()
)

top1_true = top1["is_true"].sum()
top1_total = len(top1)

top1_accuracy = (
    100 * top1_true / top1_total
    if top1_total > 0 else 0
)

print("\n" + "=" * 100)
print("TOP-1 PERFORMANCE")
print("=" * 100)

print("Ambiguous S1 entities:", len(ambiguous))
print("Top-1 true:", int(top1_true))
print(f"Top-1 accuracy: {top1_accuracy:.2f}%")


# ------------------------------------------------------------
# 5. TRUE RATE BY CANDIDATE RANK
# ------------------------------------------------------------

rank_quality = (
    qualified
    .groupby("candidate_rank")
    .agg(
        candidates=("matched_entity_ids", "size"),
        true_candidates=("is_true", "sum")
    )
)

rank_quality["true_rate_%"] = (
    100
    * rank_quality["true_candidates"]
    / rank_quality["candidates"]
)

print("\n" + "=" * 100)
print("TRUE RATE BY CANDIDATE RANK")
print("=" * 100)

display(rank_quality)


# ------------------------------------------------------------
# 6. TOP-1 CANDIDATE VS TRUE MATCH COUNT
# ------------------------------------------------------------

top1_analysis = (
    qualified[
        qualified["candidate_rank"] == 1
    ][
        [
            "source1_entity_id",
            "matched_entity_ids",
            "s1_name",
            "matched_name",
            "matched_name_latin",
            "s1_address",
            "matched_address",
            "name_score_translit",
            "address_score",
            "combined_score_translit",
            "candidate_rank",
            "is_true"
        ]
    ]
    .merge(
        entity_summary[
            [
                "candidate_count",
                "true_candidate_count",
                "multiple_true_matches"
            ]
        ],
        left_on="source1_entity_id",
        right_index=True,
        how="left"
    )
)

print("\n" + "=" * 100)
print("TOP-1 CANDIDATE VS TRUE MATCH COUNT")
print("=" * 100)

print(
    "S1 entities with multiple candidates:",
    len(ambiguous)
)

print(
    "S1 entities with multiple true matches:",
    int(
        ambiguous["multiple_true_matches"].sum()
    )
)

display(
    top1_analysis
    .sort_values(
        ["candidate_count", "combined_score_translit"],
        ascending=[False, False]
    )
    .head(150)
)


# ------------------------------------------------------------
# 7. EXACT-TIE ANALYSIS
# ------------------------------------------------------------

# Recreate score summary directly from qualified candidates

score_pivot = (
    qualified
    .sort_values(
        ["source1_entity_id", "candidate_rank"]
    )
    .groupby("source1_entity_id")[
        "combined_score_translit"
    ]
    .apply(
        lambda x: list(x)
    )
)

tie_records = []

for s1_id, scores in score_pivot.items():

    if len(scores) < 2:
        continue

    best = scores[0]
    second = scores[1]

    if pd.notna(best) and pd.notna(second):

        tie_records.append(
            {
                "source1_entity_id": s1_id,
                "best_score": best,
                "second_score": second,
                "score_gap": best - second
            }
        )

tie_df = pd.DataFrame(tie_records)

exact_tie_ids = tie_df.loc[
    tie_df["score_gap"] == 0,
    "source1_entity_id"
]

exact_tie_candidates = qualified[
    qualified["source1_entity_id"].isin(
        exact_tie_ids
    )
].copy()

# Only candidates tied at the best score
exact_tie_candidates = exact_tie_candidates[
    exact_tie_candidates["combined_score_translit"]
    ==
    exact_tie_candidates.groupby(
        "source1_entity_id"
    )["combined_score_translit"].transform("max")
]

tie_truth = (
    exact_tie_candidates
    .groupby("source1_entity_id")["is_true"]
    .agg(
        all_tied_true="all",
        no_tied_true=lambda x: not x.any(),
        some_tied_true=lambda x: x.any() and not x.all()
    )
)

print("\n" + "=" * 100)
print("EXACT-TIE ANALYSIS")
print("=" * 100)

print("Exact-tie S1 entities:", len(exact_tie_ids))

if len(tie_truth) > 0:

    print(
        "All tied candidates true:",
        int(tie_truth["all_tied_true"].sum())
    )

    print(
        "No tied candidates true:",
        int(tie_truth["no_tied_true"].sum())
    )

    print(
        "Some tied candidates true:",
        int(tie_truth["some_tied_true"].sum())
    )

else:

    print("No exact ties found.")


# ------------------------------------------------------------
# 8. SCORE-GAP ANALYSIS
# ------------------------------------------------------------

score_gap_analysis = (
    qualified
    .sort_values(
        ["source1_entity_id", "candidate_rank"]
    )
    .groupby("source1_entity_id")
    .agg(
        best_score=(
            "combined_score_translit",
            "first"
        ),
        second_score=(
            "combined_score_translit",
            lambda x:
            x.iloc[1]
            if len(x) > 1
            else np.nan
        ),
        candidate_count=(
            "matched_entity_ids",
            "size"
        )
    )
)

score_gap_analysis["score_gap"] = (
    score_gap_analysis["best_score"]
    -
    score_gap_analysis["second_score"]
)

multiple_gap = score_gap_analysis[
    score_gap_analysis["candidate_count"] > 1
]["score_gap"].dropna()

print("\n" + "=" * 100)
print("SCORE-GAP ANALYSIS")
print("=" * 100)

print(
    multiple_gap.describe()
)


# ------------------------------------------------------------
# 9. GAP BANDS
# ------------------------------------------------------------

gap_bands = pd.cut(
    multiple_gap,
    bins=[-np.inf, 1, 2, 5, 10, 20, np.inf],
    labels=[
        "0-1",
        "1-2",
        "2-5",
        "5-10",
        "10-20",
        "20+"
    ],
    right=False
)

print("\n" + "=" * 100)
print("SCORE-GAP BANDS")
print("=" * 100)

print(gap_bands.value_counts().sort_index())

print(
    "\nExact ties:",
    int((multiple_gap == 0).sum())
)


# ------------------------------------------------------------
# 10. FINAL SANITY CHECK
# ------------------------------------------------------------

print("\n" + "=" * 100)
print("STEP 29 SANITY CHECK")
print("=" * 100)

print(
    "Qualified candidates:",
    len(qualified)
)

print(
    "True candidates:",
    int(qualified["is_true"].sum())
)

print(
    "False candidates:",
    int((~qualified["is_true"]).sum())
)

print(
    "True candidate rate:",
    f"{100 * qualified['is_true'].mean():.4f}%"
)

====================================================================================================
STEP 29 — CROSS-SCRIPT RANK QUALITY ANALYSIS
====================================================================================================

Ground-truth rows: 7638365
Qualified candidate rows: 60397
True qualified candidates: 60397
False qualified candidates: 0

====================================================================================================
TRUE-CANDIDATE DISTRIBUTION AMONG AMBIGUOUS S1 ENTITIES
====================================================================================================
true_candidate_count
2    7691
3     850
4      61
5       3
Name: count, dtype: int64

====================================================================================================
TOP-1 PERFORMANCE
====================================================================================================
Ambiguous S1 entities: 8605
Top-1 true: 50811
Top-1 accuracy: 100.00%

====================================================================================================
TRUE RATE BY CANDIDATE RANK
====================================================================================================

                candidates  true_candidates  true_rate_%
candidate_rank
1                    50811            50811        100.0
2                     8605             8605        100.0
3                      914              914        100.0
4                       64               64        100.0
5                        3                3        100.0

====================================================================================================
TOP-1 CANDIDATE VS TRUE MATCH COUNT
====================================================================================================
S1 entities with multiple candidates: 8605
S1 entities with multiple true matches: 8605

,source1_entity_id,matched_entity_ids,s1_name,matched_name,matched_name_latin,s1_address,matched_address,name_score_translit,address_score,combined_score_translit,candidate_rank,is_true,candidate_count,true_candidate_count,multiple_true_matches
187756,S1-540969303,S2-864911434,Shiv Super Media Private Limited,शिव सुपर मीडिया प्राइवेट लिमिटेड,shiva supara mIDiyA prAiveTa limiTeDa,C/O Nabila Arshad R/O A-44 Third Floor Shaheen...,C/O NABILA ARSHAD R/O A-44 THIRD FLOOR SHAHEEN...,81.159420,100.000000,88.695652,1,True,5,5,True
458245,S1-246004420,S2-673770047,Om Hospitality Private Limited,ओम Hospitality Private Limited,oma Hospitality Private Limited,"Vivek Industrial Estate, Gala 17, Walbhat Rd, ...","महाराष्ट्र, null, MUMBAI, VIVEK INDUSTRIAL EST...",98.360656,67.469880,86.004345,1,True,5,5,True
377527,S1-82443192,S2-577124023,East Guru Food Private Limited,ಈಸ್ಟ್ ಗುರು ಫುಡ್ ಪ್ರೈವೇಟ್ ಲಿಮಿಟೆಡ್,IsT guru phuD praiveT limiTèD,"No.59/3, 21St A Main, 16Th Cross Sector 1, Hsr...","NO 59/3, 21ST A MAIN, 16TH CROSS SECTOR 1, HSR...",74.576271,100.000000,84.745763,1,True,5,5,True
18832,S1-433054591,S2-220418946,Tirupati Hospitality Limited,తిరుపతి Hospitality లిమిటెడ్,tirupati Hospitality limiTèD,"6-3-898 Somajiguda, Hyderabad, Telangana","6-3-898 SOMAJIGUDA, HYDERABAD, Telangana",96.428571,100.000000,97.857143,1,True,4,4,True
264914,S1-303887578,S2-327902918,Al Projects Private Limited,अल प्रोजेक्ट्स Private Limited,ala projekTsa Private Limited,"Flat No.. 301, Gh.No.-7, Sec-45, Sector -45, G...","FLAT NO.. 301, GH.NO.-7, SEC-45, SECTOR -45, G...",92.857143,100.000000,95.714286,1,True,4,4,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
234975,S1-734317100,S2-508044149,Jay Apex Investments Limited,जय एपेक्स Investments लिमिटेड,jaya epeksa Investments limiTeDa,"B 34 Ist Floorlaxmi Nagar Vikas Marg, Delhi, E...","B 34. IST FLOORLAXMI NAGAR VIKAS MARG, DELHI, ...",86.666667,100.000000,92.000000,1,True,3,3,True
644806,S1-926096865,S2-229741669,Shyam Global Private Limited,श्याम ग्लोबल प्राइवेट लिमिटेड,shyAma globala prAiveTa limiTeDa,"Khs-260 Green Park Colony, Jalpura, Dadri, Gau...","KHS-260 GREEN PARK COLONY, JALPURA, DADRI, GAU...",86.666667,100.000000,92.000000,1,True,3,3,True
561117,S1-335685499,S2-429530928,Balaji Marketing Private Limited,बालाजी मार्केटिंग प्राइवेट लिमिटेड,bAlAjI mArkeTiMga prAiveTa limiTeDa,"81 Electric Dp Ke Pass Soni Colony, Guna, Madh...","81 ELECTRIC DP KE PASS SONI COLONY, GUNA, Madh...",86.567164,100.000000,91.940299,1,True,3,3,True
395881,S1-941656647,S2-101885606,Vision Energy Private Limited,विजन Energy Private Limited,vijana Energy Private Limited,H No. 165 K Sighi-2 Singhi Thana Sahatwar Teh ...,DOOR NO 16 K SIGHI-2 SINGHI THANA SAHATWR TEH ...,89.655172,95.238095,91.888342,1,True,3,3,True
616767,S1-408827121,S2-582447111,All Investment Limited,ऑल Investment Limited,ऑla Investment Limited,302 Iiird Floor G-Blockpankaj Tower-I Vikas Pu...,302 IIIRD FLOOR G-BLOCKPANKAJ TOWER-I VIKAS PU...,90.909091,93.333333,91.878788,1,True,3,3,True

====================================================================================================
EXACT-TIE ANALYSIS
====================================================================================================
Exact-tie S1 entities: 3460
All tied candidates true: 3460
No tied candidates true: 0
Some tied candidates true: 0

====================================================================================================
SCORE-GAP ANALYSIS
====================================================================================================
count    8605.000000
mean        2.141611
std         2.935199
min         0.000000
25%         0.000000
50%         0.817050
75%         3.448276
max        19.104478
Name: score_gap, dtype: float64

====================================================================================================
SCORE-GAP BANDS
====================================================================================================
score_gap
0-1      4507
1-2       850
2-5      1972
5-10     1034
10-20     242
20+         0
Name: count, dtype: int64

Exact ties: 3460

====================================================================================================
STEP 29 SANITY CHECK
====================================================================================================
Qualified candidates: 60397
True candidates: 60397
False candidates: 0
True candidate rate: 100.0000%